carbon-design-system/carbon-components-svelte

README.md
src/components/Search/Search.Skeleton.svelte
src/components/Search/Search.Story.svelte
src/components/Search/Search.stories.js
src/components/Search/Search.svelte
src/components/Search/index.js
src/index.js

**Changes**
- Add `Search` component
- Update list of supported components

feat(components): add Search component

---

README.md
src/components/RadioButton/RadioButton.stories.js
src/components/TextArea/TextArea.svelte

**Changes**
- Update `value` in the on:input event
- Remove forward events for `click`, `change`, `input`

refactor(text-area): update bound value on input

---

src/components/DataTableSkeleton/DataTable.stories.js
src/components/DataTableSkeleton/DataTableSkeleton.Story.svelte
src/components/DataTableSkeleton/DataTableSkeleton.svelte
src/components/DataTableSkeleton/index.js
src/index.js

Closes #29 
**Changes**
- Add DataTableSkeleton component

feat(component): add DataTableSkeleton

---

src/components/Copy/Copy.svelte

**Changes**
- Inline handleClick function
- Remove exported `props`
- Remove unused dispatcher

refactor(copy): inline handleClick, remove dispatcher

---

src/components/Tile/ClickableTile.svelte
src/components/Tile/ExpandableTile.svelte
src/components/Tile/RadioTile.svelte
src/components/Tile/SelectableTile.svelte
src/components/Tile/Tile.Story.svelte
src/components/Tile/Tile.stories.js
src/components/Tile/Tile.svelte
src/components/Tile/TileAboveTheFoldContent.svelte
src/components/Tile/TileBelowTheFoldContent.svelte
src/components/Tile/TileGroup.svelte
src/components/Tile/index.js
src/index.js

Supports #34
**Changes**
- Add initial Tile component
**TODO**
- remove exported props
- compose TileGroup, SelectableTile, RadioTile components

feat(components): add Tile

---

src/components/SkeletonPlaceholder/SkeletonPlaceholder.stories.js
src/components/SkeletonPlaceholder/SkeletonPlaceholder.svelte
src/components/SkeletonText/SkeletonText.svelte

refactor(skeleton): forward events, remove exported props

---

src/components/Accordion/Accordion.Skeleton.svelte
src/components/Accordion/Accordion.svelte
src/components/Accordion/AccordionItem.svelte

Supports #7
- Forward events
- Export style

refactor(accordion): remove expando, inline functions

---

README.md
src/components/ContentSwitcher/ContentSwitcher.Story.svelte
src/components/ContentSwitcher/ContentSwitcher.stories.js
src/components/ContentSwitcher/ContentSwitcher.svelte
src/components/ContentSwitcher/Switch.svelte
src/components/ContentSwitcher/index.js
src/index.js

Closes #33
**Changes**
- Add `ContentSwitcher`, `Switch` components
- Use children composition through context/store APIs

feat(components): add ContentSwitcher, Switch

---

README.md
src/components/Notification/InlineNotification.svelte
src/components/Notification/Notification.Story.svelte
src/components/Notification/Notification.stories.js
src/components/Notification/NotificationActionButton.svelte
src/components/Notification/NotificationButton.svelte
src/components/Notification/NotificationIcon.svelte
src/components/Notification/NotificationTextDetails.svelte
src/components/Notification/ToastNotification.svelte
src/components/Notification/index.js
src/index.js

feat(component): add Notification

---

src/components/Checkbox/Checkbox.Skeleton.svelte
src/components/Checkbox/Checkbox.Story.svelte
src/components/Checkbox/Checkbox.stories.js
src/components/Checkbox/Checkbox.svelte

- Forward events, inline functions
- Add style, remove exported props (#7)

fix(checkbox): support two way binding

---

README.md
src/components/ProgressIndicator/ProgressIndicator.Skeleton.svelte
src/components/ProgressIndicator/ProgressIndicator.Story.svelte
src/components/ProgressIndicator/ProgressIndicator.stories.js
src/components/ProgressIndicator/ProgressIndicator.svelte
src/components/ProgressIndicator/ProgressStep.svelte
src/components/ProgressIndicator/index.js
src/index.js

feat(component): add ProgressIndicator

---

src/components/ProgressIndicator/ProgressIndicator.Story.svelte

**Changes**
- Remove "Label" text from `ProgressStep` slot

fix(progress-indicator): correct Story

---

README.md
src/components/RadioButton/RadioButton.Skeleton.svelte
src/components/RadioButton/RadioButton.Story.svelte
src/components/RadioButton/RadioButton.svelte
src/components/RadioButtonGroup/RadioButtonGroup.Story.svelte
src/components/RadioButtonGroup/RadioButtonGroup.stories.js
src/components/RadioButtonGroup/RadioButtonGroup.svelte
src/components/RadioButtonGroup/index.js
src/components/Select/Select.Skeleton.svelte
src/components/Select/Select.Story.svelte
src/components/Select/Select.stories.js
src/components/Select/Select.svelte
src/components/Select/SelectItem.svelte
src/components/Select/SelectItemGroup.svelte
src/components/Select/index.js
src/components/TooltipDefinition/TooltipDefinition.Story.svelte
src/components/TooltipDefinition/TooltipDefinition.svelte
src/components/TooltipIcon/TooltipIcon.svelte
src/index.js

Closes #25, closes #31 
**Additional Changes**
- Forward events, remove external props in `TooltipIcon`, `TooltipDefinition`

feat(components): add RadioButtonGroup, Select, SelectItem, SelectItemGroup

---

CONTRIBUTING.md
README.md
package.json

Closes #5 
**Changes**
- Add `CONTRIBUTING.md`
- Specify required node (>=10), yarn (>=1) versions

docs: add contributing guidelines, update README

---

src/components/FileUploader/FileUploader.Skeleton.svelte
src/components/FileUploader/FileUploaderButton.svelte
src/components/FileUploader/FileUploaderItem.svelte
src/components/FileUploader/Filename.svelte
src/components/Form/Form.svelte
src/components/FormGroup/FormGroup.svelte
src/components/Search/Search.Story.svelte
src/components/Search/Search.stories.js
src/components/Search/Search.svelte
src/components/SkeletonText/SkeletonText.stories.js
src/components/SkeletonText/SkeletonText.svelte
src/components/TextArea/TextArea.svelte
src/components/TextInput/PasswordInput.svelte
src/components/TextInput/TextInput.svelte
src/components/TimePicker/TimePicker.Story.svelte
src/components/TimePicker/TimePicker.svelte
src/components/TimePicker/TimePickerSelect.svelte
src/components/Toggle/Toggle.Skeleton.svelte
src/components/Toggle/Toggle.Story.svelte
src/components/Toggle/Toggle.svelte
src/components/ToggleSmall/ToggleSmall.Story.svelte
src/components/ToggleSmall/ToggleSmall.svelte

**Changes**
- Prefer two-way binding and event forwarding over dispatching custom events
- Move reactive assignments (className) to markup

refactor(components): remove unnecessary dispatch, forward events

---

README.md
src/components/ListBox/ListBox.svelte
src/components/ListBox/ListBoxField.svelte
src/components/ListBox/ListBoxMenu.svelte
src/components/ListBox/ListBoxMenuIcon.svelte
src/components/ListBox/ListBoxMenuItem.svelte
src/components/ListBox/ListBoxSelection.svelte
src/components/ListBox/index.js
src/index.js

Closes #88
**Changes**
- Add `ListBox`, `ListBoxField`, `ListBoxMenu`, `ListBoxMenuIcon`, `ListBoxMenuItem`, `ListBoxSelection`

feat(components): add ListBox

---

README.md
src/components/Checkbox/Checkbox.svelte
src/components/ComboBox/ComboBox.svelte
src/components/ListBox/ListBox.svelte
src/components/ListBox/ListBoxField.svelte
src/components/ListBox/ListBoxMenu.svelte
src/components/ListBox/ListBoxSelection.svelte
src/components/MultiSelect/MultiSelect.Story.svelte
src/components/MultiSelect/MultiSelect.stories.js
src/components/MultiSelect/MultiSelect.svelte
src/components/MultiSelect/index.js
src/index.js

Closes #19 
**Changes**
- Add `MultiSelect` component
- Fix `ComboBox` to filter when opened

feat(component): add MultiSelect

---

package.json
src/components/InlineLoading/InlineLoading.test.js
src/components/Loading/Loading.test.js
src/internal/Icon.stub.svelte

**Changes**
- Stub `carbon-icons-svelte` module with `Icon.Stub.svelte`

test(components): add InlineLoading, Loading unit tests

---

.prettierignore
CHANGELOG.md
README.md
package.json
src/components/DatePicker/createCalendar.js

Closes #103 
**Changes**
- Fix Svelte module resolution by including `src` in published files (#102 )
- Fix DatePicker resolution error (from Svelte REPL); check l10n.en is truthy
- Add basic usage instructions to README
- Add link to CodeSandbox live example

docs: release v0.2.0, v0.2.1

---

palimpsest/public/index.html
palimpsest/src/components/ButtonTile.svelte
palimpsest/src/components/Component/Component.svelte
palimpsest/src/components/Component/ComponentPreview.svelte
palimpsest/src/components/Component/ComponentTab.svelte
palimpsest/src/components/Header.svelte
palimpsest/src/components/Home.svelte
palimpsest/src/components/SideNav.svelte
palimpsest/src/components/ThemePicker.svelte
palimpsest/src/store/index.js
src/components/Select/Select.svelte
src/components/Select/SelectItem.svelte

Supports #107 
**Changes**
- Fix `Select` component to programmatically set selected item

refactor: make docs responsive

---

palimpsest/src/components/ButtonTile.svelte
palimpsest/src/components/Component/Component.svelte
palimpsest/src/components/Home.svelte
palimpsest/src/components/SideNav.svelte
palimpsest/src/components/ThemePicker.svelte
src/components/Select/Select.svelte
src/components/Select/SelectItem.svelte

Supports #109 
**Changes**
- Fix `Select`, `SelecteItem` bugs to correctly update `selected` prop
- Refactor palimpsest `ThemePicker` which uses `Select`

fix(select): use afterUpdate, correct subscription behavior

---

package.json
src/components/Checkbox/Checkbox.Skeleton.svelte
src/components/Checkbox/Checkbox.Story.svelte
yarn.lock

Closes #61
**Changes**
- Bump `carbon-components` version to ^10.9.3
- Update `CheckboxSkeleton` classes

fix: update CheckboxSkeleton style

---

src/components/DatePicker/createCalendar.js

**Changes**
- Customize/set `l10n.en` if defined

fix(date-picker): move l10n customization to createCalendar

---

src/components/SkeletonText/SkeletonText.svelte

fix(skeleton-text): remove duplicate style attribute

---

CHANGELOG.md
package.json

**Changes**
- Fix `SkeletonText` duplicate attribute bug

chore(release): v0.3.2

---

src/components/Select/Select.svelte

Added event for select when it gets blur

added on:blur for select

---

src/components/UIShell/Content.svelte
src/components/UIShell/GlobalHeader/Header.svelte
src/components/UIShell/SkipToContent.svelte
src/components/UIShell/UIShell.Story.svelte
src/components/UIShell/index.js
src/index.js

**Changes**
- add Content, SkipToContent components
- forward click event in UI Shell Header component

Add Content, SkipToContent components

---

src/ComboBox/ComboBox.Story.svelte
src/ComboBox/ComboBox.svelte
src/Dropdown/Dropdown.Story.svelte
src/Dropdown/Dropdown.stories.js

fix(combo-box): close menu on Escape key

---

src/DatePicker/DatePicker.stories.js
src/DatePicker/DatePickerInput.svelte
src/ListBox/ListBox.svelte
src/ListBox/ListBoxField.svelte
src/NumberInput/NumberInput.stories.js
src/NumberInput/NumberInput.svelte
src/Select/Select.stories.js
src/Select/Select.svelte
src/TextInput/PasswordInput.svelte
src/TextInput/TextInput.stories.js
src/TextInput/TextInput.svelte

Also:
- fix(list-box): fix regression where size is overridden

feat: support size prop for input components

---

src/Grid/Column.svelte
src/Grid/Grid.Story.svelte
src/Grid/Grid.svelte
src/Grid/Row.svelte

- adds `noGutter`, `noGutterLeft`, `noGutterRight` props
- adds `aspectRatio` prop to `Column` component

feat(grid): support gutter, aspectRatio props

---

src/Grid/Grid.Story.svelte
src/Grid/Grid.svelte
src/Grid/Row.svelte

- adds `narrow` prop to `Grid`, `Row` components

feat(grid): support narrow prop for Grid, Row

---

COMPONENT_INDEX.md
src/UIShell/HeaderGlobalAction.svelte
src/UIShell/UIShell.Story.svelte
src/UIShell/UIShell.stories.js
src/UIShell/index.js
src/index.js
types/index.d.ts

**Features**
- UI Shell: add `HeaderGlobalAction` component

feat(ui-shell): add HeaderGlobalAction component

---

src/ProgressIndicator/ProgressIndicator.stories.js
src/ProgressIndicator/ProgressIndicator.svelte

fixes #262 
Adds `spaceEqual` prop and JSDoc, as well as class declaration. Updates default `ProgressIndicator` story with toggle

feat(progress-indicator): add spaceEqual prop and functionality

---

src/DataTable/DataTable.svelte
types/index.d.ts

Fixes #270
---
- fix(data-table): change DataTable headers prop type

fix(data-table): change DataTable headers prop type

---

src/TextInput/TextInput.stories.js
src/TextInput/TextInput.svelte

fixes #274 
- adds `warn` and `warnText` prop
- adds appropriate knobs to story
- add classes and aria attributes as shown in referenced commit

feat(text-input): add warn prop

---

src/DataTableSkeleton/DataTable.stories.js
src/DataTableSkeleton/DataTableSkeleton.svelte
types/index.d.ts

fixes #278
---
- feat(datatable-skeleton): change to size prop

feat(datatable-skeleton): change to size prop

---

package.json
yarn.lock

fixes #294 
- adds `husky`, `lint-staged`
https://github.com/josefaidt/carbon-components-svelte/blob/294-add-git-hooks/package.json#L86-L95

feat: add husky and lint-staged

---

src/Pagination/Pagination.stories.js
src/Pagination/Pagination.svelte

useful for programs that have fixed pagination size, which cannot / must not be changed by the user

feat(pagination): add pageSizeInputDisabled

---

src/Dropdown/Dropdown.svelte

chore(dropdown): remove unused setContext import

---

src/DatePicker/createCalendar.js

remove locales from DatePicker / flatpickr

---

src/UIShell/GlobalHeader/HeaderAction.svelte

fix(HeaderAction): panel closes when user clicks inside the browser window, not just inside the page body

---

COMPONENT_INDEX.md
docs/src/pages/components/ContentSwitcher.svx
src/ContentSwitcher/ContentSwitcher.svelte
types/index.d.ts

**Features**
- feat(content-switcher): add "sm", "xl" size variants
- ContentSwitcher: add examples "Extra-large size" and "Small size"

ContentSwitcher: add "sm", "xl" size variants

---

COMPONENT_INDEX.md
docs/src/pages/components/CodeSnippet.svx
src/CodeSnippet/CodeSnippet.svelte
types/index.d.ts

**Features**
- feat(code-snippet): add wrapText prop for "multi" type CodeSnippet
- CodeSnippet: add example "Wrap text"

feat(code-snippet): add wrapText prop

---

package.json
scripts/build-css.js
yarn.lock

- chore(deps-dev): bump carbon-components to ^v10.22

chore(deps-dev): bump carbon-components to ^v10.22

---

docs/src/pages/components/DataTable.svx

related to https://github.com/IBM/carbon-components-svelte/pull/356#issuecomment-715453911
---
- feat(docs): add datatable display and sort example
- fix(docs): string interpolation in display method body

feat(docs): add datatable display and sort example

---

docs/src/pages/components/DataTable.svx

- docs(datatable): simplify date sort method operation: `new Date(a) - new Date(b)`
- fix sortable with custom methods example order: moved after `Sortable` example

docs(datatable): simplify date sort method operation

---

docs/src/components/ComponentApi.svelte

closes #390
---
- docs: add line replace method for code tags

docs: add line replace method for code tags

---

docs/src/pages/components/ComboBox.svx
docs/src/pages/components/Dropdown.svx
docs/src/pages/components/MultiSelect.svx
docs/src/pages/framed/ComboBox/MultipleComboBox.svelte
docs/src/pages/framed/Dropdown/MultipleDropdown.svelte
docs/src/pages/framed/MultiSelect/MultipleMultiSelect.svelte
src/ListBox/ListBox.svelte

#388
**Changes**
- fixes a bug where the dropdown menu would not close if there are multiple combo box, multi-select dropdown components
- add usage examples to ComboBox, Dropdown, MultiSelect

fix(list-box): remove stopPropagation click modifier

---

README.md
docs/src/components/ComponentApi.svelte
docs/src/pages/components/OrderedList.svx
docs/src/pages/index.svelte
package.json
yarn.lock

- escape HTML in component prop descriptions on the docsite
- describe use case for using OrderedList native styles (closes #418)
- update description in README, docsite home page
- update count for icons, charts packages
- pin `sveld` development dependency to v0.3.0

improve documentation

---

src/UIShell/HeaderSearch.svelte

set selectedResultIndex in HeaderSearch on click

---

src/UIShell/GlobalHeader/Header.svelte
src/UIShell/SideNav/SideNav.svelte
src/UIShell/navStore.js

ref #434 
Header will now conditionally render hamburger menu in mobile if a SideNav exists. No change to props or DX.

feat(UIShell): only render hamburger menu if SideNav exists

---

docs/src/COMPONENT_API.json
src/TextInput/PasswordInput.svelte
src/TextInput/TextInput.svelte
types/TextInput/PasswordInput.d.ts
types/TextInput/TextInput.d.ts

This PR contains a fix for issue #480

move restProps from wrapper to input for TextInput and PasswordInput

---

src/OverflowMenu/OverflowMenu.svelte

This contains a fix for issue: #474

Close overflow menu on focusout

---

docs/src/COMPONENT_API.json
src/DataTable/DataTable.svelte
tests/DataTable.test.svelte
types/DataTable/DataTable.d.ts

**Fixes**
- specify that restProps are forwarded to "div", fixes #524

fix(data-table): specify that restProps are forwarded to "div" #524

---

actions/truncate.js

**Fixes**
- fix `truncate` Svelte action to preserve existing class names on node

fix(truncate): preserve existing class names on node

---

src/UIShell/SideNav/SideNav.svelte

SideNav overlay should be applied when not fixed.
Reference: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/UIShell/SideNav.js#L118

fix(SideNav): apply overlay for non-fixed sidenav instances, ref #544

---

src/DataTable/DataTable.svelte
types/DataTable/DataTable.d.ts

PR related with [issue](#609).

Adding display attr to DataTableCell

---

COMPONENT_INDEX.md
docs/package.json
docs/src/COMPONENT_API.json
docs/src/pages/_layout.svelte
docs/src/pages/components/ProgressBar.svx
docs/src/pages/framed/ProgressBar/ProgressBarUx.svelte
docs/yarn.lock
package.json
src/DataTable/ToolbarSearch.svelte
src/Notification/InlineNotification.svelte
src/Notification/ToastNotification.svelte
src/ProgressBar/ProgressBar.svelte
src/ProgressBar/index.js
src/TextInput/TextInput.svelte
src/index.js
tests/ProgressBar.test.svelte
types/ProgressBar/ProgressBar.d.ts
types/index.d.ts
yarn.lock

**Features**
- add ProgressBar component
**Fixes**
- omit size prop in `ToolbarSearch`
- omit passing iconDescription to `NotificationIcon` in `InlineNotification`, `ToastNotification`
**Refactor**
- use class directive in `TextInput`
- add ProgressBar component documentation
- upgrade `carbon-components` to version 10.37.0

Align v10.37

---

src/ComposedModal/ComposedModal.svelte
src/Modal/Modal.svelte

Fix: trap tab focus within modal

---

src/TextArea/TextArea.svelte

fix(text-area): omit prop if readonly={false} #710

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
docs/src/pages/_layout.svelte
docs/src/pages/components/OrderedList.svx
docs/src/pages/components/RecursiveList.svx
docs/src/pages/components/UnorderedList.svx
docs/src/pages/framed/RecursiveList/RecursiveList.svelte
docs/src/pages/framed/RecursiveList/RecursiveListOrdered.svelte
docs/src/pages/framed/RecursiveList/RecursiveListOrderedNative.svelte
src/RecursiveList/RecursiveList.svelte
src/RecursiveList/RecursiveListItem.svelte
src/RecursiveList/index.js
src/index.js
tests/ProgressBar.test.svelte
tests/RecursiveList.test.svelte
types/RecursiveList/RecursiveList.d.ts
types/index.d.ts

This component uses the [svelte:self API](https://svelte.dev/docs#svelte_self) to render the `UnorderedList` and `OrderedList` components with data formatted as a tree structure. This is especially useful when the depth of the tree is unknown.
A child node can render text (`text`), a link (`href`), HTML content (`html`), and other `children`.
Sample usage:
```svelte
<script>
import { RecursiveList } from "carbon-components-svelte";
const children = [
{
text: "Item 1",
children: [
{
text: "Item 1a",
children: [{ html: "<h5>HTML content</h5>" }],
},
],
},
{
text: "Item 2",
children: [
{
href: "https://svelte.dev/",
},
{
href: "https://svelte.dev/",
text: "Link with custom text",
},
],
},
{
text: "Item 3",
},
];
</script>
<RecursiveList children="{children}" />
```
---
TODO:

RecursiveList

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
docs/src/pages/components/DataTable.svx
src/DataTable/DataTable.svelte
types/DataTable/DataTable.d.ts

feat(data-table): make title, description slottable #720

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
docs/src/pages/framed/TreeView/TreeViewExpanded.svelte
src/TreeView/TreeView.svelte
src/TreeView/TreeViewNodeList.svelte
tests/TreeView.test.svelte
types/TreeView/TreeView.d.ts

**Features**
- support two-way binding for expanded nodes in `TreeView` via the `expandedIds` prop

feat(tree-view): add expandedIds #750

---

README.md
docs/src/components/Footer.svelte
docs/src/pages/_layout.svelte
docs/src/pages/components/Button.svx
docs/src/pages/components/OrderedList.svx
docs/src/pages/components/UnorderedList.svx
docs/src/pages/index.svelte

Improve docs

---

README.md
docs/src/components/Footer.svelte
docs/src/pages/_layout.svelte
docs/src/pages/components/Button.svx
docs/src/pages/components/OrderedList.svx
docs/src/pages/components/UnorderedList.svx
docs/src/pages/index.svelte
src/Button/Button.svelte

Fixes #755
**Fixes**
- omit disabled attribute in `Button` if falsy

fix(button): only set disabled attribute if true #755

---

src/ComboBox/ComboBox.svelte

Fixes #768
Todo:
- do not set default selectedIndex value to 0; value cannot be cleared by clicking the "X"

fix(combo-box): fix reactivity regression #768

---

docs/src/pages/components/ComboBox.svx
src/ComboBox/ComboBox.svelte

This PR added support to clear the ComboBox component programmatically.
You can clear the ComboBox by changing `selectedIndex = -1`

Clear ComboBox Programaticaly

---

src/DatePicker/DatePicker.svelte
types/DatePicker/DatePicker.d.ts

added the staticProp property for the Modal component to work correctly #753

added the staticProp property for the DatePicker component to work correctly

---

src/Tooltip/Tooltip.svelte

Proposal to fix https://github.com/carbon-design-system/carbon-components-svelte/issues/894

fix(Tooltip): fix two way binding in cases where icon is in focus

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/Form/Form.svelte
tests/Form.test.svelte
types/Form/Form.svelte.d.ts

Add ref prop to `Form`

---

src/DatePicker/DatePicker.svelte

fix(date-picker): set calendar to null

---

COMPONENT_INDEX.md
docs/package.json
docs/src/COMPONENT_API.json
docs/src/pages/components/InlineNotification.svx
docs/src/pages/components/ToastNotification.svx
docs/yarn.lock
package.json
src/Notification/InlineNotification.svelte
src/Notification/NotificationTextDetails.svelte
src/Notification/ToastNotification.svelte
src/Tile/ExpandableTile.svelte
src/UIShell/GlobalHeader/HeaderNavItem.svelte
src/UIShell/GlobalHeader/HeaderNavMenu.svelte
types/Notification/InlineNotification.svelte.d.ts
types/Notification/ToastNotification.svelte.d.ts
yarn.lock

**Features**
- support `UIShell` HeaderNavMenu with current item
- make `InlineNotification` title/subtitle props slottable 
- make `ToastNotification` title/subtitle/caption props slottable 
**Refactor**
- remove unnecessary "position: relative" style in `ExpandableTile`
- remove unused `refContent` in `ExpandableTile`
- upgrade `carbon-components` to v10.48.0

Align v10.48

---

src/Pagination/Pagination.svelte

When in last page of data and the page size get changed to a bigger size the current page number will be out of range of total pages.
This code will set the page number in range of total pages.

Correct page number when dispatching update

---

src/Tabs/Tabs.svelte

Fix: Tabs dispatch change event on init

---

src/TextArea/TextArea.svelte
src/TextInput/PasswordInput.svelte
src/TextInput/TextInput.svelte

fix(textinput): displaying empty input value if value is undefined or null

---

src/DataTable/DataTable.svelte

fix(data-table): forgo "click", "click:row" events if target is a checkbox, radio button

---

src/DataTable/ToolbarSearch.svelte

fix(toolbar-search): input should expand if value is programmatically set

---

src/DatePicker/DatePicker.svelte

fix(date-picker): input should not lose focus when pressing "Enter"

---

docs/src/pages/components/DatePicker.svx
examples/rollup/rollup.config.js

Document `DatePicker` usage with a Rollup set-up

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
docs/src/pages/components/Toggle.svx
src/Toggle/Toggle.svelte
types/Toggle/Toggle.svelte.d.ts

```svelte
<Toggle labelText="Push notifications">
<span slot="labelA" style="color: red">No</span>
<span slot="labelB" style="color: green">Yes</span>
</Toggle>
```

Make `Toggle` labels slottable

---

src/Checkbox/Checkbox.svelte

Fixes https://github.com/carbon-design-system/carbon-components-svelte/issues/977

Emit change event after modifying interal state

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
docs/src/pages/components/Dropdown.svx
docs/src/pages/framed/Dropdown/MultipleDropdown.svelte
src/Dropdown/Dropdown.svelte
tests/Dropdown.test.svelte
types/Dropdown/Dropdown.svelte.d.ts

part of #1003
Modify `selectedIndex` to `selectedId` in Dropdown component.
(I will create another PR for ComboBox later to make the diff smaller.)

feat(Dropdown): selectedIndex -> selectedId

---

src/Dropdown/Dropdown.svelte

https://user-images.githubusercontent.com/1846548/149938326-e2ab9415-3178-429d-bbf7-0f0cdd66a529.mp4

fix(Dropdown): list icon was clickable in disabled state

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/Checkbox/Checkbox.svelte
types/Checkbox/Checkbox.svelte.d.ts

Add `required` prop to Checkbox.

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/RadioButton/RadioButton.svelte
types/RadioButton/RadioButton.svelte.d.ts

Adds `required` prop and corrects minor documentation issues.
Fixes #1034.

Add `required` prop to `RadioButton`.

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/Tooltip/Tooltip.svelte
tests/Tooltip.test.svelte
types/Tooltip/Tooltip.svelte.d.ts

**Fixes**
- type open/close events for `Tooltip`

fix(tooltip): `Tooltip.svelte.d.ts` is missing open/close events

---

src/ContentSwitcher/Switch.svelte

fix(content-switcher): Switch should have `type="button"`

---

docs/src/pages/components/FileUploader.svx
docs/src/pages/framed/FileUploader/FileUploaderClearFiles.svelte

- add `FileUploader` "Clear files" example
- document `validateFiles` prop for `FileUploaderDropContainer`
- add descriptions for `FileUploaderButton`, `FileUploader` examples

docs(file-uploader): add "Clear files" example, document "validateFiles" prop

---

css/_popover.scss
css/all.scss
css/g10.scss
css/g100.scss
css/g80.scss
css/g90.scss
css/white.scss
scripts/build-css.js

fix: inline `Popover` styles from carbon-components v10.47

---

src/UIShell/GlobalHeader/HeaderAction.svelte

This audits the `HeaderAction` component when using the `text` prop:
- change "100% width" to be auto
- use `body-short-01` font styles
- use consistent text color as `Header` platform text
- fix icon alignment with `HeaderActionLink`

fix(header-action): audit `HeaderAction` text styles

---

LICENSE

chore(license): add copyright metadata

---

src/DataTable/DataTable.svelte

perf(data-table): only render table row content when expanded

---

src/NumberInput/NumberInput.svelte

fix(number-input): slotted label should render correctly

---

COMPONENT_INDEX.md
docs/package.json
docs/src/COMPONENT_API.json
docs/src/pages/components/ProgressBar.svx
docs/yarn.lock
package.json
src/ProgressBar/ProgressBar.svelte
tests/ProgressBar.test.svelte
types/ProgressBar/ProgressBar.svelte.d.ts
yarn.lock

**Features**
- add `kind` prop to `ProgressBar` to support inline, indented variants
- add `ProgressBar` examples "Inline variant" and "Indented variant"
- upgrade `carbon-components` to v10.56.0

Align 10.56

---

src/index.js
types/index.d.ts

feat(breakpoint): export breakpointObserver, breakpoints

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/UIShell/HeaderGlobalAction.svelte

fix(header-global-action): icon slot should have a default size of 20

---

docs/svelte.config.js

This PR generates imports for actions (e.g., `truncate`).

docs(action): generate action imports

---

docs/src/pages/components/DataTable.svx
docs/src/pages/framed/Breakpoint/Breakpoint.svelte
docs/src/pages/framed/DataTable/DataTableBatchSelection.svelte
docs/src/pages/framed/DataTable/DataTableBatchSelectionInitial.svelte
docs/src/pages/framed/DataTable/DataTableExpandableSelectable.svelte
docs/src/pages/framed/DataTable/DataTableExpandableZebra.svelte
docs/src/pages/framed/DataTable/DataTableNonExpandableRows.svelte
docs/src/pages/framed/DataTable/SelectableDataTable.svelte
docs/src/pages/framed/LocalStorage/LocalStorage.svelte

- add `DataTable` "Expandable and selectable" example
- add `DataTable` "Batch selection" example

docs(data-table): add "Expandable and selectable" example

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/CodeSnippet/CodeSnippet.svelte
tests/CodeSnippet.test.svelte
types/CodeSnippet/CodeSnippet.svelte.d.ts

```svelte
<CodeSnippet
type="multi"
{code}
on:expand={() => {
console.log("expand");
}}
on:collapse={() => {
console.log("collapse");
}}
/>
```

feat(code-snippet): dispatch "expand" and "collapse" events

---

src/DataTable/DataTable.svelte

fix(data-table): apply custom widths to empty columns

---

src/Notification/InlineNotification.svelte
src/Notification/ToastNotification.svelte

fix: allow preventdefault in toast notification on:close

---

src/ComboBox/ComboBox.svelte

fix(ComboBox): fix an issue, when selection via typing does not work as expected, resolves #1222

---

docs/src/components/ComponentApi.svelte
docs/src/global.css
docs/src/pages/_layout.svelte
docs/src/pages/components/ExpandableTile.svx
docs/src/pages/components/OverflowMenu.svx

docs(expandable-tile): add "With interactive content" example

---

src/Modal/Modal.svelte

fix(modal): prevent submitting `Modal` on enter if prop `primaryButtonDisabled` is true

---

src/DatePicker/DatePickerInput.svelte

fix(date-picker): display warn/invalid icons in input with calendar

---

src/ProgressIndicator/ProgressStep.svelte

fix(progress-step): button should have type="button"

---

src/DataTable/TableHeader.svelte

To prevent form submission when placed inside a form.

TableHeader: add type="button" to button

---

docs/src/global.css

The same class is defined twice.

docs: fix redundant css class

---

docs/package.json
docs/yarn.lock
package.json
yarn.lock

chore(deps-dev): upgrade `svelte` to v4.2.0

---

docs/src/pages/components/Button.svx
docs/src/pages/framed/Button/ProgrammaticFocus.svelte

docs(button): add "Programmatic focus" example

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/Button/Button.svelte
src/Button/ButtonSkeleton.svelte
types/Button/Button.svelte.d.ts
types/Button/ButtonSkeleton.svelte.d.ts

fix(button): forward `on:focus` event

---

docs/src/pages/_layout.svelte
docs/src/pages/framed/_reset.svelte

It seems to me that linting on master hasn’t run.

chore: linting

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
src/Slider/Slider.svelte
tests/Slider.test.svelte
types/Slider/Slider.svelte.d.ts

Fixes [#1643](https://github.com/carbon-design-system/carbon-components-svelte/issues/1643)

fix(slider): dispatch `on:input` event

---

docs/src/pages/components/Button.svx

- Adds a "Link button with icon" example
- Add a description to the "Custom element" example

docs(button): add "Link button with icon" example

---

README.md
package.json
telemetry.yml
yarn.lock

Adds config file and dependency necessary to start tracking telemetry data via [IBM Telemetry](https://github.com/ibm-telemetry/telemetry-js)
**New**
- Adds @ibm/telemetry-js dependency
- Adds [telemetry.yml](telemetry.yml) config file
- This file was generated using [IBM Telemetry automated config generator](https://github.com/ibm-telemetry/telemetry-js-config-generator/pull/1)
- Adds readme telemetry disclosure
- Include `telemetry.yml` in package.json files config 
- Adds postinstall script to use IBM telemetry command
Please look through package.json config file and ensure all necessary modifications have been made so that the "telemetry.yml" config file is included in the release version of this package.
**PLEASE NOTE:** In order for IBM Telemetry to start collecting data for this …

chore(deps): add `@ibm/telemetry-js`

---

.github/workflows/ci.yml
.github/workflows/release.yml

- [upgrade actions/cache to v4](https://github.com/carbon-design-system/carbon-components-svelte/commit/32fc991e4e5ee377839e6ed413c9d580828e926c)
- [upgrade Node to 20.x](https://github.com/carbon-design-system/carbon-components-svelte/commit/7e1143db6035aa19d5e49db6324f316902942d16)

ci: upgrade deps

---

package.json
telemetry.yml

- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope) config to `telemetry.yml`

feat: instrument with telemetry JS scope

---

COMPONENT_INDEX.md
docs/src/COMPONENT_API.json
docs/src/pages/components/ContainedList.svx
src/ContainedList/ContainedList.svelte
src/ContainedList/ContainedListItem.svelte
src/ContainedList/index.js
src/index.js
tests/ContainedList.test.svelte
types/ContainedList/ContainedList.svelte.d.ts
types/ContainedList/ContainedListItem.svelte.d.ts
types/index.d.ts

Adds a new set of components: `ContainedList` and `ContainedListItem`.

feat(contained-list): add `ContainedList`, `ContainedListItem`

---

docs/index.html
docs/src/global.css
docs/src/pages/index.svelte

chore(docs): add mandatory IBM instrumentation tags

---

docs/src/COMPONENT_API.json
package-lock.json
package.json

chore(deps-dev): upgrade `sveld` for generics support

---

package-lock.json
package.json
tsconfig.json

TypeScript 4.7 was released two years ago. This upgrades the development dependency.

chore(deps-dev): upgrade typescript 4.7.4 --> 5.6.3

---

docs/src/components/Preview.svelte

Make the preview viewer more comfortable and larger screens.

docs(style): increase preview viewer for large screens

---

docs/src/pages/components/TreeView.svx

Hope this helps. I wasn't able to preview what the markup actually looks like.

docs(tree-view): update mentions of renamed `children` prop

---

.github/workflows/checks.yml
package-lock.json
package.json
tests/App.test.svelte
tests/TreeView/TreeView.test.svelte
tests/TreeView/TreeView.test.ts
tests/index.html
tests/setup-tests.ts
tsconfig.json
vite.config.ts

Scaffold component tests using Vitest. Add an initial test case for `TreeView`.

test: scaffold component testing using Vitest

---

src/Select/Select.svelte

Fixes #2107 – applies the suggestion from https://github.com/carbon-design-system/carbon-components-svelte/issues/2107#issue-2900333913
Tested with Svelte 4 and Svelte 5.

fix(select): avoid infinite update loop in Svelte 5

---

docs/package-lock.json
docs/package.json
docs/src/components/ComponentApi.svelte
examples/rollup/package-lock.json
examples/rollup/package.json
examples/sveltekit/package-lock.json
examples/sveltekit/package.json
examples/vite/package-lock.json
examples/vite/package.json
examples/webpack/package-lock.json
examples/webpack/package.json
package-lock.json
package.json
tsconfig.json

Housekeeping PR that upgrades development dependencies, runs lint.

chore: upgrade dependencies

---

package.json

Use the actual docs site as the homepage.

chore: use docs site for homepage

---

.github/workflows/checks.yml
.github/workflows/release.yml

Switch `ubuntu-latest` for `macos-latest-xlarge`.

ci: use `macos-latest-xlarge`

---

docs/src/pages/components/Accordion.svx
docs/src/pages/components/AspectRatio.svx
docs/src/pages/components/Breadcrumb.svx
docs/src/pages/components/Breakpoint.svx
docs/src/pages/components/Button.svx
docs/src/pages/components/ButtonSet.svx
docs/src/pages/components/Checkbox.svx
docs/src/pages/components/ClickableTile.svx
docs/src/pages/components/CodeSnippet.svx
docs/src/pages/components/ComboBox.svx
docs/src/pages/components/ComposedModal.svx
docs/src/pages/components/ContentSwitcher.svx
docs/src/pages/components/ContextMenu.svx
docs/src/pages/components/CopyButton.svx
docs/src/pages/components/DataTable.svx
docs/src/pages/components/DatePicker.svx
docs/src/pages/components/Link.svx
docs/src/pages/components/Toggle.svx
docs/src/pages/components/TooltipIcon.svx
docs/src/pages/framed/DataTable/DataTableProgrammaticSorting.svelte

Initial pass at improving docs:
- Add a description of the UI component and its purpose.
- Add a basic description to each example.
- Revise existing description to be more consistent (grammar, active voice, brevity etc..)

docs: improve docs

---

tests/OverflowMenu/OverflowMenu.test.svelte
tests/OverflowMenu/OverflowMenu.test.ts

Noticed while working on #2198 
The test suite for `OverflowMenu` is light. This adds more coverage.

test(overflow-menu): add more unit tests

---

tests/Tab/Tab.test.svelte
tests/Tabs/Tabs.test.ts
tests/Tabs/TabsSkeleton.test.svelte

Add more test coverage for `Tabs`.

test(tabs): add more unit tests
