- .travis.yml
- src/components/Breadcrumb/Breadcrumb.test.js
- src/components/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap
- src/lib/__tests__/cx.spec.js
**Changes**
- Add tests for Breadcrumb using the Breadcrumb.Story.svelte component
- Add spec for `lib/cx.js`
- Update Travis CI config to run tests (w/ coverage)
> test: add initial unit tests for Breadcrumb, cx

- package.json
- src/components/CopyButton/CopyButton.Story.svelte
- src/components/CopyButton/CopyButton.stories.js
- src/components/CopyButton/CopyButton.svelte
- yarn.lock
Fixes #36
**Changes**
- Remove `createEventDispatcher`
- Remove exported `props`
- __Breaking Change__: upgrade to `carbon-components@10.9.0-rc.1`
- Clean up `CopyButton` story
> fix(copy-button): use ^10.9.0 styles for CopyButton

- README.md
- src/components/Breadcrumb/BreadcrumbItem.svelte
- src/components/DataTableSkeleton/DataTableSkeleton.svelte
- src/components/InlineLoading/InlineLoading.Story.svelte
- src/components/InlineLoading/InlineLoading.svelte
- src/components/Link/Link.Story.svelte
- src/components/Link/Link.svelte
Supports #7 
**Changes**
- Remove exported props from `Link`, `InlineLoading`, `DataTableSkeleton`
- Add `DataTableSkeleton` to supported components
> refactor: remove exported props

- README.md
- src/components/Tile/ClickableTile.svelte
- src/components/Tile/ExpandableTile.svelte
- src/components/Tile/RadioTile.svelte
- src/components/Tile/SelectableTile.svelte
- src/components/Tile/Tile.Story.svelte
- src/components/Tile/Tile.svelte
- src/components/Tile/TileAboveTheFoldContent.svelte
- src/components/Tile/TileBelowTheFoldContent.svelte
- src/components/Tile/TileGroup.svelte
Closes #34 
**Changes**
- Forward events, style prop
- Remove unneeded dispatched events
- Remove exported props
- Add Tile to list of supported components
- Make RadioTile composable as a "child" component
> feat(tile): complete RadioTile, forward events

- src/components/Accordion/AccordionItem.svelte
Fixes a bug that caused the collapsing animation class to be added and removed upon component instantiation.
The animation should be set only when clicking the `AccordionItem` component.
> fix(accordion): set animation on click

- src/components/Toggle/Toggle.Skeleton.svelte
- src/components/Toggle/Toggle.svelte
- src/components/ToggleSmall/ToggleSmall.Skeleton.svelte
- src/components/ToggleSmall/ToggleSmall.svelte
Supports #7
- Forward events
- Add style prop
- Remove exported props
- Inline change, keyup functions
- Dispatch only 'toggle' event
> refactor(toggle): forward events, inline functions

- src/components/TextInput/PasswordInput.svelte
- src/components/TextInput/TextInput.Skeleton.svelte
- src/components/TextInput/TextInput.Story.svelte
- src/components/TextInput/TextInput.svelte
Supports #7
**Changes**
- Mark passwordIsVisible as reactive
- Forward events, inline functions
- Add style prop
- Remove exported props
- Bind value for TextInput
> fix(password-input): mark passwordIsVisible as reactive

- src/components/Button/Button.Story.svelte
- src/components/Button/Button.svelte
Instead of explicitly defining hasIconOnly, its value can be inferred from a falsy icon prop and an empty slot.
> feat(button): derive hasIconOnly from icon and slots

- src/components/Button/Button.Skeleton.svelte
- src/components/Tile/ExpandableTile.svelte
**Changes**
- Prevent default keypress if key is a <Space> or 'Enter'
- Remove unused const declaration from `ButtonSkeleton`
> refactor(expandable-tile): remove onMount method

- src/components/CodeSnippet/CodeSnippet.svelte
- src/components/ComposedModal/ComposedModal.svelte
- src/components/ContentSwitcher/Switch.svelte
- src/components/Copy/Copy.svelte
- src/components/CopyButton/CopyButton.svelte
- src/components/FileUploader/FileUploader.Story.svelte
- src/components/FileUploader/FileUploader.svelte
- src/components/FileUploader/FileUploaderDropContainer.svelte
- src/components/InlineLoading/InlineLoading.svelte
- src/components/Notification/ToastNotification.svelte
- src/components/Search/Search.svelte
- src/components/Tile/ExpandableTile.svelte
- src/components/Toggle/Toggle.svelte
- src/components/ToggleSmall/ToggleSmall.svelte
**Changes**
- Use onMount, afterUpdate instead of reactive declaration blocks to avoid null checking DOM nodes
- Add autofocus prop to Search component
- clear timeout when component is destroyed in ToastNotification
> refactor: use onMount, afterUpdate methods to manage state

- .eslintrc.json
- package.json
- src/components/Breadcrumb/Breadcrumb.test.js
- src/components/Button/Button.Story.svelte
- src/components/Button/Button.stories.js
- src/components/ComposedModal/ComposedModal.svelte
- src/components/ContentSwitcher/ContentSwitcher.Story.svelte
- src/components/ContentSwitcher/ContentSwitcher.svelte
- src/components/DatePicker/DatePicker.svelte
- src/components/DatePicker/DatePickerInput.svelte
- src/components/DatePicker/flatpickr.js
- src/components/FileUploader/FileUploader.svelte
- src/components/FileUploader/FileUploaderDropContainer.svelte
- src/components/FileUploader/Filename.svelte
- src/components/Modal/Modal.svelte
- src/components/OverflowMenu/OverflowMenu.svelte
- src/components/ProgressIndicator/ProgressIndicator.stories.js
- src/components/ProgressIndicator/ProgressStep.svelte
- src/components/RadioButton/RadioButton.Story.svelte
- src/components/Select/Select.stories.js
- src/components/Slider/Slider.svelte
- src/components/StructuredList/StructuredList.stories.js
- src/components/Tile/ExpandableTile.svelte
- src/components/Tile/Tile.stories.js
- src/components/TimePicker/TimePicker.svelte
- src/lib/css.js
- yarn.lock
**Changes**
- remove `peerDependencies` field; strategy is to fold dependencies into `carbon-components-svelte`
- use eslint:recommended and apply new linting rules
- bump `carbon-icons-svelte` to 10.8.1, which includes support for forwarding the `keydown` event
> chore: apply recommended eslint rules, bump carbon-icons-svelte

- package.json
- src/components/ListBox/ListBoxMenuIcon.svelte
- src/components/ListBox/ListBoxSelection.svelte
- yarn.lock
Fixes #90 
**Changes**
- Bump `carbon-icons-svelte` to ^10.8.2
- Allow focus styles for icons in `ListBox` components
> fix(deps): upgrade carbon-icons-svelte to exclude focusring

- src/components/UIShell/UIShell.svelte
Moving global window access to onMount hook for to fix "window is undefined" error when using with sapper, etc.
> Fix window is undefined

- src/components/ComposedModal/ComposedModal.svelte
- src/components/Modal/Modal.svelte
Fix modal change focus and dispatch _open event_ after every update.
I detected the bug after using a form:
> fix(modal): focus

- src/components/Pagination/Pagination.svelte
The `Pagination` component had a naming error in the bound name for both `Select` components (One that changes the page size, the other changes the current page).
Because of this it would not display the correct values in the pager part of it due to this bug.
This PR fixes issue #178 by binding the correct variables.
> Fix pagination component

- src/components/Pagination/Pagination.svelte
Added Event Forwarding to the Pagination component by adding handlers to the Next & Previous Page buttons and the Page Size and Page select fields.
These handlers will dispatch one event containing `page` and `pageSize` details.  This was done to prevent duplicate dispatches when the `pageSize` changes, as the `page` is always set to 1 when `pageSize` is changed.
Question: Is there a better way to handle select value changes than `onBlur`? Using `onChange` results in duplicate triggers since they are binded to the `page` and `pageSize` variables.
> Added Event Forwarding To Pagination Component

- src/components/DataTable/DataTable.svelte
Also added `sortCurrentData` to control whether or not the current table data is sorted.
This features will aid in the integrating outside data sources, as you'll most likely want to make a new API call when the sorting column or direction is changed.
Issue #186
> Added the Sort Direction to the header click dispatch

- src/components/OverflowMenu/OverflowMenu.svelte
#191
**Bug description**
The Overflow Menu button is focused, even without having been opened.
**Fix**
The fix focuses the button when closing the menu. Another change introduced resets the current menu item index (`currentIndex`) to 0 after closing.
> fix(overflow-menu): focus button after initial opening

- src/components/OverflowMenu/OverflowMenu.svelte
#191
`didOpen` should only be true if the menu is opened for the first time.
> fix(overflow-menu): set didOpen after menu opened

- src/Modal/Modal.svelte
#200
**Description**
This PR fixes a bug with the `Modal` component where it is incompatible with SSR. The solution is to move the `onDestroy` logic to the function returned by `onMount`. This guarantees that the DOM can be safely interacted with.
> fix(modal): replace onDestroy with onMount for SSR support

- README.md
- package.json
- src/ComboBox/ComboBox.svelte
- src/DataTable/TableHeader.svelte
- src/Dropdown/Dropdown.svelte
- src/FileUploader/FileUploader.svelte
- src/FileUploader/FileUploaderDropContainer.svelte
- src/Grid/Column.svelte
- src/ListBox/ListBoxField.svelte
- src/ListBox/ListBoxMenuIcon.svelte
- src/ListBox/ListBoxSelection.svelte
- src/MultiSelect/MultiSelect.svelte
- src/NumberInput/NumberInput.svelte
- src/Pagination/Pagination.svelte
- types/index.d.ts
#214 
---
This is a milestone for an ongoing effort to enhance component documentation.
Recently, Svelte announced [first class TypeScript support](https://svelte.dev/blog/svelte-and-typescript). This PR provides TypeScript definitions that stub the component API (i.e. exported props).
For VSCode, two immediate goals are to:
- support automatic module imports
- provide static typing for component props
**Approach**
- annotate prop types using JSDoc notation
- use the type annotations to stub TypeScript definitions for components (primarily using the `$$prop_def` class declaration field)
**Example**
```ts
export class Button {
$$prop_def: {
kind?: "primary" | "secondary" | "tertiary" | "ghost" | "danger"; // default: "primary"
size?: "default" | "field" | "small"; // default: "default" …
```
> add TypeScript definitions

- src/ComboBox/ComboBox.Story.svelte
- src/ComboBox/ComboBox.svelte
#223 
---
**Changes**
- dispatch "select" event when selecting/changing a combo box item
- dispatch "clear" event when clearing the combo box (i.e. clicking the "x")
- also fixes a bug where the `selectedId` isn't reset when clearing the selection
**Usage**
```jsx
<ComboBox
on:select={({ detail }) => {
console.log('on:select', detail);
}}
on:clear={() => {
console.log('on:clear');
}}
{items} />
```
`on:select` detail payload:
```ts
// e.detail
{
selectedId: string;
selectedItem: { id: string; text: string; };
selectedIndex: number;
}
```
> feat(combo-box): dispatch select, clear events

- src/ComposedModal/ComposedModal.Story.svelte
- src/Modal/Modal.Story.svelte
- src/TextInput/PasswordInput.svelte
Issue #229
This PR addresses a critical bug where toggling the `PasswordInput` component inside a `Modal` would inadvertently close the modal. This also affects the `ComposedModal` component.
This hot fix stops the propagation of the click event on the "toggle password" icon.
**Changes**
- add `stopPropagation` modifier to `on:click` in `PasswordInput`
- update stories for Modal/ComposedModal to include a `PasswordInput` and `Button` inside the modals
**Test**
1) Go to [default `Modal` story](https://ibm.github.io/carbon-components-svelte/?path=/story/modal--default)
2) Click outside the modal to close it
3) Re-open it and toggle the password input (modal should not close)
4) Click on the "Programmatically toggle password" button (modal should not close)
> fix(password-input): stop propagation when toggling input type

- src/ComposedModal/ComposedModal.Story.svelte
- src/ComposedModal/ComposedModal.svelte
- src/Modal/Modal.Story.svelte
- src/Modal/Modal.svelte
- src/TextInput/PasswordInput.svelte
Issue #229 
**Changes**
- implements solution proposed by @cdellacqua that prevents clicking the inner modal from closing the modal 
- removes `stopPropagation` modifier to the PasswordInput "toggle password" button (reverts PR #230)
To test:
1) Open the default Modal/Composed Modal stories
2) Click outside the modal and verify that it closes
3) Re-open and press escape or click the "X" button; verify that it closes
4) Re-open and click the password input "toggle password" button; verify that the modal does not close
For both the Modal/Composed Modal stories, the `on:click` event logs `e.target` to the browser console. This demonstrates that the event bubbling behavior is preserved.
> fix(modal): prevent clicking inside inner modal from closing the modal

- src/Notification/InlineNotification.svelte
- src/Notification/ToastNotification.svelte
* Dispatch close event when a notification closes due to timeout
This was my main issue I found when working with `ToastNotification` and `InlineNotification`. The `timeout` works, it hides the notification, but it never dispatches a `close`-event.
Now with a `close`-event, we can attach handlers to that, and update components/sites/state according wether the notification got closed (either by a timeout or by the user).
* Fix documentation text on the timeout prop (its removing the notification after opening it, not after closing it)
This was confusing. The documentation on the `timeout`-prop read: "Set the timeout duration (ms) to hide the notification after closing it". But the implementation was "closing the notification" after a given timeout "after opening it". So I decided to fix …
> Fix InlineNotification and ToastNotification timeout

- src/ComboBox/ComboBox.svelte
- src/ListBox/ListBoxMenuIcon.svelte
- src/MultiSelect/MultiSelect.stories.js
- src/MultiSelect/MultiSelect.svelte
#251
- fix(dropdown): allow propagation when clicking the chevron icon
---
This PR fixes a bug where clicking the chevron icon in the `Dropdown` component would not toggle the menu.
The solution is to remove the `stopPropagation` modifier in the `ListBoxMenuIcon` component.
> fix(dropdown): allow clicking chevron to toggle menu

- src/Tile/ClickableTile.svelte
fixes #253 
adds `href` prop and JSDoc to `src/Tile/ClickableTile.svelte`
> fix(tile): add href prop

- src/ComboBox/ComboBox.stories.js
- src/ComboBox/ComboBox.svelte
- src/Dropdown/Dropdown.stories.js
- src/Dropdown/Dropdown.svelte
- src/MultiSelect/MultiSelect.stories.js
- src/MultiSelect/MultiSelect.svelte
- src/NumberInput/NumberInput.stories.js
- src/NumberInput/NumberInput.svelte
- src/Select/Select.stories.js
- src/Select/Select.svelte
- src/TextArea/TextArea.stories.js
- src/TextArea/TextArea.svelte
- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.stories.js
- src/TextInput/TextInput.svelte
fixes #255 
Moves helper text below form inputs per referenced commit. Also updates related stories.
**Sample**
> feat(helper-text): move helper text below form inputs

- src/Link/Link.stories.js
- src/Link/Link.svelte
fixes #258 
Adds boolean prop `visited` as defined in referenced commit with class toggles. Also updates story to include toggle
> fix(link): remove visited styles by default

- src/TimePicker/TimePicker.stories.js
- src/TimePicker/TimePickerSelect.svelte
fixes #260 
Adds `@deprecated` JSDoc syntax with message from referenced commit. Also removes `hideLabel` option from TimePickerSelect story
> fix(TimePickerSelect): deprecate hideLabel to match spec

- src/DataTableSkeleton/DataTable.stories.js
- src/DataTableSkeleton/DataTableSkeleton.svelte
Fixes #264
---
This PR aligns `DataTableSkeleton` with Carbon release version 10.13.
- fix(datatable-skeleton): add `showHeader`, `showToolbar` props
- add missing `rows`, `count` props to Story
**Breaking changes** (requires minor version bump)
- `showHeader` and `showToolbar` are `true` by default
> fix(datatable-skeleton): add showHeader, showToolbar props

- src/ComposedModal/ComposedModal.stories.js
- src/ComposedModal/ComposedModal.svelte
- src/Modal/Modal.stories.js
- src/Modal/Modal.svelte
Closes #266
---
This PR aligns `Modal`, `ComposedModal` with Carbon release version 10.20.
- feat(modal): add `preventCloseOnClickOutside` prop to prevent modal from closing when clicking outside (default is `false`)
> feat(modal): add preventCloseOnClickOutside prop

- src/OverflowMenu/OverflowMenu.svelte
Fixes #268
---
- fix(overflow-menu): focus menu button on escape key only
> fix(overflow-menu): focus menu button on escape key only

- src/Modal/Modal.stories.js
- src/Modal/Modal.svelte
fixes #272 
Adds alert dialog support for default modal as defined in referenced commit.
- adds `alert` boolean prop to component and story
- adds `modalBodyId` reactive statement
- adds `alertDialogProps` with reactive conditional assignment
```js
let alertDialogProps = {};
$: if (alert) {
if (passiveModal) {
alertDialogProps.role = "alert";
} else if (!passiveModal) {
alertDialogProps.role = "alertdialog";
alertDialogProps["aria-describedby"] = modalBodyId;
}
}
```
> feat(modal): support alertdialog aria role

- src/TextInput/TextInput.stories.js
- src/TextInput/TextInput.svelte
fixes #276 
- adds `inline` prop and appropriate classes following [Carbon React text-input](https://github.com/carbon-design-system/carbon/blob/a5e27b74c9e4659759806db0facf7455987d5f48/packages/react/src/components/TextInput/TextInput.js)
- adds necessary input outer wrapper
@metonym I noticed there are inline variants of the React password input fields but I'm not sure if it's functional there. Should we aim to include the inline variants on these other text inputs as well? Are the input fields similar enough to extract out to the `.Skeleton.svelte` file?
> feat(text-input): add inline option for TextInput

- examples/rollup-typescript/package.json
- examples/rollup-typescript/public/index.html
- examples/rollup-typescript/src/App.svelte
- examples/rollup-typescript/yarn.lock
- examples/rollup/package.json
- examples/rollup/public/index.html
- examples/rollup/rollup.config.js
- examples/rollup/src/App.svelte
- examples/rollup/yarn.lock
#283
In the rollup, rollup-typescript examples, the CSS stylesheet imported using `svelte-preprocess` isn't working. In the webpack set-up, importing the stylesheet using `css-loader` with `sideEffects` set to `true` appears to work fine.
This temporary fix adds the CSS stylesheet from the unpkg CDN.
When https://github.com/carbon-design-system/carbon/pull/6803 is released, we'll switch back to SCSS, at least for the rollup set-ups.
> fix(examples): use external stylesheet for rollup examples

- src/Slider/Slider.Story.svelte
- src/Slider/Slider.svelte
#288, #289
This PR addresses several defects in the Slider component.
**Fixes**
- mouse/touch movement should slide even if not hovering directly over the Slider UI (issue #288 )
- `value` prop should be a number, not a string (issue #289)
- dispatched "change" event should not occur when mounting
- slider should not update/dispatch events if `disabled` is set to `true`
- `value` prop is initialized as `0` instead of an empty string
> Fix slider

- src/FluidForm/FluidForm.Story.svelte
- src/FluidForm/FluidForm.stories.js
- src/FluidForm/FluidForm.svelte
- src/FluidForm/index.js
- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.Story.svelte
- src/TextInput/TextInput.stories.js
- src/TextInput/TextInput.svelte
- src/index.js
fixes #285 
- adds `FluidForm`
- adds `FormContext.svelte`
- access via `getContext("Form")`
- adds fluid variations to `TextInput` and a minor change to `PasswordInput`
There has been an issue filed with the flagship Carbon repo in regards to an unintended misalignment with the "toggle visibility" button in `PasswordInput` in a `FluidForm` https://github.com/carbon-design-system/carbon/issues/6934
> feat(text-input): adds fluid variation of text input

- src/UIShell/GlobalHeader/Header.svelte
- src/UIShell/GlobalHeader/HeaderActionLink.svelte
- src/UIShell/GlobalHeader/HeaderNavItem.svelte
- src/UIShell/GlobalHeader/HeaderNavMenu.svelte
- src/UIShell/GlobalHeader/HeaderPanelLink.svelte
- src/UIShell/HeaderGlobalAction.svelte
- src/UIShell/SideNav/HamburgerMenu.svelte
- src/UIShell/SideNav/SideNav.svelte
- src/UIShell/SideNav/SideNavLink.svelte
- src/UIShell/SideNav/SideNavMenu.svelte
- src/UIShell/SideNav/SideNavMenuItem.svelte
fixes #296 
- Adds ref to all shell components
```
/**
* Obtain a reference to the HTML button element
* @type {null | HTMLButtonElement} [ref=null]
*/
export let ref = null;
```
- bound to components via
```
bind:this={ref}
```
> feat(UIShell): export ref for all shell components

- COMPONENT_INDEX.md
- src/Link/Link.svelte
- types/index.d.ts
fixes #300
---
- feat(link): add href prop
> feat(link): add href prop

- package.json
Per an offline discussion with @metonym `yarn prepack` should be removed from the pre-commit git hook in favor of running prepack in Travis and reducing the time for committing.
> chore: remove prepack from pre-commit git hook

- README.md
`npm i` for installing a Node package; not `npm -i`
> Repair syntax

- src/Button/Button.Skeleton.svelte
- src/Button/Button.svelte
- src/Link/Link.svelte
- src/Tile/ClickableTile.svelte
- src/UIShell/GlobalHeader/HeaderActionLink.svelte
- src/UIShell/GlobalHeader/HeaderNavItem.svelte
- src/UIShell/GlobalHeader/HeaderPanelLink.svelte
- src/UIShell/SideNav/SideNavLink.svelte
fixes #320 
Adds ```rel="{$$restProps.target === '_blank' ? 'noopener noreferrer' : undefined}"``` to the following components:
- Button.Skeleton
- ClickableTile
- SideNavLink
- HeaderActionLink
- HeaderNavItem
- HeaderPanelLink
> chore(links): add rel="" to all links

- COMPONENT_INDEX.md
- docs/package.json
- docs/src/pages/components/Accordion.svx
- docs/yarn.lock
- src/Accordion/Accordion.Skeleton.svelte
- src/Accordion/Accordion.svelte
- src/Accordion/AccordionItem.svelte
- types/index.d.ts
**Features**
- feat(accordion): add disabled prop for `Accordion` and `AccordionItem` (requires `carbon-components v10.22`)
- feat(accordion): add "sm", "xl" size variants to `Accordion` and `AccordionSkeleton` (requires `carbon-components v10.22`)
**Fixes**
- fix(accordion-skeleton): forward align prop
- Accordion: add examples for "Extra-large" and "Small" size variants
- Accordion: add examples for "Disabled" and "Disabled (item)"
- AccordionSkeleton: add examples "Skeleton (chevron aligned left)" and size variants
> Accordion: add size variants, disabled prop; forward align prop to Skeleton

- COMPONENT_INDEX.md
- docs/src/pages/components/AspectRatio.svx
- src/AspectRatio/AspectRatio.svelte
- src/AspectRatio/index.js
- src/index.js
- types/index.d.ts
This component wraps the `bx--aspect-ratio` classes from `carbon-components` and is useful for constraining fluid content within an aspect ratio.
Supported aspect ratios include "2x1", "16x9", "4x3", "1x1", "3x4", "9x16" and "1x2".
**Features**
- feat(aspect-ratio): add AspectRatio component
- AspectRatio: demo all ratios
> add AspectRatio component

- docs/src/pages/components/DataTable.svx
- src/DataTable/DataTable.svelte
#14
---
This PR allows for cell values to be overridden through named slots.
Use cases:
- wrapping the cell in a link
- adding an icon
- formatting the raw value for display
**Features**
- feat(data-table): make cells slottable
> make DataTable cells slottable

- src/ComposedModal/ComposedModal.svelte
When onMount is async, the returned function is not executed: https://github.com/sveltejs/svelte/issues/4927
Because the class is not remove from the body, the code should be moved to a onDestroy function.
> fix(ComposedModal): remove bx--body--with-modal-open from body classes after destroy

- COMPONENT_INDEX.md
- docs/src/PUBLIC_API.json
- docs/src/pages/components/ProgressIndicator.svx
- src/ProgressIndicator/ProgressIndicator.svelte
- src/ProgressIndicator/ProgressStep.svelte
- types/index.d.ts
Closes #343
- refactor(progress-indicator): make currentIndex reactive, add preventChangeOnClick
- ProgressIndicator: clicking a completed step will update `currentIndex`. To opt out of this default behavior, set `preventChangeOnClick` to `true`
> refactor(progress-indicator): make currentIndex reactive, add preventChangeOnClick

- COMPONENT_INDEX.md
- docs/src/PUBLIC_API.json
- src/DataTable/DataTable.svelte
- types/index.d.ts
fixes #282
---
- feat: add display and sort methods in header object
- feat: update types and Component Index
- feat: update Public API with datatable headers methods
> feat: add DataTable display and sort methods

- docs/src/components/Preview.svelte
- docs/src/pages/components/Accordion.svx
- docs/src/pages/components/Breadcrumb.svx
- docs/src/pages/components/CodeSnippet.svx
- docs/src/pages/components/ContentSwitcher.svx
- docs/src/pages/components/InlineLoading.svx
- docs/src/pages/components/Search.svx
- docs/src/pages/framed/InlineLoading/InlineLoadingUx.svelte
Use more realistic copy for ContentSwitcher, Accordion instead of "Item 1, 2...."
- ContentSwitcher: add "Selected index" example
- CodeSnippet: add multi-line skeleton example
- InlineLoading: add UX example showcasing various statuses
> Improve docs

- COMPONENT_INDEX.md
- docs/src/PUBLIC_API.json
- docs/src/components/ComponentApi.svelte
- docs/src/pages/components/DataTable.svx
- docs/src/pages/framed/DataTable/DataTableBatchSelection.svelte
- docs/src/pages/framed/DataTable/DataTableBatchSelectionToolbar.svelte
- docs/src/pages/framed/DataTable/RadioSelectableDataTable.svelte
- docs/src/pages/framed/DataTable/SelectableDataTable.svelte
- scripts/rollup/generate-index.js
- src/Checkbox/InlineCheckbox.svelte
- src/Checkbox/index.js
- src/DataTable/DataTable.svelte
- src/DataTable/TableRow.svelte
- src/DataTable/Toolbar.svelte
- src/DataTable/ToolbarBatchActions.svelte
- src/DataTable/ToolbarContent.svelte
- src/DataTable/ToolbarSearch.svelte
- src/DataTable/index.js
- src/Search/Search.svelte
- src/index.js
- types/index.d.ts
#14
---
**Features**
- DataTable: add Toolbar, ToolbarContent, ToolbarSearch, ToolbarBatchActions
- DataTable: support row selection, radio selection, batch selection
- DataTable: dispatch row mouseenter, mouseleave events
- Search: forward focus, blur events
- fix(docgen): list both default and named slots in `COMPONENT_INDEX.md`
> DataTable: add toolbar, toolbar search

- src/DataTable/DataTable.svelte
fixes #355
---
- fix(datatable): fix sort parameters
> fix(datatable): fix sort parameters

- src/ComboBox/ComboBox.svelte
- src/ListBox/ListBoxMenu.svelte
This prepares the ComboBox for a "infinite" loading scenario: we watch the scroll position of the list, so when the user scrolls and reaches the end of the list then we can append some new items to the list.
> Forward scroll event for ComboBox and add a reference to the list HTML element

- COMPONENT_INDEX.md
- docs/src/PUBLIC_API.json
- docs/src/pages/components/DataTable.svx
- docs/src/pages/framed/DataTable/DataTableBatchSelectionToolbar.svelte
- src/Checkbox/InlineCheckbox.svelte
- src/ComboBox/ComboBox.svelte
- src/DataTable/DataTable.svelte
- src/DataTable/Toolbar.svelte
- src/DataTable/ToolbarBatchActions.svelte
- src/DataTable/ToolbarMenu.svelte
- src/DataTable/ToolbarMenuItem.svelte
- src/DataTable/index.js
- src/OverflowMenu/OverflowMenu.svelte
- src/index.js
- types/index.d.ts
#14
---
**Features**
- DataTable: add `ToolbarMenu`, `ToolbarMenuItem`
**Fixes**
- DataTable: cancelling batch selection should unselect "select all rows" checkbox
- Toolbar: remove duplicate "bx--toolbar-content" element
> DataTable: add ToolbarMenu, ToolbarMenuItem, fix batch actions selection cancellation

- COMPONENT_INDEX.md
- docs/src/PUBLIC_API.json
- docs/src/pages/components/Dropdown.svx
- docs/src/pages/components/MultiSelect.svx
- src/MultiSelect/MultiSelect.svelte
**Features**
- MultiSelect: forward "clear" event
- MultiSelect: dispatch "select" event to be consistent with ComboBox, Dropdown (#378 , #344 )
Signature for "select" event:
```ts
// on:select
interface Detail {
selectedIds: string[];
selected: Item[];
unselected: Item[];
}
```
- Document `itemToString` prop for Dropdown, MultiSelect
- MultiSelect: add example for "Initial selected items"
> MultiSelect: forward "clear" event, dispatch "select" event

- docs/src/pages/components/CodeSnippet.svx
- docs/src/pages/framed/CodeSnippet/DynamicCodeSnippet.svelte
- docs/src/pages/framed/CodeSnippet/HiddenCodeSnippet.svelte
- src/CodeSnippet/CodeSnippet.svelte
**Fixes**
- CodeSnippet: `showMoreLess` should be re-computed if `code` is dynamically updated
- CodeSnippet: add example for dynamically updating `code`
- CodeSnippet: add example for "Hidden code snippet" edge case (#373)
> CodeSnippet: showMoreLess should update if code is dynamically updated

- src/ComposedModal/ComposedModal.svelte
Useful if you want to handle the focusing yourself or do not want the modal to auto focus on anything at all after mounting.
If you don't pass the prop `selectorPrimaryFocus`, everything works as before, the modal will focus on the primary button (`buttonRef`) after mounting.
If you pass a string value to the `selectorPrimaryFocus`, the modal will focus on the value using `querySelector` after mounting.
If you now pass `selectorPrimaryFocus={null}`, the modal will not focus on anything after mounting.
> feat(ComposedModal): allow using null for selectorPrimaryFocus to disable auto focus

- docs/src/pages/components/UIShell.svx
- docs/src/pages/framed/UIShell/HeaderNav.svelte
- docs/src/pages/framed/UIShell/PersistedHamburgerMenu.svelte
- src/UIShell/GlobalHeader/Header.svelte
- src/UIShell/SideNav/SideNav.svelte
- adds `persistentHamburgerMenu` prop to Header component
- fixes collapse logic in SideNav
- overrides `isSideNavOpen` logic when persisting hamburger menu
ref #374
> feat(UIShell): add persistentHamburgerMenu prop to Header

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/CodeSnippet.svx
- docs/src/pages/components/CopyButton.svx
- docs/src/pages/components/Toggle.svx
- docs/src/pages/components/ToggleSmall.svx
- src/Toggle/Toggle.svelte
- src/Toggle/ToggleSkeleton.svelte
- src/ToggleSmall/ToggleSmall.svelte
- src/ToggleSmall/ToggleSmallSkeleton.svelte
- types/Toggle/Toggle.d.ts
- types/Toggle/ToggleSkeleton.d.ts
This PR addresses a suggestion from @ispyinternet to fold `ToggleSmall` into `Toggle` because the components are virtually identical. This has also been raised upstream in https://github.com/carbon-design-system/carbon/issues/6653
**Changes**
- add "size" prop to `Toggle` and `ToggleSkeleton`; default value is "default" while "sm" uses the small variant
- add deprecation notices to `ToggleSmall` and `ToggleSmallSkeleton`
None.
However, the `ToggleSmall` and `ToggleSmallSkeleton` will be removed in the next major version.
> feat(toggle): support small size, deprecate ToggleSmall

- src/Button/Button.svelte
The `#if icon` conditional is redundant because svelte:component will not render if `this={icon}` is falsy.
> refactor(button): remove redundant if statement

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/ProgressIndicator.svx
- docs/src/pages/framed/ProgressIndicator/ProgrammaticProgressIndicator.svelte
- src/ProgressIndicator/ProgressIndicator.svelte
- src/ProgressIndicator/ProgressStep.svelte
- types/ProgressIndicator/ProgressIndicator.d.ts
Issue #399 
**Changes**
- ProgressIndicator: fix reactivity for `currentIndex`; the value should update if the user clicks a completed step or if `currentIndex` is updated programmatically
- ProgressStep: if `complete` or `disabled` are updated, the existing step tracked by `ProgressIndicator` should be updated
**Notes**
Currently, programmatically updating the `currentIndex` will not check whether a step is completed or not. I feel that this decision should be left to the developer.
**Todo**
In the [following example](https://carbon-components-svelte-git-fix-progress-indicator.carbon-svelte.vercel.app/framed/ProgressIndicator/ProgrammaticProgressIndicator), `currentIndex` is updated if:
- the user clicks a completed step
- the user toggles the completion for Step 3 (index 2) or Step 1 …
> fix(progress-indicator): allow currentIndex to be programmatically updated

- src/RadioButtonGroup/RadioButtonGroup.svelte
> fix(RadioButtonGroup): make selected prop reactive

- src/RadioButtonGroup/RadioButtonGroup.svelte
After the previous modifications per #407, the change event would not be dispatched when selecting a radio button. This fixes it.
There is however a slight annoyance: the change event is triggered once after the component is created. This also happened before the previous modifications #407. I tried to fix it in a few ways (for example moving the newly added `subscribe` in the `onMount` function) but to no avail :(
> fix(RadioButtonGroup): trigger change event

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- package.json
- src/DataTable/DataTable.svelte
- src/RadioButtonGroup/RadioButtonGroup.svelte
- tests/ComboBox.test.svelte
- types/ComboBox/ComboBox.d.ts
- types/DataTable/DataTable.d.ts
- types/Dropdown/Dropdown.d.ts
- types/FileUploader/FileUploader.d.ts
- types/FileUploader/FileUploaderButton.d.ts
- types/FileUploader/FileUploaderDropContainer.d.ts
- types/Grid/Column.d.ts
- types/ListBox/ListBoxField.d.ts
- types/ListBox/ListBoxMenuIcon.d.ts
- types/ListBox/ListBoxSelection.d.ts
- types/MultiSelect/MultiSelect.d.ts
- types/NumberInput/NumberInput.d.ts
- yarn.lock
#409 
**Changes**
- Export component types/interfaces
Usage
```svelte
<script lang="ts">
import { ComboBox } from "carbon-components-svelte";
import type { ComboBoxItem } from "carbon-components-svelte/ComboBox/ComboBox";
const items: ComboBoxItem[] = [
{ id: "1", text: "Email" },
];
</script>
```
> fix(types): export component types

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/DataTable.svx
- src/DataTable/DataTable.svelte
- src/DataTableSkeleton/DataTableSkeleton.svelte
- tests/DataTable.test.svelte
- types/DataTable/DataTable.d.ts
- types/DataTableSkeleton/DataTableSkeleton.d.ts
**Features**
- Expand `headers` prop type in DataTableSkeleton to be consistent with that of the DataTable (issue #413)
This enables you to share `headers` between the DataTable and DataTableSkeleton components:
```svelte
{#if loading}
<DataTableSkeleton {headers} />
{:else}
<DataTable {headers} {rows} />
{/if}
```
**Fixes**
- Update `DataTableRow` prop type in DataTable to require an "id" key and value (issue #414)
- Add example "Skeleton with object headers" to DataTable docs
- Document that the DataTable is keyed ("key" for `headers`, "id" for `rows)
> expand headers type in DataTableSkeleton, fix DataTableRow type to require "id"

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/UIShell.svx
- docs/src/pages/framed/UIShell/HeaderSearch.svelte
- src/UIShell/GlobalHeader/HeaderActionSearch.svelte
- src/UIShell/HeaderSearch.svelte
- src/UIShell/index.js
- src/index.js
- tests/HeaderSearch.svelte
- types/UIShell/HeaderSearch.d.ts
- types/index.d.ts
#395 
**Changes**
- add a highly reactive HeaderSearch component that can render user-provided results
- deprecate HeaderActionSearch in favor of HeaderSearch
Sample usage:
```svelte
<script>
let ref = null;
let active = false;
let value = "";
let selectedResultIndex = 1;
$: results =
value.length > 2
? [
{
href: "/",
text: "Result 1",
description: "Result description",
},
{
href: "/",
text: "Result 2",
description: "Result description",
},
{
href: "/",
text: "Result 3",
description: "Result description",
},
]
: [];
$: console.log("ref", ref);
$: console.log("active", active);
$: console.log("value", value);
$: console.log("selectedResultIndex", selectedResultIndex);
</script>
<HeaderSearch
bind:ref
bind:active
bind:value
bind:selectedResultIndex
results="{results}"
on:clear …
```
> Refactor UI Shell global search component

- src/UIShell/HeaderSearch.svelte
Fixes #431 
---
**Fixes**
- prevent cursor in search input from jumping by preventing the default behavior for "ArrowUp" and "ArrowDown" keys
> prevent default behavior for Arrow{Up|Down} in HeaderSearch

- src/DataTableSkeleton/DataTableSkeleton.svelte
move restprops from `<table>` to table container `div` to align with DataTable usage
> Move rest props in DataTableSkeleton

- src/ComboBox/ComboBox.svelte
- src/Dropdown/Dropdown.svelte
**Changes**
- fix: selecting a different combobox should focus the correct input
- fix: selecting a different dropdown should focus the correct button
- fix: refocus combobox input unless the related event target has a "searchbox" role (fixes #436)
> Fix dropdown combobox focus

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Search/Search.svelte
- types/Search/Search.d.ts
Refs: https://github.com/carbon-design-system/carbon/pull/7230
**Changes**
- clear search input if the "Escape" key is pressed
- forward the `keydown` event to the input element
> feat(search): clear input on escape key

- docs/src/pages/components/Tooltip.svx
- docs/src/pages/framed/Tooltip/TooltipReactive.svelte
- src/Tooltip/Tooltip.svelte
Issue #398
Refs: https://github.com/IBM/carbon-components-svelte/pull/446
This fixes a [defect in the tooltip](https://github.com/IBM/carbon-components-svelte/pull/446#issuecomment-739465459) using the "align" prop.
**Changes**
- close tooltip on mousedown event
- remove blur event from tooltip; stop click, mouse propagation on tooltip content
- remove tabindex from open tooltip to prevent outline ring
- refocus trigger icon or trigger text when closing
- remove useless programmatic variable
- add reactive example
- add hidden icon example
> Close tooltip on mousedown event, add reactive, hidden icon examples

- src/Select/SelectItem.svelte
Fixes #451 
Reverts https://github.com/IBM/carbon-components-svelte/pull/449/commits/90bd2a10b7c00c3eb29d205d1945ed80db5975b5#diff-12cef3c45879191131821aeebbb60be97d60888f43daf6dce4a419537538945d
> fix(select-item): revert spreading rest props

- src/OverflowMenu/OverflowMenu.svelte
This PR contains a fix for issue #476 
The current implementation prevents the focus to be set when it is opened for the first time. The code in this PR prevents the focus to be set during the initial after update lifecycle method call. The initial lifecycle call is called after the component is mounted.
> Overflow menu first time open behavior is not correct

- docs/vite.config.js
- docs/yarn.lock
- package.json
- src/DatePicker/createCalendar.js
- yarn.lock
Closes #249
By upgrading `flatpickr` to a version that supports ESM, users no longer need to include "flatpickr" as an optimizable dependency when using this library with ESM development approaches like vite.
- upgrade `flatpickr` dependency from 4.6.3 to 4.6.9
- update flatpickr `rangePlugin` import to use ESM entry
> feat: upgrade flatpickr and use ESM entry

- src/DataTable/ToolbarSearch.svelte
- src/Slider/Slider.svelte
- src/UIShell/GlobalHeader/HeaderNav.svelte
Non-style related fixes from the upstream Carbon library.
**Fixes**
- remove "aria-hidden" prop from ToolbarSearch
- remove "menubar" role from HeaderNav; deprecate ariaLabel in favor of native attributes "aria-label" and "aria-labelledby"
- add label id to Slider
> Minor fixes to align with v10.26

- src/ComposedModal/ComposedModal.svelte
- src/Modal/Modal.svelte
An extraneous focus ring for the Modal component is caused by `tabindex="-1"` being set on the incorrect element.
**Fixes**
- move `tabindex="-1"` to the body elemennt in Modal
- remove `tabindex="-1"` from ComposedModal (ModalBody already sets `tabindex`)
> fix(modal): remove extraneous focus ring

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/_layout.svelte
- src/Notification/NotificationButton.svelte
- src/UIShell/GlobalHeader/HeaderAction.svelte
- src/UIShell/GlobalHeader/HeaderActionLink.svelte
- src/UIShell/SideNav/SideNavLink.svelte
- src/UIShell/SideNav/SideNavMenu.svelte
- types/Notification/NotificationButton.d.ts
- types/UIShell/GlobalHeader/HeaderAction.d.ts
- types/UIShell/GlobalHeader/HeaderActionLink.d.ts
- types/UIShell/SideNav/SideNavLink.d.ts
- types/UIShell/SideNav/SideNavMenu.d.ts
Closes #463
This PR addresses an inconsistency in prop names/types for rendering an icon.
The following each expect a Carbon icon:
- `renderIcon`
- `render` (Icon)
- `icon.render`
- `renderIcon` renamed to `icon` in NotificationButton
- `icon` prop type changed to "typeof import("carbon-icons-svelte").CarbonIcon" in HeaderAction, HeaderActionLink, SideNavLink, SideNavMenu
> make renderIcon/icon prop consistent

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Link.svx
- src/Link/OutboundLink.svelte
- src/Link/index.js
- src/index.js
- types/Link/OutboundLink.d.ts
- types/index.d.ts
`OutboundLink` wraps `Link` with the following differences:
- target="_blank" is automatically set
- the Launch16 icon is used
```svelte
<OutboundLink href="https://www.carbondesignsystem.com/">Carbon Design System</OutboundLink>
```
> add OutboundLink

- docs/src/components/ComponentApi.svelte
The path to the source is missing a slash.
Before:
`https://github.com/IBM/carbon-components-svelte/tree/mastersrc/Grid/Grid.svelte`
After:
`https://github.com/IBM/carbon-components-svelte/tree/master/src/Grid/Grid.svelte`
`-----------------------------------------------------------^`
> Fix path to source

- css/all.scss
- css/g10.scss
- css/g100.scss
- css/g90.scss
- css/white.scss
- docs/src/App.svelte
This is a hot fix needed to correctly render the text color for low contrast notifications.
> fix(scss): use new component tokens to render low contrast notifications

- src/ComboBox/ComboBox.svelte
- src/MultiSelect/MultiSelect.svelte
When blurring (e.g., clicking away from) a ComboBox or MultiSelect, the list box should *not* be re-focused if the related target is an input/select/textarea element.
> hotfix: blur ComboBox, MultiSelect focus based on relatedTarget tag name

- src/Button/Button.svelte
Icons in the "Button w/ icon" variant incorrectly renders in Safari 13.
The fix is to remove the blank space between the slot and icon.
> fix(button): remove blank line to correctly render button with icon in Safari 13

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/FluidForm/FluidForm.svelte
- types/FluidForm/FluidForm.d.ts
- types/Form/Form.d.ts
**Fixes**
- forward missing events in `FluidForm`
> fix(fluid-form): forward missing events

- src/NumberInput/NumberInput.svelte
NumberInput does not set `name` property correctly on the non-mobile variant.
> NumberInput: forward name to non-mobile variant

- docs/src/App.svelte
Refs: https://github.com/carbon-design-system/carbon/issues/8286
In `carbon-components` v10.32, input styles have a default value of $field-02. This is a hotfix that patches the documentation site styles to reset the value to $field-01.
I will patch the release as well.
> hotfix: reset input background color to use $field-01

- src/DataTable/DataTable.svelte
- src/UIShell/SideNav/HamburgerMenu.svelte
Using `HamburgerMenu` from a SvelteKit project would result in the following error:
```
4:01:51 PM [vite] Error when evaluating SSR module /node_modules/carbon-components-svelte/src/UIShell/SideNav/HamburgerMenu.svelte:
/home/vegard/beat/backoffice-sapper/node_modules/carbon-icons-svelte/lib/Close20/index.js:1
import Close20 from "./Close20.svelte";
^^^^^^
SyntaxError: Cannot use import statement outside a module
at wrapSafe (internal/modules/cjs/loader.js:1101:16)
at Module._compile (internal/modules/cjs/loader.js:1149:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
at Module.load (internal/modules/cjs/loader.js:1034:32)
at Function.Module._load (internal/modules/cjs/loader.js:923:14)
at Module.require (internal/modules/cjs/loader.js:1074:19)
at require …
```
> Fix "Cannot use import statement outside a module"

- src/Dropdown/Dropdown.svelte
Fixes can't open a dropdown with keyboard #607 
I didn't use the preventDefault modifier because it would also prevent the default of the tab. Which interferes with the tab navigation. 
While on this I found another inconsistency with other implementations. The selected options of a dropdown can be switch by arrow down and arrow up when the dropdown isn't opened. Other implementations like the vue and react version would open the Dropdown and switch highlighted options. Should I open another PR for it? Or I can just do it here.
> fix dropdown keyboard usage

- src/Dropdown/Dropdown.svelte
Hi guys!
Using the dropdown we found a visual bug. 
When we change the selectedIndex value from an external action like clicking a button, we can see the previously selected item active when we open the dropdown.
Here's a Minimal, Reproducible Example: [https://svelte.dev/repl/159395c52c3140f996616b57d74861f4?version=3.37.0](https://svelte.dev/repl/159395c52c3140f996616b57d74861f4?version=3.37.0)
Just wait for it to compile then:
Click the dropdown.
Click the third item.
Click the button that changes the selectedIndex.
Click the dropdown.
You will see the 2nd AND 3rd item active!
You should only see the 2nd 😅
This PR updates the internal selectedId variable when a valid selectedIndex is passed, otherwise, it sets it to undefined (its initialization value).
> fix(Dropdown): update selectedId when selectedIndex changes.

- docs/package.json
- docs/src/App.svelte
- docs/yarn.lock
- package.json
- yarn.lock
In the previous minor version 10.32.0, there was a styling issue that impacted a number components. This fix patches carbon-components to version 10.32.1.
> chore(deps-dev): patch carbon-components@10.32.1

- CHANGELOG.md
- COMPONENT_INDEX.md
- docs/package.json
- docs/src/App.svelte
- docs/src/pages/components/DataTable.svx
- docs/yarn.lock
- package.json
- preprocess/api.json
- src/DataTable/DataTable.svelte
- src/Dropdown/Dropdown.svelte
- yarn.lock
I took the liberty to provide a way to access nested objects by a string path.
I also changed the way undefined items are handled : instead of showing up as "undefined" in the DataTable, the cells will simply be empty, which makes it so that it does not crash with the default sorting behaviour.
> Add support for nested object fields in DataTable

- src/DataTable/DataTable.svelte
Small fix to correct the width of the `expanded-row` slot when a DataTable is both expandable and selectable.
The `colspan` of TableCell that wraps the `expanded-row` slot is now set to `header.length + 2` instead of `header.length + 1` to accommodate the additional selectable column.
> Fix TableCell "colspan" when a DataTable is Expandable and Selectable

- docs/src/COMPONENT_API.json
- src/DataTable/ToolbarSearch.svelte
- types/DataTable/ToolbarSearch.d.ts
Fixes #646
ToolbarSearchProps are missing type definitions for $$restProops. With this PR `svelte-check` no longer complains and editors can show propose code completions. E.g. VS Code:
*Limitations*
This is just a very specific case. The proper definition of `$$restProps` in other components is subject to further work.
As an alternative to `svelte.JSX.HTMLAttributes` I would like to suggest [`Partial`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) in a separate PR.
> Add html input attributes to ToolbarSearchProps

- docs/src/layouts/ComponentLayout.svelte
This adds "g80" to the array of valid themes.
This allows you to set the theme for a documentation page through the URL.
Example:
https://carbon-svelte.vercel.app/components/InlineNotification?theme=g80#low-contrast
> docs: add g80 to valid themes

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/DataTable.svx
- src/ComposedModal/ComposedModal.svelte
- src/DataTable/DataTable.svelte
- src/Modal/Modal.svelte
- tests/ComposedModal.test.svelte
- tests/DataTable.test.svelte
- tests/Modal.test.svelte
- types/ComposedModal/ComposedModal.d.ts
- types/DataTable/DataTable.d.ts
- types/Modal/Modal.d.ts
**Features**
- dispatch "click:button--primary" as an alias to "submit" in `Modal`, `ComposedModal`
**Fixes**
- export `useStaticWidth` prop in `DataTable`
- do not render `DataTable` table header if title/description not provided
- add DataTable example "Static width"
- add clear reminder in DataTable that `headers` must have a unique "key" property and `rows` should have a unique "id" property
> Various features/fixes

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/ProgressBar.svx
- docs/src/pages/framed/ProgressBar/ProgressBarUx.svelte
- src/ProgressBar/ProgressBar.svelte
- types/ProgressBar/ProgressBar.d.ts
Fixes #731 
**Fixes**
- export id prop in ProgressBar
- add ProgressBar "UX example"
> Export id in ProgressBar, add UX animated progress bar example

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/components/ComponentApi.svelte
- docs/src/components/InlineSnippet.svelte
- docs/src/pages/_layout.svelte
- docs/src/pages/components/Breakpoint.svx
- docs/src/pages/framed/Breakpoint/Breakpoint.svelte
- docs/svelte.config.js
- src/Breakpoint/Breakpoint.svelte
- src/Breakpoint/index.js
- src/index.js
- tests/Breakpoint.test.svelte
- types/Breakpoint/Breakpoint.d.ts
- types/index.d.ts
**Features**
- add `Breakpoint` component
---
The [Carbon Design System grid implementation](https://carbondesignsystem.com/guidelines/2x-grid/implementation#responsive-options) defines five responsive breakpoints:
- Small (`sm`): less than 672px
- Medium (`md`): 672 - 1056px
- Large (`lg`): 1056 - 1312px
- X-Large (`xlg`): 1312 - 1584px
- Max (`max`): greater than 1584px
This utility component uses the [Window.matchMedia API](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) to declaratively determine the current Carbon breakpoint size.
```svelte
<script>
import { Breakpoint } from "carbon-components-svelte";
let size;
let events = [];
</script>
<Breakpoint bind:size on:match="{(e) => (events = [...events, e.detail])}" />
<h1>{size}</h1>
<pre> …
```
> Breakpoint

- src/DataTable/DataTableSkeleton.svelte
Fixes #734
**Fixes**
- add skeleton text for every row and column in `DataTableSkeleton`
> fix(data-table-skeleton): every row should animate text #734

- docs/index.html
- docs/src/components/ComponentApi.svelte
- docs/src/pages/_layout.svelte
- docs/src/pages/components/CodeSnippet.svx
- docs/src/pages/components/CopyButton.svx
- docs/src/pages/components/RecursiveList.svx
- docs/src/pages/index.svelte
- docs/src/store.js
- fix typo in `CodeSnippet`, `CopyButton` pages; "noop" should be spelled "no-op"
- add `carbon-preprocess-svelte` to Carbon Svelte portfolio
---
Todo:
- unpkg
- pre-compiled CSS
- SCSS
> Improve documentation

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/DatePicker.svx
- docs/src/pages/framed/DatePicker/DatePickerRange.svelte
- docs/src/pages/framed/DatePicker/DatePickerSingle.svelte
- docs/vite.config.js
- src/DatePicker/DatePicker.svelte
- src/DatePicker/DatePickerInput.svelte
- src/DatePicker/createCalendar.js
- tests/DatePicker.test.svelte
- types/DatePicker/DatePicker.d.ts
This PR address some long standing issues with the `DatePicker` component.
Fixes #573 , fixes #345 , fixes #522
---
- remove `appendTo` prop in `DatePicker` as it is no longer needed; this also makes the `DatePicker` component compatible in server-side rendering (SSR) environments (#522)
**Fixes**
- append calendar to the date picker element instead of `document.body` to prevent locking of the arrow keys in other input elements (suggested fix by @timeshift92), (#345, #573)
- fix `rangePlugin` import in `DatePicker` to fix "Unexpected token export" error
> DatePicker rework

- COMPONENT_INDEX.md
- docs/package.json
- docs/src/COMPONENT_API.json
- docs/src/pages/components/LocalStorage.svx
- docs/src/pages/components/NumberInput.svx
- docs/src/pages/framed/LocalStorage/LocalStorageClear.svelte
- docs/yarn.lock
- package.json
- src/DataTable/Table.svelte
- src/FormGroup/FormGroup.svelte
- src/LocalStorage/LocalStorage.svelte
- src/MultiSelect/MultiSelect.svelte
- src/NumberInput/NumberInput.svelte
- types/FormGroup/FormGroup.d.ts
- types/LocalStorage/LocalStorage.d.ts
- types/MultiSelect/MultiSelect.d.ts
- yarn.lock
**Features**
- support `NumberInput` readonly variant 
- export multiSelectRef, fieldRef, selectionRef props in `MultiSelect`
- add clearItem, clearAll instance methods to `LocalStorage`
**Fixes**
- add legendId to `FormGroup`
- deprecate `Table` shouldShowBorder prop
- add LocalStorage example "Clear item, clear all"
- upgrade `carbon-components` to v10.39.0
> Align v10.39

- docs/src/COMPONENT_API.json
- package.json
- tests/Breakpoint.test.svelte
- tests/CodeSnippet.test.svelte
- tests/CopyButton.test.svelte
- tests/LocalStorage.test.svelte
- tests/Modal.test.svelte
- types/LocalStorage/LocalStorage.d.ts
- yarn.lock
**Fixes**
- upgrade `sveld` to v0.8.1 to type functional declarations as accessors, not props
For example, `LocalStorage` exports `clearItem` and `clearAll`, which should be accessible on the component instance.
```svelte
<script lang="ts">
import { LocalStorage } from "carbon-components-svelte";
let storage: LocalStorage;
let toggled = false;
$: if (storage) storage.clearItem();
$: if (storage) storage.clearAll();
</script>
<LocalStorage
bind:this="{storage}"
bind:value="{toggled}"
/>
```
> Fix TypeScript definitions; function declarations should be typed as accessors, not props

- package.json
- types/Breakpoint/Breakpoint.d.ts
- types/FileUploader/FileUploader.d.ts
- types/ImageLoader/ImageLoader.d.ts
- types/ListBox/ListBoxField.d.ts
- types/ListBox/ListBoxMenuIcon.d.ts
- types/ListBox/ListBoxSelection.d.ts
- types/LocalStorage/LocalStorage.d.ts
- types/NumberInput/NumberInput.d.ts
- yarn.lock
**Fixes**
- type constant props in TypeScript definitions as accessors in the `SvelteComponentTyped` interface
Example:
```diff
/// <reference types="svelte" />
import { SvelteComponentTyped } from "svelte";
export type BreakpointSize = "sm" | "md" | "lg" | "xlg" | "max";
export type BreakpointValue = 320 | 672 | 1056 | 1312 | 1584;
export interface BreakpointProps {
/**
* Determine the current Carbon grid breakpoint size
*/
size?: BreakpointSize;
/**
* Carbon grid sizes as an object
* @default { sm: false, md: false, lg: false, xlg: false, max: false, }
*/
sizes?: Record<BreakpointSize, boolean>;
-  /**
-   * Reference the Carbon grid breakpoints
-   * @constant
-   * @default { sm: 320, md: 672, lg: 1056, xlg: 1312, max: 1584, }
-   */
-  breakpoints: Record<BreakpointSize, …
```
> fix(types): upgrade sveld and type constant props as accessors

- src/TreeView/TreeView.svelte
Fixes #747
The first, non-disabled tree node should be tab focusable (`tabindex="0"`) if no active id is provided.
- `TreeView` should be tab focusable if no active id is provided
> fix(tree-view): TreeView should be tab focusable if no active id is provided

- src/DataTable/DataTable.svelte
Zero cell value should be as-is.
Only fallback on `undefined` property.
Link to issue:
- https://github.com/IBM/carbon-components-svelte/issues/666
> fix(DataTable): undefined cell value fallback

- src/ComboBox/ComboBox.svelte
- src/DatePicker/DatePicker.svelte
- src/MultiSelect/MultiSelect.svelte
- src/OverflowMenu/OverflowMenu.svelte
- src/Slider/Slider.svelte
- src/Tooltip/Tooltip.svelte
- src/TooltipDefinition/TooltipDefinition.svelte
- src/TooltipIcon/TooltipIcon.svelte
Replace all occurrences of `svelte:body` with `svelte:window` to resolve the issue described in #315.
All occurrences listed in [this comment](https://github.com/IBM/carbon-components-svelte/issues/315#issuecomment-705669503) were replaced, except for `Dropdown/Dropdown.svelte`, as it was already replaced.
> fix: close overlays on window click

- COMPONENT_INDEX.md
- css/all.scss
- css/g10.scss
- css/g100.scss
- css/g80.scss
- css/g90.scss
- css/white.scss
- docs/package.json
- docs/src/COMPONENT_API.json
- docs/src/pages/components/DatePicker.svx
- docs/src/pages/components/TreeView.svx
- docs/src/pages/index.svelte
- docs/yarn.lock
- package.json
- src/DatePicker/DatePickerInput.svelte
- tests/DatePicker.test.svelte
- types/DatePicker/DatePickerInput.d.ts
- yarn.lock
**Features**
- add `helperText` prop to `DatePickerInput`
- fix typos in styling instructions
- update expanded nodes guidance
**Refactor**
- omit explicit `treeview.scss` import in `css/*.scss` files as it is included by default in `carbon-components@10.14`
- upgrade `carbon-components` to v10.40.0
> Align 10.40

- src/FormGroup/FormGroup.svelte
We shouldn't add a `<legend>` If the the legend text specified.
> Set a condition for showing legend in FormGroup

- src/ComboBox/ComboBox.svelte
Fixes #817
- prevent redundant `clear` events in `ComboBox`
> fix(combo-box): remove redundant clear events #817

- docs/src/COMPONENT_API.json
- src/Tile/ClickableTile.svelte
- tests/ClickableTile.test.svelte
- types/Tile/ClickableTile.d.ts
**Fixes**
- `ClickableTile` TypeScript definition restProps should extend attributes of either `a` or `p` tags
> fix(clickable-tile): explicitly type restProps

- src/OverflowMenu/OverflowMenu.svelte
Thanks.
I think that the `menuOptionsClass` prop (in OverflowMenu component) is not work correctly.
```svelte
<OverflowMenu menuOptionsClass="foo-class" open>
<OverflowMenuItem text="foo" />
<OverflowMenuItem text="bar" />
</OverflowMenu>
```
> fix: menuOptionsClass in OverflowMenu

- src/DataTable/DataTable.svelte
Fixes #889
Currently, the `click:row--expand` event will be dispatched along with `click:row` when clicking the chevron button in an expandable row. The solution is to stop the event from propagating from the cell to the parent row.
In the example below, both "click:row". and "click:row--expand" can be triggered together. The expected behavior is that only "click:row--expand" should fire when toggling the chevron.
```svelte
<DataTable
on:click:row={() => {
console.log("click:row");
}}
on:click:row--expand={() => {
console.log("click:row--expand");
}}
/>
```
> fix(data-table): avoid triggering click:row when clicking expandable row chevron

- src/Tooltip/Tooltip.svelte
Proposal to fix https://github.com/carbon-design-system/carbon-components-svelte/issues/872
> fix(ToolTip): better toggling logic

- src/TextInput/TextInput.svelte
Fixes #898
Even though there is a dedicated `NumberInput` component, the `TextInput` should have a numerical value if `type` is explicitly set to `"number"`.
```svelte
<script>
import { TextInput } from "carbon-components-svelte";
let value;
$: console.log(value, typeof value);
</script>
<TextInput type="number" bind:value />
```
> fix(text-input): coerce TextInput value to number if type is numerical

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Tabs.svx
- src/Tabs/Tab.svelte
- src/Tabs/Tabs.svelte
- types/Tabs/Tabs.svelte.d.ts
Closes #899
By default, the width of each tab is set to `10rem`.
Set `autoWidth` to `true` for tabs to have an automatically set width.
```svelte
<Tabs autoWidth>
<Tab label="Tab label 1" />
<Tab label="Tab label 2" />
<Tab label="Tab label 3" />
<div slot="content">
<TabContent>Content 1</TabContent>
<TabContent>Content 2</TabContent>
<TabContent>Content 3</TabContent>
</div>
</Tabs>
```
> Add autoWidth prop to `Tabs`

- src/ComboBox/ComboBox.svelte
- src/ContextMenu/ContextMenuOption.svelte
- src/DataTable/TableHeader.svelte
- src/DatePicker/DatePickerInput.svelte
- src/Dropdown/Dropdown.svelte
- src/FileUploader/Filename.svelte
- src/InlineLoading/InlineLoading.svelte
- src/MultiSelect/MultiSelect.svelte
- src/Notification/NotificationIcon.svelte
- src/NumberInput/NumberInput.svelte
- src/OverflowMenu/OverflowMenu.svelte
- src/Pagination/Pagination.svelte
- src/PaginationNav/PaginationNav.svelte
- src/ProgressIndicator/ProgressStep.svelte
- src/Search/Search.svelte
- src/Select/Select.svelte
- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.svelte
- src/UIShell/GlobalHeader/Header.svelte
- src/UIShell/GlobalHeader/HeaderAction.svelte
- src/UIShell/GlobalHeader/HeaderActionSearch.svelte
- src/UIShell/HeaderSearch.svelte
- src/UIShell/SideNav/HamburgerMenu.svelte
#904 inlined icons from `carbon-icons-svelte`. Unfortunately, many references were missed in the script.
This didn't throw errors when building the library because `carbon-icons-svelte` is installed as a devDependency.
> hotfix: fix remaining imports from carbon-icons-svelte

- css/all.scss
- css/g10.scss
- css/g100.scss
- css/g80.scss
- css/g90.scss
- css/white.scss
- docs/package.json
- docs/src/App.svelte
- docs/yarn.lock
- package.json
- yarn.lock
Fixes #912 
Related #910 
Popover styles were removed completely from `carbon-components@10.48`. This PR adds `carbon-components@10.47` as a development dependency and manually imports the popover styles in the SCSS files for generating.
> hotfix(popover): include missing Popover styles from carbon-components version 10.47

- src/ComposedModal/ComposedModal.svelte
- src/ContentSwitcher/Switch.svelte
- src/DatePicker/DatePicker.svelte
- src/Select/SelectItem.svelte
Avoid running code server-side by using `onMount` instead of `onDestroy`.
> Refactor `onDestroy` to use `onMount` return function

- src/Popover/Popover.svelte
Support for the `relative` prop in Popover was dropped upstream as early as version 10.36.
This PR manually applies a relative style if `relative` is true.
> hotfix(popover): manually apply relative style if `relative` is true

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/ContextMenu.svx
- docs/src/pages/framed/ContextMenu/ContextMenuTarget.svelte
- docs/src/pages/framed/ContextMenu/ContextMenuTargets.svelte
- src/ContextMenu/ContextMenu.svelte
- tests/ContextMenu.test.svelte
- types/ContextMenu/ContextMenu.svelte.d.ts
Related #620, #811
**Features**
- support custom target elements for `ContextMenu` using the `target` prop
- pass clicked element as `event.detail` in `ContextMenu` "open" event
> Support custom target(s) for `ContextMenu`

- src/DataTable/DataTable.svelte
Fixes #917
```svelte
<script>
import {
DataTable,
OverflowMenu,
OverflowMenuItem,
} from "carbon-components-svelte";
const headers = [
{ key: "name", value: "Name" },
{ key: "port", value: "Port" },
{ key: "rule", value: "Rule" },
{ key: "overflow", empty: true },
];
const rows = [
{ id: "a", name: "Load Balancer 3", port: 3000, rule: "Round robin" },
{ id: "b", name: "Load Balancer 1", port: 443, rule: "Round robin" },
{ id: "c", name: "Load Balancer 2", port: 80, rule: "DNS delegation" },
{ id: "d", name: "Load Balancer 6", port: 3000, rule: "Round robin" },
{ id: "e", name: "Load Balancer 4", port: 443, rule: "Round robin" },
{ id: "f", name: "Load Balancer 5", port: 80, rule: "DNS delegation" },
];
</script>
<DataTable
{headers}
{rows}
on:click:row={(e) => {
// should not trigger when …
```
> Do not dispatch "click", "click:row" events in `DataTable` if target is an `OverflowMenu`

- src/MultiSelect/MultiSelect.svelte
**Fixes**
- select correct item in filterable `MultiSelect` using keyboard navigation
- do not mutate `sortedItems` in `MultiSelect`
> Fix filterable multiselect keyboard selection behavior

- src/Tabs/Tabs.svelte
Without `preventDefault` the link will navigate the page instead of opening the dropdown when the tabs are in the compact mode.
Because the parent element also toggles on click, there is an additional `stopPropagation` to not toggle twice which would be a no-op.
Fixes #626.
> Modify tab click events to prevent navigation.

- src/DatePicker/DatePickerInput.svelte
- src/TextArea/TextArea.svelte
- src/TimePicker/TimePicker.svelte
- src/TimePicker/TimePickerSelect.svelte
- src/Toggle/ToggleSkeleton.svelte
Fixes #944
The `{#if labelText}` conditional that guards a named slot should also check that `$$slots.labelText` is truthy.
> fix(label-text): correctly render "labelText" slots

- src/MultiSelect/MultiSelect.svelte
Fixes #940
Manually set `pointer-events` to "none" when a filterable multiselect menu is not open to prevent a double trigger.
> hotfix(multi-select): prevent double trigger in a filterable multiselect

- src/DatePicker/DatePicker.svelte
Fixes #952
This PR programmatically closes the calendar when pressing "Escape" and stops the event from propagating; this addresses the use case of a date picker within a modal.
> fix(date-picker): stop "Escape" from closing modal

- src/MultiSelect/MultiSelect.svelte
**Fixes**
- blur filterable `MultiSelect` input when pressing "Tab" (fixes #938)
- close filterable menu when pressing "Escape"
- open filterable menu when pressing [Space]
> Fix filterable MultiSelect keydown behavior

- docs/package.json
- docs/vite.config.js
- docs/yarn.lock
Switch from svite to vite + vite-plugin-svelte.
Use `cross-env` to set environment variables platform independently in scripts.
Fixes #959
> Fix docs dev/build on Windows/newer Node version

- css/g10.scss
- css/g100.scss
- css/g80.scss
- css/g90.scss
- css/white.scss
Fixes #966
In the theme SCSS files, the global theme variable should be set before any other imports.
> fix(css): set global theme variable first

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/framed/Breakpoint/Breakpoint.svelte
- package.json
- src/CodeSnippet/CodeSnippet.svelte
- src/DatePicker/DatePicker.svelte
- src/Dropdown/Dropdown.svelte
- src/MultiSelect/MultiSelect.svelte
- src/ProgressIndicator/ProgressStep.svelte
- src/Select/Select.svelte
- src/TextInput/PasswordInput.svelte
- src/TreeView/TreeViewNode.svelte
- types/Select/Select.svelte.d.ts
- yarn.lock
Upgrade sveld to set paths correctly on Windows.
Make Prettier script compatible with Windows and run it.
Fixes #964
> Add `required` prop to Select.

- src/Tile/TileGroup.svelte
Also only fire `select` event for user interaction (from RadioTile).
Uses `set` function instead of `$` to prevent cyclic dependency error.
Fixes #859.
> Update TileGroup on programmatic selection change.

- docs/src/pages/components/RadioTile.svx
- docs/src/pages/framed/RadioTile/RadioTileReactive.svelte
- docs/src/pages/framed/RadioTile/RadioTileReactiveOneWay.svelte
This PR adds two reactive examples for `RadioTile`:
- one-way binding using `on:select` to manage state
- two-way binding using the `selected` prop on `TileGroup` (enabled by #971)
> docs(radio-tile): add reactive examples

- docs/src/pages/components/Modal.svx
- docs/src/pages/framed/Modal/ModalMultiple.svelte
Refs: #975
```svelte
<script>
import { Button, Modal } from "carbon-components-svelte";
let openCreate = false;
let openDelete = false;
</script>
<Button on:click="{() => (openCreate = true)}">Create database</Button>
<Button kind="danger-tertiary" on:click="{() => (openDelete = true)}">
Delete database
</Button>
<Modal
bind:open="{openCreate}"
modalHeading="Create database"
primaryButtonText="Confirm"
secondaryButtonText="Cancel"
on:click:button--secondary="{() => (openCreate = false)}"
on:open
on:close
on:submit
>
<p>Create a new Cloudant database in the US South region.</p>
</Modal>
<Modal
danger
bind:open="{openDelete}"
modalHeading="Delete database"
primaryButtonText="Delete"
secondaryButtonText="Cancel"
on:click:button--secondary="{() => (openDelete = false)}"
on:open
on:close …
```
> docs(modal): add multiple modals example

- package.json
- src/Dropdown/Dropdown.svelte
- src/UIShell/GlobalHeader/Header.svelte
- yarn.lock
Fixes #988 
- Upgrade svelte to version 3.45.0
- Remove redundant "button" role in `Dropdown` to fix a11y warning
- Remove redundant "banner" role in `Header` to fix a11y warning
> Fix a11y warnings emitted by Svelte v3.45

- src/ComboBox/ComboBox.svelte
Manually clearing the input field in a ComboBox does not reset the value.
"Manually" meaning:
- selecting the text and pressing "Backspace"
- deleting each character individually by pressing "Backspace"
The solution is to clear all values and re-open the menu.
> fix(combo-box): reset values when manually clearing input field

- src/ComboBox/ComboBox.svelte
Fixes #797
The "name" prop was mistakenly passed to the `ListBoxField` element when it should be set on the `input` element.
> fix(combo-box): name should be passed to input

- src/Tooltip/Tooltip.svelte
Fixes #924
When shift + tabbing, pressing "Escape" should close the tooltip and re-focus the icon, allowing the user to exit the trap focus.
> fix(tooltip): pressing "Escape" should break out of trap focus

- docs/src/pages/components/ComboBox.svx
- docs/src/pages/components/Dropdown.svx
This PR adds a breaking change notice to the `ComboBox`, `Dropdown` pages following #1004, #1016
> docs: add breaking change notice to `ComboBox`, `Dropdown` docs

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/DataTable.svx
- src/DataTable/DataTable.svelte
- types/DataTable/DataTable.svelte.d.ts
This MR is introducing  `pageSize` and `page` props, allowing  `DataTable` to sort the whole dataset but still display paginated content. It can be also used with non-Carbon pagination components.
How it works:
- pass the whole dataset in the `rows` prop, 
- limit displayed content by using `pageSize` and `page` props  (which are corresponding to the same props in the `Pagination` component).
> feat: allow paginated sorting data table

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ComboBox/ComboBox.svelte
- src/Dropdown/Dropdown.svelte
- src/MultiSelect/MultiSelect.svelte
- tests/ComboBox.test.svelte
- tests/Dropdown.test.svelte
- tests/MultiSelect.test.svelte
- types/ComboBox/ComboBox.svelte.d.ts
- types/Dropdown/Dropdown.svelte.d.ts
- types/MultiSelect/MultiSelect.svelte.d.ts
Closes #1010
This PR loosens the `id` / `selectedId` prop types to allow `any` type, not just strings.
> Type `id` as any in `ComboBox`, `Dropdown`, `MultiSelect`

- src/NumberInput/NumberInput.svelte
Fixes #1031
If `allowEmpty` is enabled on a `NumberInput`, an empty value (`""`) should not be coerced to 0.
The bug stems from this line: `$: value = Number(inputValue)`.
`Number("")` will return `0`.
---
**Expected result**
In the example below, the input should not display a validate error when provided an empty input.
The initial value will be `"" string` for both `bind:value` and `on:change`.
Typing in a number should emit `[x] number` for both.
Clearing the input manually should print "" string` again.
```svelte
<script>
import { NumberInput } from "carbon-components-svelte";
let value = "";
$: console.log("bind:value", value, typeof value);
</script>
<NumberInput
allowEmpty
bind:value
on:change={(e) => console.log("on:change", e.detail, typeof e.detail)}
/>
```
> fix(number-input): do not coerce empty input to 0

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/NumberInput/NumberInput.svelte
- types/NumberInput/NumberInput.svelte.d.ts
Forward the `focus`, `blur` events to the input element.
```svelte
<NumberInput
on:focus={() => console.log("focus")}
on:blur={() => console.log("blur")}
/>
```
> feat(number-input): forward `focus`, `blur` events to input

- CONTRIBUTING.md
- package.json
- rollup.config.js
- scripts/build-docs.js
- yarn.lock
Currently, sveld is only run when running "yarn build:lib." This PR separates sveld into a standalone script so that it can be run separately.
It does not need to be coupled with Rollup as it uses the `glob` option anyways.
- upgrade `sveld` to v0.13.1, which supports programmatic usage
- move `sveld` from `rollup.config.js` to `scripts/build-docs.js`
> build: decouple typegen/docgen from `yarn build:lib`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Checkbox/Checkbox.svelte
- types/Checkbox/Checkbox.svelte.d.ts
Fixes #967 
Currently, it is not possible to programmatically set `checked` or `group` since both props are used to determine the checkbox value.
This proposes initializing `group` as undefined instead of an empty array. If `group` is an array, the Checkbox will use it to determine the checked state; if not, it will default to the `checked` prop.
With this solution, two-way reactivity can be supported for either `checked` or `group` props, but not both. When using the `group` prop, `checked` will have one-way binding (i.e., read but not set).
> Fix checkbox two-way reactivity

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/TextArea/TextArea.svelte
- types/TextArea/TextArea.svelte.d.ts
Fixes #1009
Styling-wise, Carbon does not yet support a "readonly" variant `TextArea`.
However, we should at least fix the `readonly` behavior.
```svelte
<script>
import { TextArea, Button } from "carbon-components-svelte";
let readonly = true;
</script>
<TextArea {readonly} />
<Button on:click={() => (readonly = !readonly)}>Toggle</Button>
```
> fix(text-area): export readonly prop

- docs/src/pages/components/NumberInput.svx
- src/NumberInput/NumberInput.svelte
#1044 caused a regression, where a value of `0` is set to `null`.
This is caused by the following:
```js
$: value = inputValue ? Number(inputValue) : null;
```
`0` is falsy, so `value` is set to `null`. Instead, we should perform an explicit null check on `inputValue`.
> fix(number-input): value `0` should not be converted to `null`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/NumberInput/NumberInput.svelte
- types/NumberInput/NumberInput.svelte.d.ts
> Align NumberInput `change`/`input` with native.

- docs/src/pages/components/SkeletonText.svx
Hello,
While reading the docs, I found duplication on SkeletonText
> fix: duplicated SkeletonText heading removed

- src/DataTable/DataTable.svelte
- src/DataTable/TableHeader.svelte
Fixes #1062, closes #1063
If `headers` is dynamically updated, clicking a sortable table header will sort the incorrect column. Instead of randomly generating an id and keeping track of it through context, we can simply use the required key in `headers` as the id.
```svelte
<script>
import { DataTable } from "carbon-components-svelte";
let headers = [];
let rows = [
// ...
];
setTimeout(() => {
headers = [
{ key: "name", value: "Name" },
{ key: "protocol", value: "Protocol" },
{ key: "port", value: "Port" },
{ key: "rule", value: "Rule" },
];
}, 500);
</script>
<DataTable {rows} {headers} />
```
> fix(data-table): use `headers` key as id

- src/ListBox/ListBoxField.svelte
- src/MultiSelect/MultiSelect.svelte
Fixes #1071
Addresses the following Lighthouse accessibility warning(s):
```
Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children.
```
- role="listbox" children require the role="option" attribute
- add a "aria-multiselectable" attribute to the listbox menu
- move "aria-label" attribute from listbox to listbox menu
- listbox field should not have a "combobox" role when expanded (the non-filterable variant serves as a "button")
> fix(multi-select): resolve a11y violations

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/TextInput/TextInput.svelte
- tests/TextInput.test.svelte
- types/TextInput/TextInput.svelte.d.ts
Fixes #1061 
- user must specify a "type" through `$$restProps` because "type" cannot be dynamic when using `bind:value`
- dispatch instead of forward `change`, `input` events (like `NumberInput`)
**Features**
- if `$$restProps.type="number" and no value is provided, `value` will be `null`
**Fixes**
- use native `bind:value` to fix two-way reactivity
> breaking(text-input): use `bind:value`, dispatch instead of forward `change`, `input` events

- src/MultiSelect/MultiSelect.svelte
Fixes #848
Fixes #938
Fixes #1024
Currently, opening a MultiSelect and then clicking an interactive target will cause the MultiSelect to retain focus.
This is best illustrated by the repro provided in #848.
This removes the hacky blur logic that causes focus issues when clicking away from an open MultiSelect. PR #961 already blurs the input when tabbing.
> fix(multi-select): MultiSelect should correctly lose focus

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/TooltipDefinition/TooltipDefinition.svelte
- tests/TooltipDefinition.test.svelte
- types/TooltipDefinition/TooltipDefinition.svelte.d.ts
TODO:
---
**Features**
- export `open` prop from `TooltipDefinition` for programmatic control; dispatch open, close events
```svelte
<script>
import { TooltipDefinition } from "carbon-components-svelte";
let open = true;
</script>
<TooltipDefinition
bind:open
on:open
on:close
tooltipText="IBM Corporate Headquarters is based in Armonk, New York."
>
Armonk
</TooltipDefinition>
<button on:click={() => (open = !open)}> Toggle: {open} </button>
```
> feat(tooltip-definition): export open prop, dispatch open/close events

- src/UIShell/GlobalHeader/HeaderNavItem.svelte
- src/UIShell/GlobalHeader/HeaderNavMenu.svelte
Fixes #1067
Fixes:
- pressing "Enter" on a `HeaderNavMenuItem` should close the menu
Also fixes:
- blurring the last item in an open menu should close the menu
- remove "role" to fix a11y warning
> fix(ui-shell): `HeaderNavMenu` should close when pressing Enter

- src/UIShell/GlobalHeader/HeaderNavMenu.svelte
Follow-up to #1079
Pressing Space without preventing the default behavior will cause a page with overflow content to scroll.
> fix(ui-shell): prevent default behavior when pressing Space

- src/DataTable/DataTable.svelte
Fixes #1083
If `DataTable` selectedIds is programmatically cleared, the batch selection checkbox should be unchecked.
The issue is that `selectAll` is not reactive. The solution is that it should be `true` if the number of selected row ids equals the total rows (and if there is at least one row in the table).
> fix(data-table): batch selection checkbox should be reactive

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- types/DataTable/DataTable.svelte.d.ts
Supports #1082
```svelte
<DataTable
headers={[
// ...
]}
rows={[
// ...
]}
>
<svelte:fragment slot="cell" let:row let:cell let:rowIndex let:cellIndex>
Row index: {rowIndex}
Cell index: {cellIndex}
</svelte:fragment>
</DataTable>
```
> feat(data-table): pass row index, cell index to "cell" slot

- src/CodeSnippet/CodeSnippet.svelte
Fixes #1087
Svelte v3.46.4 preserves whitespace inside `pre` tags by default. This PR removes the whitespace from inside the `pre` tag in `CodeSnippet`.
> fix(code-snippet): remove whitespace from `pre` tag

- src/Button/Button.svelte
> Do not set `aria-pressed` on link buttons.

- src/UIShell/GlobalHeader/HeaderPanelDivider.svelte
Currently, you can provide a subject using the `HeaderPanelDivider` default slot:
```svelte
<HeaderPanelDivider>Switcher subject 1</HeaderPanelDivider>
<li><span>Switcher subject 1</span></li>
```
However, if you just want the divider, an empty `li` element will be rendered:
```svelte
<HeaderPanelDivider />
<li><span></span></li>
```
This PR uses the semantic `hr` element for a divider without a subject:
```svelte
<HeaderPanelDivider />
<hr />
```
Thus, a divider with a subject will still render a `li` tag:
```svelte
<HeaderPanelDivider>Switcher subject 1</HeaderPanelDivider>
<li><span>Switcher subject 1</span></li>
<hr />
```
- conditionally render the subject if component has a default slot
- use `hr` semantic element to signify a break
- use Carbon's "bx--switcher__item--divider" class …
> fix(ui-shell): use semantic `hr` in `HeaderPanelDivider` to render dividers

- src/OverflowMenu/OverflowMenu.svelte
- src/OverflowMenu/OverflowMenuItem.svelte
Using Up/Down arrow keys to navigate an open overflow menu should skip disabled items.
```svelte
<script>
import { OverflowMenu, OverflowMenuItem } from "carbon-components-svelte";
</script>
<OverflowMenu>
<OverflowMenuItem text="Create key" />
<OverflowMenuItem text="Import key" />
<OverflowMenuItem text="Revoke key" disabled />
<OverflowMenuItem text="Duplicate key" disabled />
<OverflowMenuItem
hasDivider
href="https://cloud.ibm.com/docs/api-gateway/"
text="API documentation"
/>
<OverflowMenuItem hasDivider danger text="Delete service" disabled />
</OverflowMenu>
```
https://user-images.githubusercontent.com/10718366/153732311-f9bf9a60-a90d-4a41-942e-953c1fd49259.mov
> fix(overflow-menu): keyboard navigation should skip disabled items

- src/Tooltip/Tooltip.svelte
> fix(tooltip): aria-label should use iconDescription if triggerText is falsy

- examples/sveltekit/svelte.config.js
to prevent this error that halts dev or build
> config.kit.target is no longer required, and should be removed
> chore(examples):remove config.kit.target from sveltekit example

- src/ListBox/ListBoxField.svelte
- src/MultiSelect/MultiSelect.svelte
Fixes #938
- only prevent `MultiSelect` default behavior when pressing Space/ArrowDown/ArrowUp
> fix(multi-select): ListBoxField should not prevent default keyboard behavior

- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.svelte
Currently, in `TextInput` and `PasswordInput`, the "labelText" slot will not be rendered as the condition only checks for the `labelText` prop.
```svelte
<TextInput placeholder="Enter user name...">
<b slot="labelText" style="color: red">Label</b>
</TextInput>
```
**Fixes**
- correctly render "labelText" slot in `TextInput` and `PasswordInput`
> fix: slottable labelText should render correctly

- docs/src/COMPONENT_API.json
- src/Icon/Icon.svelte
- src/Icon/IconSkeleton.svelte
- src/Notification/NotificationTextDetails.svelte
- src/ToggleSmall/ToggleSmall.svelte
- src/ToggleSmall/ToggleSmallSkeleton.svelte
- src/UIShell/GlobalHeader/HeaderActionSearch.svelte
- types/Icon/Icon.svelte.d.ts
- types/Icon/IconSkeleton.svelte.d.ts
- types/Notification/NotificationTextDetails.svelte.d.ts
- types/ToggleSmall/ToggleSmall.svelte.d.ts
- types/ToggleSmall/ToggleSmallSkeleton.svelte.d.ts
- types/UIShell/GlobalHeader/HeaderActionSearch.svelte.d.ts
The Svelte Language Server allows [component-level comments](https://svelte.dev/faq#how-do-i-document-my-components) through `` syntax.
This PR moves the deprecation notices for components from the script block to the markup template.
This leads to proper component-level comments:
**Fixes**
- use `@component` comments for component deprecation notices
> fix: use `@component` comments for deprecation notices

- src/DataTable/DataTable.svelte
This fixes a regression caused by #1075
The id is needed to update the sort icon direction accordingly.
Fixes #1113
> fix(data-table): pass header key to `TableHeader`

- src/FileUploader/FileUploader.svelte
> fix(file-uploader): `FileUploader` files should not be keyed

- src/FileUploader/FileUploader.svelte
Fixes #1119
Currently, `FileUploader` dispatches add/remove if the number of files changes.
This doesn't account for the case of adding/removing the same number of files. The comparison logic now uses `file.lastModified + file.name` as a heuristic for a file id.
> fix(file-uploader): correctly fire add/remove events

- src/Search/Search.svelte
The JSDoc default type (e.g., `[size="xl"]`) can be omitted as it is already determined by sveld.
```js
/*
* @type {"sm" | "lg" | "xl"} [size="xl"]
*/
```
> refactor(types): remove unnecessary JSDoc default type

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ImageLoader/ImageLoader.svelte
- src/LocalStorage/LocalStorage.svelte
- src/MultiSelect/MultiSelect.svelte
- src/Search/Search.svelte
- src/Tooltip/Tooltip.svelte
- src/TooltipDefinition/TooltipDefinition.svelte
- src/UIShell/HeaderSearch.svelte
- src/UIShell/SideNav/SideNav.svelte
- tests/ImageLoader.test.svelte
- types/ImageLoader/ImageLoader.svelte.d.ts
- types/LocalStorage/LocalStorage.svelte.d.ts
- types/MultiSelect/MultiSelect.svelte.d.ts
- types/Search/Search.svelte.d.ts
- types/Tooltip/Tooltip.svelte.d.ts
- types/TooltipDefinition/TooltipDefinition.svelte.d.ts
- types/UIShell/HeaderSearch.svelte.d.ts
- types/UIShell/SideNav/SideNav.svelte.d.ts
Currently, dispatched events without `e.detail` have a type of `any`.
We can be more specific as a `CustomEvent` detail value defaults to `null`.
> fix(types): dispatched events without a detail value should be `null`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/FileUploader/FileUploaderDropContainer.svelte
- types/FileUploader/FileUploaderDropContainer.svelte.d.ts
**Features**
- convert `FileList` to `File[]` to be consistent with `FileUploader` and `FileUploaderButton`
- add `files` prop for two-way binding
- dispatch instead of forward the `change` event (detail signature: `File[]`)
> feat(file-uploader-drop-container): rework `FileUploaderDropContainer`

- src/DatePicker/DatePicker.svelte
Fixes #1127
Currently, the `DatePicker` calendar will only initialize once. It should be reactive and initialize if any consumer-provided options change.
Updated the implementation to use `calendar.set` API and only trigger the update logic if any option except for `appendTo`, `defaultDate`, or `mode` changes.
> fix(date-picker): update calendar if options change

- COMPONENT_INDEX.md
- docs/package.json
- docs/src/COMPONENT_API.json
- docs/src/pages/components/ProgressBar.svx
- docs/src/pages/components/RadioButton.svx
- docs/yarn.lock
- package.json
- src/ProgressBar/ProgressBar.svelte
- src/RadioButtonGroup/RadioButtonGroup.svelte
- src/StructuredList/StructuredList.svelte
- types/ProgressBar/ProgressBar.svelte.d.ts
- types/RadioButtonGroup/RadioButtonGroup.svelte.d.ts
- yarn.lock
**Features**
- add `RadioButtonGroup` `hiddenLegend` prop to visually hide the legend
- add `ProgressBar` `size` prop to support small size variant
- add `RadioButton` "Hidden legend" example
- add `ProgressBar` "Small size" example
**Refactor**
- remove `StructuredList` `overflow-y` style monkey patch
- upgrade `carbon-components` to v10.54.0
> Align v10.54

- src/DataTable/DataTable.svelte
- src/DataTable/ToolbarBatchActions.svelte
- src/DataTable/ToolbarMenu.svelte
- src/DataTable/ToolbarMenuItem.svelte
- src/FileUploader/FileUploaderSkeleton.svelte
- src/FileUploader/Filename.svelte
This refactors imports to use the direct path where possible.
```diff
- import { InlineCheckbox } from "../Checkbox";
+ import InlineCheckbox from "../Checkbox/InlineCheckbox.svelte";
```
This offers a small performance improvement during development (unused imports should still be tree-shaken by modern bundlers). Importing a components from the JS file will also import other, unnecessary components.
Run "yarn build:lib" to ensure the ESM/UMD bundles can be correctly generated.
> perf: use direct imports where possible

- src/UIShell/GlobalHeader/HeaderAction.svelte
- src/UIShell/GlobalHeader/HeaderActionLink.svelte
The `Icon` component is deprecated.
This replaces `Icon` usage in `HeaderAction` components with the native `svelte:component`.
> refactor: remove Icon usage

- src/UIShell/GlobalHeader/HeaderAction.svelte
- src/UIShell/GlobalHeader/HeaderActionLink.svelte
The icon in `HeaderActionLink` is misaligned with the icon in `HeaderAction`.
This is apparent when using the same icon (in this instance, `LogoGithub20`).
> fix(header-action-link): align icon with `HeaderAction`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/UIShell/GlobalHeader/HeaderAction.svelte
- types/UIShell/GlobalHeader/HeaderAction.svelte.d.ts
Instead of manually typing the Svelte slide transition prop, we can reuse `SlideParams` from `svelte/transition`.
> breaking(header-action): use `SlideParams` to type `transition` prop

- src/TextArea/TextArea.svelte
Tested to make sure #935 didn't regress.
As expected, setting `value` to undefined will empty the `textarea` value, not set it to be "undefined."
```svelte
<script>
import { Button, TextArea } from "carbon-components-svelte";
let value;
</script>
<TextArea bind:value />
<Button on:click={() => (value = undefined)}>Click</Button>
```
> refactor(text-area): use native binding for `value` prop

- docs/src/pages/components/Form.svx
- src/Form/Form.svelte
Closes #1140
Closes #1134
The modifier blocks the consumer from using the native form submission behavior. The consumer still has the ability to prevent the default behavior if needed.
```svelte
<Form
on:submit={(e) => {
e.preventDefault();
}}
/>
```
> breaking(form): do not prevent default behavior on submit event

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/ComboBox.svx
- docs/src/pages/framed/ComboBox/ComboBoxSlot.svelte
- src/ComboBox/ComboBox.svelte
- tests/ComboBox.test.svelte
- types/ComboBox/ComboBox.svelte.d.ts
Closes #1176
This PR adds a default slot to `ComboBox` so the consumer can customize each item slot using their own components or elements. This is more expressive than the `itemToString` prop.
The default slot includes the `item` and `index` as props.
```svelte
<ComboBox
placeholder="Select contact method"
items={[
{ id: "1", text: "Email" },
]}
let:item
let:index
>
{item.text} {item.id} {index}
</ComboBox>
```
> feat(combo-box): make `ComboBox` slottable 

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Dropdown.svx
- docs/src/pages/framed/Dropdown/DropdownSlot.svelte
- src/Dropdown/Dropdown.svelte
- tests/Dropdown.test.svelte
- types/Dropdown/Dropdown.svelte.d.ts
Related https://github.com/carbon-design-system/carbon-components-svelte/issues/1176
Similar to making the `ComboBox` slottable (#1181), this PR makes the `Dropdown` slottable.
```svelte
<Dropdown
selectedId="0"
items="{[
{ id: '0', text: 'Slack' },
{ id: '1', text: 'Email' },
{ id: '2', text: 'Fax' },
]}"
let:item
let:index
>
{item.text} {item.id} {index}
</Dropdown>
```
> feat(dropdown): make `Dropdown` slottable

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/MultiSelect.svx
- docs/src/pages/framed/MultiSelect/MultiSelectSlot.svelte
- src/MultiSelect/MultiSelect.svelte
- tests/MultiSelect.test.svelte
- types/MultiSelect/MultiSelect.svelte.d.ts
Related https://github.com/carbon-design-system/carbon-components-svelte/issues/1176
Similar to making the `ComboBox` slottable (#1181), this PR makes the `MultiSelect` slottable.
```svelte
<MultiSelect
label="Select contact methods..."
items={[
{ id: "1", text: "Email" },
]}
let:item
let:index
>
{item.text}
{item.id}
{index}
</MultiSelect>
```
> feat(multi-select): make `MultiSelect` slottable

- src/UIShell/GlobalHeader/HeaderAction.svelte
Currently, both open/close icons in `HeaderAction` are rendered to avoid the behavior where clicking the icon would double trigger the `isOpen` toggle.
```svelte
<svelte:component this="{icon}" style="{isOpen ? 'display: none' : ''}" />
<svelte:component this="{closeIcon}" style="{!isOpen ? 'display: none' : ''}" />
```
This PR stops the propagation on the `click` event so that inadvertently clicking the icon `svg` element will not double trigger the panel.
As a result, we can properly render the open/close icons based on the `isOpen` condition:
```svelte
{#if isOpen}
<svelte:component this="{closeIcon}" />
{:else}
<svelte:component this="{icon}" />
{/if}
```
> fix(header-action): stop propagation on button click event

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ContextMenu/ContextMenuOption.svelte
- src/Link/Link.svelte
- src/Tag/Tag.svelte
- src/UIShell/GlobalHeader/HeaderAction.svelte
- src/UIShell/GlobalHeader/HeaderActionLink.svelte
- src/UIShell/SideNav/SideNavLink.svelte
- src/UIShell/SideNav/SideNavMenu.svelte
- types/ContextMenu/ContextMenuOption.svelte.d.ts
- types/Link/Link.svelte.d.ts
- types/Tag/Tag.svelte.d.ts
- types/UIShell/GlobalHeader/HeaderAction.svelte.d.ts
- types/UIShell/GlobalHeader/HeaderActionLink.svelte.d.ts
- types/UIShell/SideNav/SideNavLink.svelte.d.ts
- types/UIShell/SideNav/SideNavMenu.svelte.d.ts
Currently, icons are not slottable. Making icons slottable would support make it easier to pass custom styles and events. The workaround currently would be to create a "wrapper" component, which is rather inconvenient.
```svelte
<Tag icon={Add16}>Text</Tag>
<Tag>
Text
<Add16 slot="icon" style="fill: red" on:click />
</Tag>
```
> feat: make icons slottable

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/UIShell/SideNav/SideNavLink.svelte
- types/UIShell/SideNav/SideNavLink.svelte.d.ts
This adds a default slot to `SideNavLink` so that `text` is slottable.
```svelte
<SideNavLink href="/" text="Text" />
<SideNavLink href="/">
<strong>Text</strong>
</SideNavLink>
```
> feat(ui-shell): make `SideNavLink` text slottable

- src/DataTable/ToolbarSearch.svelte
Fixes #1189
This is a hot fix for use cases where `ToolbarSearch` is used standalone. Currently, it depends on the "DataTable" context.
> fix(toolbar-search): context can be undefined

- docs/src/pages/components/DataTable.svx
- docs/src/pages/framed/DataTable/DataTableExpandableZebra.svelte
- src/DataTable/DataTable.svelte
Fixes #1199 
Currently, zebra styles cannot be applied to expandable rows. The Carbon styles expect the child rows to be rendered, and the content to be populated when they are expanded.
```css
.bx--data-table--zebra tbody tr[data-parent-row]:nth-child(4n+1) td { ... }
```
The solution is to render the child rows if the table is expandable for the styles to be properly applied.
> fix(data-table): expandable rows should work with zebra styles

- src/TreeView/TreeView.svelte
Fixes #1214
- `expandNodes` must expand parent nodes that include expandable child nodes
- `collapseNodes` should only filter nodes that are already expanded
https://user-images.githubusercontent.com/10718366/160252282-77ed9096-583d-40bc-a4c9-50c359142cdf.mov
> fix(tree-view): fix filter logic in expandNodes/collapseNodes

- actions/index.js
- docs/src/pages/components/Truncate.svx
- package.json
- src/Truncate/index.js
- src/Truncate/truncate.d.ts
- src/Truncate/truncate.js
- src/index.js
- tests/Truncate.test.svelte
- types/Truncate/truncate.d.ts
- types/index.d.ts
The reason for the separate `actions` folder was due to the limitation of `sveld` not generating types for JS files.
Since [#1218](https://github.com/carbon-design-system/carbon-components-svelte/issues/1218), the `truncate` action can now exist alongside `src/Truncate/Truncate.svelte`.
> breaking(actions): move truncate action to src/Truncate

- src/Checkbox/InlineCheckbox.svelte
This PR fixes a bug where selecting a datatable row will cause the page to scroll back to the top. It applies a fix suggested in #1230.
Sample code to repro:
1. Scroll down the page
2. Select a row
3. The page should scroll to the top
```svelte
<script>
import { DataTable } from "carbon-components-svelte";
const headers = [
{ key: "name", value: "Name" },
{ key: "port", value: "Port" },
{ key: "rule", value: "Rule" },
];
const rows = [
{ id: "a", name: "Load Balancer 3", port: 3000, rule: "Round robin" },
{ id: "b", name: "Load Balancer 1", port: 443, rule: "Round robin" },
{ id: "c", name: "Load Balancer 2", port: 80, rule: "DNS delegation" },
{ id: "d", name: "Load Balancer 6", port: 3000, rule: "Round robin" },
{ id: "e", name: "Load Balancer 4", port: 443, rule: "Round robin" },
{ id: …
```
> fix(data-table): prevent selectable datatable with sticky header from jumping

- docs/src/COMPONENT_API.json
- src/Link/Link.svelte
- tests/Link.test.svelte
- types/Link/Link.svelte.d.ts
While investigating #1232, I noticed that `Link` rest props do not extend `a` element attributes. It only extends `p` attributes.
The solution is to use `@restProps` to explicitly write that it should extend either `a` or `p` attributes.
> fix(link): `$$restProps` should extend `p`, `a` HTML attributes

- docs/src/COMPONENT_API.json
- src/Link/Link.svelte
- types/Link/Link.svelte.d.ts
Fast follow to #1233
Minor nit but the `a` element should precede the `p` element. Intellisense in VS Code will show the "p" attributes on hover. This can be misleading as we want a `Link` to display `a` attributes instead.
This is also consistent with how `ClickableTile` is typed.
> refactor(link): make `a` precede `p` element for restProps

- src/Tag/Tag.svelte
Fixes #1243
This adds an explicit `type="button"` attribute on interactive, filterable tags.
Otherwise, pressing "Enter" will trigger a form submission if the tag is wrapped in a `form` element.
> fix(tag): add `type="button"` on interactive, filter tag variants

- package.json
- types/Button/Button.svelte.d.ts
- types/Button/ButtonSkeleton.svelte.d.ts
- types/Link/Link.svelte.d.ts
- types/Tile/ClickableTile.svelte.d.ts
- types/UIShell/Header.svelte.d.ts
- types/UIShell/HeaderActionLink.svelte.d.ts
- types/UIShell/HeaderNavItem.svelte.d.ts
- types/UIShell/HeaderNavMenu.svelte.d.ts
- types/UIShell/HeaderPanelLink.svelte.d.ts
- types/UIShell/SideNavLink.svelte.d.ts
- types/UIShell/SideNavMenuItem.svelte.d.ts
- types/UIShell/SkipToContent.svelte.d.ts
- yarn.lock
Upgrades `sveld` so that type definitions for links include the optional `sveltekit:reload` attribute.
> chore(deps-dev): upgrade sveld to v0.15.0

- src/DataTable/DataTable.svelte
Without the `=` sign, the reactivity chain were broken.
Using an assignment by prefixing the store with a `$` fixes this.
https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values
Fixes #1254
> Use store $ assignment to fix batch selection

- src/DataTable/ToolbarSearch.svelte
Fixes #1258
Currently, clearing the value of a non-persistent `ToolbarSearch` will close the search bar. Clicking the button won't re-open the search bar.
This PR fixes the logic; when clearing the value, the search bar is kept open and is re-focused.
This is consistent with the [React implementation](https://react.carbondesignsystem.com/?path=/story/components-datatable-toolbar--default-toolbar) as well as the behavior of the basic `Search` component.
https://user-images.githubusercontent.com/10718366/164483650-22468dca-aaa1-4569-8143-21e7b572d9e9.mov
> fix(toolbar-search): clearing value should re-focus search bar

- src/Dropdown/Dropdown.svelte
Fixes #739
The `button` element in the `Dropdown` component requires an explicit `type="button"` value.
Buttons without an explicit type attribute will default to a "submit" behavior when used inside a form.
```svelte
<script>
import { Form, TextInput, Button, Dropdown } from "carbon-components-svelte";
</script>
<Form
on:submit={(e) => {
e.preventDefault();
alert("form submit");
}}
>
<TextInput
id="username"
labelText="User name"
placeholder="Enter user name..."
/>
<Dropdown
selectedId={"0"}
items={[
{ id: "1", text: "Email" },
]}
/>
<Button type="submit">Submit</Button>
</Form>
```
> fix(dropdown): set explicit `type="button` attribute on button

- docs/src/pages/components/RadioButton.svx
- docs/src/pages/components/Tooltip.svx
Fixes #1270
`tooltipBodyId` should be `tooltipId`. However, it's actually not needed in the examples as the [`id` is already assigned](https://github.com/carbon-design-system/carbon-components-svelte/blob/020b2e07b60948cadecc8f9c09fd03a27bf2eef5/src/Tooltip/Tooltip.svelte#L238) to the tooltip content (by default it will be randomly generated).
In fact, it's actually incorrect to assign the tooltip id to the content element since it will create duplicate `id`s:
```svelte
<Tooltip tooltipBodyId="tooltip-body">
<p id="tooltip-body">
Resources are provisioned based on your account's organization.
</p>
</Tooltip>
```
> docs(tooltip): remove unnecessary `tooltipBodyId` in examples

- docs/src/pages/components/Button.svx
- docs/svelte.config.js
Previously, icon imports would be created if the icon(s) in the example code contained [`16|20|24|32` in their names](https://github.com/carbon-design-system/carbon-components-svelte/blob/3950496b7ee88bf2637cb5b652084bd39f186961/docs/svelte.config.js#L17).
Since v11, Carbon icons no longer specify the size in their name. As a result, icon imports are not created; this causes examples with icons to be broken (copy/pasting producing an error).
This PR updates the test to determine if an inline component or expression name is a Carbon icon.
> docs(icons): correctly render icon imports in examples

- src/Tabs/Tabs.svelte
Fixes #1278
Currently, `Tabs` can dispatch repeated "change" events when clicking the same tab. The solution is to use another variable to track the previous index to ensure that the event is fired only when the index has actually changed.
The following code should trigger the "change" event when:
- clicking a different tab
- using the arrow keys to change tabs
- clicking the button which programmatically updates the `selected` value
The event should not fire twice in any circumstance.
```svelte
<script>
import { Tabs, Tab } from "carbon-components-svelte";
let selected = 0;
</script>
<Tabs bind:selected on:change={({ detail }) => console.log("change", detail)}>
<Tab label="Tab 1" />
<Tab label="Tab 2" />
<Tab label="Tab 3" />
</Tabs>
<button on:click={() => (selected = 1)}>Update index …
```
> fix(tabs): dispatch "change" event only if index has changed

- src/ListBox/ListBoxMenuIcon.svelte
- src/ListBox/ListBoxSelection.svelte
Fixes #1281
`translateWithId` is used to customize the labels for icons and buttons based on its state (e.g., if the menu is "open" or closed).
`Dropdown`, `ComboBox`, and `MultiSelect` default `translateWithId` to `undefined` when using transitions (#1281). This value will then be passed to `ListBoxMenuIcon` and `ListBoxSelection`, throwing a runtime error.
This PR ensures that `translateWithId` is only invoked if it's a function. It defaults to the default translations.
> fix: use default values if `translateWithId` is falsy

- src/DataTable/Toolbar.svelte
Fixes #652
Carbon Svelte implements overflow menus using a relative position. As a result, the menu may be clipped by adjacent content. For example, the overflow menu in a `Toolbar` can conflict with the `DataTable` sortable header icon.
The workaround is to manually set an inline `z-index: 1` style on the `Toolbar` so that an open overflow menu is not clipped by content below it.
> fix(toolbar): elevate toolbar z-index above table

- src/CodeSnippet/CodeSnippet.svelte
The expand/collapse button for multi-line code snippets should use the "small" size, not the "field" size.
Ref: https://github.com/carbon-design-system/carbon/pull/11353
> fix(code-snippet): use "small" size for expand/collapse button

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/UIShell/HeaderAction.svelte
- tests/HeaderUtilities.test.svelte
- types/UIShell/HeaderAction.svelte.d.ts
`HeaderAction` typedefs should include the dispatched "open" event.
> fix(header-action): type missing "open" event

- docs/src/pages/components/CodeSnippet.svx
- docs/src/pages/framed/CodeSnippet/CodeSnippetReactive.svelte
- add description to "Hidden copy button"
- add "Reactive example" that demonstrates reactive usage of the `expanded` prop along with the "expand" and "collapse" events
> docs(code-snippet): add "Reactive example"

- src/DataTable/DataTable.svelte
- src/DataTable/TableHeader.svelte
Fixes #1294
`DataTable` header cells have an `id` attribute with the header key as its value. Similarly, rows have an `id` attribute with `row-{row.id}` as its value.
These ids aren't used internally by the `DataTable`. They were initially added to make it easier to query elements through the DOM (e.g., attaching event listeners).
However, because the ids are not random, they can clash with other `DataTable` instances that use the same header keys or row ids.
The solution is to use `data` attributes to store these values.
For table headers, the data attribute is named `data-header`. For rows, the attribute is `data-row`.
**Headers**
```diff
- id={header.key}
+ data-header={header.key}
```
**Rows**
```diff
- id={row.id}
+ data-row={row.id}
```
> breaking(data-table): use `data` attribute instead of `id` for table header/row

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/DataTable.svx
- docs/src/pages/framed/DataTable/DataTableHeaderWidth.svelte
- src/DataTable/DataTable.svelte
- src/DataTable/Table.svelte
- tests/DataTable.test.svelte
- types/DataTable/DataTable.svelte.d.ts
- types/DataTable/Table.svelte.d.ts
Closes #790
Specify an optional `width` or `minWidth` property in the `headers` object to control the width of the column.
In the example below, we set the "Name" column width to be 50%, with a minimum width of 200px.
Note that a [table-layout: fixed](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout#values) rule will be applied to the `table` element when using custom widths.
```svelte
<DataTable
headers="{[
{ key: 'name', value: 'Name', width: '50%', minWidth: '200px' },
{ key: 'protocol', value: 'Protocol', width: '60px' },
{ key: 'port', value: 'Port', width: '60px' },
{ key: 'rule', value: 'Rule', width: '10rem' },
]}"
{rows}
/>
```
> feat(data-table): allow custom column widths

- src/DatePicker/DatePicker.svelte
Bug: when press Enter with the "lenient" date, the value has been updated to wrong value (13/01/2050).
Expected: value set to 01/01/2051, and Calendar closed.
The second input finished with TAB, it works as expected.
https://user-images.githubusercontent.com/1846548/166449917-d616b4e3-abcf-44f2-a54a-81eeb8935077.mp4
Fix:
https://user-images.githubusercontent.com/1846548/166450584-7ded414f-f19a-4154-b49d-b0a6160514d7.mp4
Related specification: https://carbondesignsystem.com/components/date-picker/usage/ "Calendar behaviour" > "Opening the calendar"
Related older, closed bug: https://github.com/carbon-design-system/carbon-components-svelte/issues/876 (In my opinion, it goes against the specification.)
> fix(DatePicker): fixing typed value handling when Enter has pressed

- docs/src/pages/components/DatePicker.svx
- docs/src/pages/framed/DatePicker/DatePickerModal.svelte
- src/DatePicker/DatePicker.svelte
Closes #985
There have been repeated cases where consumers use a `DatePicker` within a `Modal`. This requires the `DatePicker` calendar to be positioned inside the wrapper and next to the `input` element. See #833, #931, #953, #256
Defaulting `flatpickrProps.static` to `true` will make the `DatePicker` work within a modal without additional configuration.
This is a breaking change. However, the consumer can always override this default by setting `flatpickrProps.static` to `false`.
> breaking(date-picker): default `flatpickrProps.static` to true

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- package.json
- src/DatePicker/DatePicker.svelte
- types/DatePicker/DatePicker.svelte.d.ts
- yarn.lock
Using the JSDoc `@see` tag will give better Intellisense in VSCode when hovering over the `flatpickrProps` prop.
> fix(types): use `@see` tag for flatpickr options link

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DatePicker/DatePicker.svelte
- types/DatePicker/DatePicker.svelte.d.ts
Follow-up to #1298 
`static` should be set to `false` in the exported `flatpickrProps` prop for docs/types purposes.
> chore(date-picker): also set `static: true` in exported prop

- docs/src/pages/components/DataTable.svx
- docs/src/pages/components/Theme.svx
- update `Theme` docs to note that it must be used with `all.css`
- update `DataTable` docs to note that custom column widths do not work with a sticky header
> docs: update `Theme`, `DataTable` docs

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/components/ComponentApi.svelte
- package.json
- src/CopyButton/CopyButton.svelte
- src/Dropdown/Dropdown.svelte
- types/CopyButton/CopyButton.svelte.d.ts
- types/Dropdown/Dropdown.svelte.d.ts
- yarn.lock
Both the `CopyButton` and `Dropdown` components have a required prop (`text` and `selectedId` respectively). They will not work without a provided value.
An uninitialized prop in a Svelte component is required.
When using TypeScript, there should be an error if the prop is not provided.
> fix: `CopyButton` text prop and `Dropdown` selectedId prop should be required

- src/Checkbox/Checkbox.svelte
- src/ListBox/ListBoxMenuItem.svelte
Closes #1205
The `title` attribute should be set if an item's label text is truncated.
This implementation using the `element.innerText` method since the text may not be provided via a prop (e.g., slots).
> feat: set title attribute in `CheckBox`, `MultiSelect`, `Dropdown`, `ComboBox`  if label is truncated

- src/Accordion/AccordionSkeleton.svelte
- src/DatePicker/DatePicker.svelte
- src/Dropdown/Dropdown.svelte
- src/FileUploader/FileUploaderButton.svelte
- src/MultiSelect/MultiSelect.svelte
- src/NumberInput/NumberInput.svelte
- src/Select/Select.svelte
- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.svelte
This PR refactors components to use the [class directive](https://svelte.dev/docs#template-syntax-element-directives-class-name) where possible to make conditionally applied classes easier to read.
**Before**
```svelte
class="{datePickerType && `bx--date-picker--${datePickerType}`} {datePickerType === 'range' && $labelTextEmpty && 'bx--date-picker--nolabel'}"
```
**After**
```svelte
class:bx--date-picker--simple="{datePickerType === 'simple'}"
class:bx--date-picker--single="{datePickerType === 'single'}"
class:bx--date-picker--range="{datePickerType === 'range'}"
class:bx--date-picker--nolabel="{datePickerType === 'range' && $labelTextEmpty}"
```
> refactor: prefer class directive over class attribute

- src/Tabs/Tab.svelte
- src/Tabs/Tabs.svelte
Fixes #572
Currently, if the selected index for a `Tabs` component is programmatically updated (i.e., tab is changed not through clicking or keyboard navigation), the selected tab will "steal" the focus.
The expected behavior is that the appropriate element should retain the focus.
The solution is to only focus the tab if the consumer is using keyboard navigation. Clicking a tab will already focus the tab.
In the demo below, the selected tab is not focused if it is programmatically set.
- typing in an input retains its focus
- clicking the button retains its focus
https://user-images.githubusercontent.com/10718366/170882840-6631c784-61c3-482a-9c0e-87f6698a8e87.mov
> fix(tabs): tab should not steal focus if index is programmatically updated

- docs/src/pages/components/Tabs.svx
```svelte
<Tabs>
<Tab label="Tab label 1" />
<Tab label="Tab label 2" disabled />
<Tab label="Tab label 3" disabled />
<Tab label="Tab label 4" />
<svelte:fragment slot="content">
<TabContent>Content 1</TabContent>
<TabContent>Content 2</TabContent>
<TabContent>Content 3</TabContent>
<TabContent>Content 4</TabContent>
</svelte:fragment>
</Tabs>
```
> docs(tabs): add example "Disabled tabs"

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Checkbox/Checkbox.svelte
Follow-up to #1317 
#1317 has not yet been released. The `Checkbox` exposes a `title` prop. If the consumer provides a value, the `title` prop should not be overridden if the label is truncated.
> fix(checkbox): do not set title attribute if already provided

- src/Dropdown/Dropdown.svelte
- src/ListBox/ListBoxMenuItem.svelte
A couple of accessibility points here:
- the `ListBoxMenuItem` should have an "option" role
- if an item is selected (active), it should have an attribute `aria-selected="true"`
- remove redundant `role`, `id` from `Dropdown`
> fix(dropdown): remove redundant role/id

- src/ComposedModal/ComposedModal.svelte
- src/Modal/Modal.svelte
- src/Modal/modalStore.js
Fixes #1324
If multiple modals are open at once, the "bx--body--with-modal-open" class may be unexpectedly removed when closing one of the modals.
The solution is to use a store to keep track of the open modals. The class should only be removed if no modal is open.
> fix(modal): nested modals should correctly toggle the body class

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/ComboBox.svx
- docs/src/pages/components/Dropdown.svx
- docs/src/pages/components/MultiSelect.svx
- src/ComboBox/ComboBox.svelte
- src/Dropdown/Dropdown.svelte
- src/ListBox/ListBoxMenuItem.svelte
- src/MultiSelect/MultiSelect.svelte
- tests/ComboBox.test.svelte
- tests/Dropdown.test.svelte
- tests/MultiSelect.test.svelte
- types/ComboBox/ComboBox.svelte.d.ts
- types/Dropdown/Dropdown.svelte.d.ts
- types/ListBox/ListBoxMenuItem.svelte.d.ts
- types/MultiSelect/MultiSelect.svelte.d.ts
Closes #1326 
This PR adds the option to disable individual items in a `Dropdown`, `MultiSelect`, or `ComboBox`.
Set `item.disabled` to `true` for the item to be disabled.
**Example**
```svelte
<Dropdown
selectedId="0"
items={[
{ id: "1", text: "Email", disabled: true },
]}
/>
```
> feat: support `item.disabled` key for `Dropdown`, `MultiSelect`, `ComboBox`

- docs/src/pages/components/Modal.svx
- docs/src/pages/framed/Modal/ModalButtonWithIcon.svelte
- docs/src/pages/framed/Modal/ModalCustomFocus.svelte
- docs/src/pages/framed/Modal/ModalExtraSmall.svelte
- docs/src/pages/framed/Modal/ModalLarge.svelte
- docs/src/pages/framed/Modal/ModalPreventOutsideClick.svelte
- docs/src/pages/framed/Modal/ModalScrollingContent.svelte
- docs/src/pages/framed/Modal/ModalSmall.svelte
This adds a couple more examples.
It also does not open modals by default in some of the examples as the close button would be auto-focused.
> docs(modal): add "Has scrolling content," "Custom focus" examples

- src/DataTable/DataTable.svelte
- src/DataTable/ToolbarSearch.svelte
Currently, `DataTable` will add a `cells` property to each row which contains computed metadata for each header (e.g., key, display value, resolved value if using nested headers).
This is undesirable as it overrides the "cells" property in a row.
Although technically a breaking change, I'm considering this a fix as no row properties should be overridden in the first place.
Additional changes:
- chore: touch up prop descriptions (use periods where needed)
- refactor: remove unneeded third argument in `resolvePath()`
- perf: when resolving path, early return `object[path]` if value exists
> fix(data-table): do not overwrite `row.cells` property

- src/DataTable/DataTable.svelte
https://github.com/carbon-design-system/carbon-components-svelte/commit/d2cdb8eb0f5a1bdf3e7e8d01ae859542d470c9d4#r75383503
https://github.com/carbon-design-system/carbon-components-svelte/pull/1336 isn't released yet; this PR applies a suggestion to save the `rows` reference when reducing it to an object.
> perf(data-table): save rows reference when reducing

- src/ComposedModal/ComposedModal.svelte
- src/Modal/Modal.svelte
- src/Modal/modalStore.js
- Class application:
- Can be simplified using `toggle`.
- Can be extracted, so it does not need to be duplicated across components.
- On destroy cleanup can be extracted and unified with open/close logic.
- `ComposedModal` ID can be removed again.
Addresses comments on [`22f93ee`](https://github.com/carbon-design-system/carbon-components-svelte/commit/22f93ee675c04e96a3119fdd76eaa273614891cd)
> Simplify open modal tracking code

- src/ComboBox/ComboBox.svelte
- src/MultiSelect/MultiSelect.svelte
This fixes #1262 where the input value can be lost if re-rendering the `ComboBox`. We use the native `bind:` directive Instead of manually managing `value` through a secondary `inputValue` prop.
A similar bug came up before in #935, which was fixed by https://github.com/carbon-design-system/carbon-components-svelte/pull/1169.
**Fixes**
- use native binding for `value` prop in `ComboBox`, `MultiSelect`
> fix: use native binding for `value` prop in `ComboBox`, `MultiSelect`

- src/Select/Select.svelte
- src/Select/SelectItem.svelte
Fixes #570 
If the `selected` prop is not provided to `Select`, the value of the first `SelectItem` should be used. Currently, the `SelectItem` value is shown in the UI as the default, but `selected` is not updated in turn.
This logic matches the native behavior of the `select` element.
The specific use case is that – because `selected` is an optional prop – no value may be initially provided. The consumer may either bind to `selected` or opt not to use it all. For example, they may choose to use the dispatched `change` event.
```svelte
<script>
import { Select, SelectItem } from "carbon-components-svelte";
let selected = undefined;
</script>
<Select
labelText="Carbon theme"
bind:selected
on:change={(e) => {
console.log("change", e.detail);
}}
>
<SelectItem value="white" text="White" /> …
```
> fix(select): use first `SelectItem` value as default if `selected` is undefined

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Select/Select.svelte
- types/Select/Select.svelte.d.ts
Follow-up to #1355
This updates the "change" event type to reflect the `selected` prop type `string | number`.
> chore(select): update dispatched change event type

- src/Select/Select.svelte
Follow-up to #1353
If `selected` is `undefined` or not provided, the "change" event will be dispatched since the first `SelectItem` value will be set as the default.
The "change" event should only be dispatched when the value is actually changed.
```svelte
<script>
import { Select, SelectItem, Button } from "carbon-components-svelte";
let selected = undefined;
</script>
{selected}
{typeof selected}
<Select
bind:selected
on:change={(e) => {
console.log("change", e.detail, typeof e.detail);
}}
>
<SelectItem value={initialValue}  />
<SelectItem value={1}  />
<SelectItem value={2} />
<SelectItem value={3}  />
<SelectItem value={4}  />
</Select>
<Button
on:click={() => (initialValue = typeof initialValue === "number" ? "0" : 0)}
>
Toggle
</Button>
<Button
on:click={() => {
selected = …
```
> fix(select): do not dispatch "change" event on initial load

- docs/src/pages/components/Select.svx
This also demonstrates usage of the dispatched "change" event. This is the only way to get the selected value if the consumer does not use the `selected` prop.
> docs(select): adjust default example to demo usage without `selected` prop

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Slider.svx
- src/Slider/Slider.svelte
- tests/Slider.test.svelte
- types/Slider/Slider.svelte.d.ts
The `bx--slider` class in the `Slider` component has max-width of `40rem`. It would be nice to set it to have a width of 100%.
Because `$$restProps` is spread to the top-level `div` element in `Slider`, the only way to override this rule is to use global styles:
```css
:global(.bx--slider-container) {
width: 100%;
}
:global(.bx--slider) {
max-width: none;
}
```
This PR adds a `fullWidth` prop that sets a full width style using inline style attributes.
Pictured below compares the `Slider` with and without the `fullWidth` property set.
```svelte
<Slider fullWidth />
<Slider />
```
> feat(slider): add `fullWidth` prop

- src/ComposedModal/ComposedModal.svelte
Fixes #1360
This resolves the type error `Cannot read properties of null (reading 'querySelector')`.
> fix(composed-modal): node to focus is possibly `null`

- docs/src/global.css
- src/UIShell/SideNavMenu.svelte
The Carbon styles apply a max-height of `93.75rem` to the `SideNavMenu`. Although this seems to be a deliberate design choice, I don't think a cap should be set.
This overrides the max-height to be `none` if the menu is expanded.
> fix(side-nav-menu): expanded `SideNavMenu` should not have a max-height 

- src/UIShell/SideNavMenu.svelte
The chevron icon in the `SideNavMenu` should not be focusable.
See the recording below for the current behavior:
https://user-images.githubusercontent.com/10718366/175302933-bbe4e8b0-2db6-44ba-9f2f-12d98b12d864.mov
> fix(side-nav-menu): chevron icon should not be focusable

- docs/src/pages/framed/FluidForm/FluidFormInvalid.svelte
- src/TextInput/PasswordInput.svelte
Currently, a `PasswordInput` in a `FluidForm` has a broken invalid state.
This fixes the invalid state to align with the upstream implementation.
---
> fix(password-input): support invalid state when used in a `FluidForm`

- src/CodeSnippet/CodeSnippet.svelte
Using the multi-line `CodeSnippet` will log a warning in development because the `text` prop in `CopyButton` is marked as required,
```
<CopyButton> was created without expected prop 'text'
```
This PR refactors `CodeSnippet` to pass the `text` prop to `CopyButton`. It also passed down the `copy` prop and forwards the dispatched `copy` event.
> refactor(code-snippet): pass required `text` prop to `CopyButton`

- src/UIShell/SideNavMenu.svelte
The chevron icon in the UI Shell `SideNavMenu` icon should not have a title attribute.
Ref: https://github.com/carbon-design-system/carbon/blob/f17b8147b7e66325bbee6bcc6a6180d9aa5ec4d5/packages/react/src/components/UIShell/SideNavMenu.js#L71
> fix(side-nav-menu): remove title attribute from menu icon

- docs/src/pages/components/ComboBox.svx
- docs/src/pages/framed/DatePicker/DatePickerModal.svelte
- rename `ComboBox` example "Selected id" to "Initial selected id"
- revise `DatePicker` example "DatePicker in a modal" to prevent the iframe from stealing focus
> docs: rename `ComboBox` example, do not open modal in `DatePicker` by default

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/CodeSnippet/CodeSnippet.svelte
- types/CodeSnippet/CodeSnippet.svelte.d.ts
Follow-up to #1372
#1372 forwarded instead of dispatched a custom `copy` event. If it's not explicitly annotated, `sveld` will assume it's a native event.
> chore(code-snippet): preserve custom copy event type

- src/Notification/InlineNotification.svelte
- src/Notification/ToastNotification.svelte
This reverts commit 924b6d352eebf5c82da63f0ead450dc59e80ca30.
v0.66.2 actually contains breaking changes. It breaks the close behavior of `ToastNotification` and `InlineNotifiation` if svelte version 3.48 or greater is not used.
I'm going to revert, publish a patch, deprecate v0.66.2, and re-revert in v0.67.0.
> Revert "fix(notification): `on:close` should be cancellable (#1379)"

- src/UIShell/SideNav.svelte
Fixes #786 
See https://github.com/carbon-design-system/carbon-components-svelte/issues/786#issuecomment-1181923149 for a repro.
The `SideNav` overlay does not have a `z-index` set when active. This can cause other elements to visually supersede it. A hotfix would be to manually apply a `z-index` value when the overlay is active.
The rationale for the value `6000` is that it corresponds to the [`overlay` z-index](https://github.com/carbon-design-system/carbon/blob/5825cb460bb147bc7580bda93845b80a66a8ba51/packages/styles/scss/utilities/_z-index.scss#L18) as defined in Carbon styles.
> fix(side-nav): set high `z-index` on open overlay

- docs/src/pages/components/ComboBox.svx
- docs/src/pages/framed/ComboBox/FilterableComboBoxCustomLabel.svelte
- src/ComboBox/ComboBox.svelte
Fixes #1405
The ComboBox does not display the custom label set with `itemToString` in the input after a selection, when combined with the filterable option with `shouldFilterItem`.
This is now fixed, so that all direct accesses to the default attribute `text` are replaced with accessing `itemToString` instead.
Also adds the specific use case of combining filter and custom string to the documentation.
> fix(combobox): filterable and custom label (#1405)

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Toggle.svx
- src/Toggle/Toggle.svelte
- tests/Toggle.test.svelte
- types/Toggle/Toggle.svelte.d.ts
Fixes #1413
Passing an empty string to `labelText` will make the `Toggle` appear to have an extra top margin. `Toggle` should expose a `hideLabel` prop that visually hides the label for accessibility.
```svelte
<Toggle labelText="Push notifications" hideLabel />
```
> fix(toggle): add missing `hideLabel` prop 

- src/Toggle/Toggle.svelte
Fixes #1137
Rapidly clicking the `Toggle` label text can select it. The upstream Carbon implementation has [added a `user-select: none`](https://github.com/carbon-design-system/carbon/pull/11670) rule to the toggle. However, the rule is only available in Carbon v11 in the `@carbon/styles` package.
We can set an inline `style` attribute for the implementation.
> fix(toggle): `labelText` should not be selectable

- src/Pagination/Pagination.svelte
Fixes #1412
If there is only one item, the default "items" text should be singular.
```svelte
<Pagination totalItems={1} pageSizes={[10, 15, 20]} />
<Pagination pagesUnknown totalItems={1} pageSizes={[10, 15, 20]} />
<Pagination pagesUnknown pageSize={1} totalItems={1} />
```
> fix(pagination): correctly pluralize default item text

- src/Toggle/Toggle.svelte
Fixes #1413
Follow-up to #1414
Although `hideLabel` visually hides the label text, the `margin-top` property on `.bx--toggle__switch` still has to be overridden because the `@carbon/styles` are composed differently (the label has a margin-bottom instead of the switch having a margin-top).
> fix(toggle): override margin top if `hideLabel` is true

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/NumberInput/NumberInput.svelte
- tests/NumberInput.test.svelte
- types/NumberInput/NumberInput.svelte.d.ts
Fixes #1421
`NumberInput` should forward keydown and keyup events.
```svelte
<NumberInput
on:keydown={(e) => {
console.log("keydown", e);
}}
on:keyup={(e) => {
console.log("keyup", e);
}}
/>
```
> fix(number-input): forward keydown, keyup events

- src/Notification/NotificationButton.svelte
- src/Notification/NotificationIcon.svelte
Fixes https://github.com/carbon-design-system/carbon-preprocess-svelte/issues/39
The `optimizeCss` plugin from `carbon-preprocess-svelte` fails to recognize dynamic strings like `bx--{notificationType}-notification__close-icon`. This hardcodes the class name in full so that it can be statically analyzed.
Note that `svelte:component` does not support the `class:` directive so we have to hardcode the classes in the `class` attribute.
> fix(notification): avoid dynamic class names in `NotificationButton`, `NotificationIcon`

- src/DatePicker/DatePickerInput.svelte
- src/TextInput/TextInput.svelte
Related #1425
This PR replaces dynamically-formed classes with the `class:` directive to avoid situations like https://github.com/carbon-design-system/carbon-preprocess-svelte/issues/39 where `purgecss` is unable to recognize interpolated strings.
> refactor: use class directive in `TextInput`, `DatePickerInput`

- docs/src/global.css
- src/UIShell/Content.svelte
- src/UIShell/SideNav.svelte
- src/UIShell/navStore.js
Fixes #1145, closes #1406
Related https://github.com/carbon-design-system/carbon/issues/7909
This PR removes the left margin from the `Content` component if the `SideNav` is collapsed.
This PR is an alternative to #1406. The implementation uses a Svelte store instead of global CSS. In part, the motivation is to avoid the `:global` directive. The second reason is that the inline HTML style attribute offers a higher specificity.
> fix(ui-shell): remove `Content` left margin if `SideNav` is collapsed

- docs/src/global.css
The docs site manually overrides UI Shell styles. It applies these styles globally, which affect the UI Shell standalone examples.
One solution to scope the overrides to just the docs site. However, from a philosophical standpoint, I believe overrides should be avoided where possible as they can lead to confusion (e.g., #1145) over what styles are actually correct.
> style(docs): remove UI Shell overrides

- src/Toggle/Toggle.svelte
ARIA Authoring Guide recommends adding the role "switch" to on/off components like the toggle.
- [ARIA Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/switch/)
- [Documentation For Switch Role](https://w3c.github.io/aria/#switch)
- [Example of Checkbox Switch](https://www.w3.org/WAI/ARIA/apg/example-index/switch/switch-checkbox.html)
> Add Switch Role to Toggle Component for Accessibility

- src/Slider/Slider.svelte
Ref: https://github.com/carbon-design-system/carbon/pull/11798
This implements a backported change to the `Slider` component, which adds the `aria-labelledby` attribute to the slider thumb for accessibility.
> fix(slider): add `aria-labelledby` slider thumb

- src/Checkbox/InlineCheckbox.svelte
Ref: https://github.com/carbon-design-system/carbon/pull/11908
This implements a backported change to the `InlineCheckbox` component, which avoids setting `aria-checked="mixed"` if the checkbox is indeterminate.
Within the library itself, `InlineCheckbox` is only used in a selectable `DataTable`.
> fix(inline-checkbox): remove `aria-checked="mixed"` if indeterminate

- docs/src/COMPONENT_API.json
- src/Notification/NotificationActionButton.svelte
- types/Notification/NotificationActionButton.svelte.d.ts
This way, props from Button can be used in NotificationActionButton and
still typecheck correctly.
> fix(notification): add extends to button

- CHANGELOG.md
- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- package.json
- src/DataTable/ToolbarBatchActions.svelte
- src/Notification/NotificationActionButton.svelte
- types/DataTable/ToolbarBatchActions.svelte.d.ts
- types/Notification/NotificationActionButton.svelte.d.ts
Fixes #1438.
Give the user the ability to override the functionality of the cancel button by passing in their own function. If no override is provided, the existing functionality of reseting selected row ids is preserved.
Example implementation:
```
<ToolbarBatchActions cancel={()=>{console.log("User clicked cancel!")}}>
...
</ToolbarBatchActions>
```
> feat(ToolbarBatchActions): Override cancel button

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/ToolbarBatchActions.svelte
- types/DataTable/ToolbarBatchActions.svelte.d.ts
Follow-up to #1440
When testing a scenario of a `DataTable` with a controlled batch actions toolbar, I noticed that setting `active` to `false` would not close it if there are selected rows.
This is because the toolbar is activated if there are one or more selected rows OR if `active` is `true`:
```ts
$: showActions = batchSelectedIds.length > 0 || active;
```
Therefore, it's possibly to programmatically activate a toolbar but not close it in the same fashion.
The solution is two-fold:
1. Set `active` to `true` if one or more rows are selected. Then, `showActive` should be set to `false` if the `active` prop is changed from `true` to `false`. As a result, the `active` prop becomes reactive.
2. Type `active` to be `undefined` by default. `showActive` should only be set to `false` if …
> fix(toolbar-batch-actions): `active` prop should be reactive

- docs/src/pages/components/DataTable.svx
- docs/src/pages/components/InlineNotification.svx
- docs/src/pages/components/ToastNotification.svx
- docs/src/pages/framed/DataTable/DataTableBatchSelectionToolbarControlled.svelte
Along with other small docs updates, this PR adds an example for a `DataTable` with a controlled `ToolbarBatchActions` (#1440, #1441).
- add `DataTable` example "Batch selection with controlled toolbar"
> docs: add `DataTable` example "Batch selection with controlled toolbar"

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- types/DataTable/DataTable.svelte.d.ts
Proposed solution to #1449
Implementation follows existing `click:row--expand ` pattern. 
No backwards-compatibility issues AFIAK.
> emit select event on checkbox or radio button activity

- docs/src/pages/components/DataTable.svx
QOL touch-up of `DataTable` docs to improve the example names.
> docs(data-table): improve example names and descriptions

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- types/DataTable/DataTable.svelte.d.ts
Follow-up to #1450
#1450 added a dispatched event `click:row--select` for selectable rows.
This PR adds an additional event when using a batch selectable `DataTable`, where clicking the checkbox in the header will either select or deselect all rows. A similar event would be `click:header--expand` for a batch expandable `DataTable`.
Compared to `click:row--select`, one difference in the `e.detail` API is that the checkbox state can be `indeterminate`.
```ts
// indeterminate
0 < n < rows.length - 1
```
**Sample usage**
```svelte
<DataTable
batchSelection
on:click:header--select={(e) => {
console.log("header--select", e.detail.selected); // boolean
console.log("header--select", e.detail.indeterminate); // boolean
}}
/>
```
> feat(data-table): dispatch `on:click:header--select` event

- docs/src/pages/components/DataTable.svx
- docs/src/pages/framed/DataTable/DataTablePagination.svelte
Currently, any inline examples in the docs site will not include variables in the `script` block. This PR extracts the example into an `iframe` so that it's easier to read. It also refactors the example for simplicity and uses individual variables for `pageSize` and `page` instead of an object.
> docs(data-table): extract "Sortable with pagination" example into iframe

- src/UIShell/Content.svelte
- src/UIShell/SideNav.svelte
- src/UIShell/navStore.js
Fixes #1459
#1428 unsets the `Content` left margin but it shouldn't do so if `SideNav` is the rail variant.
> fix(ui-shell): do not unset `Content` left margin for rail `SideNav`

- carbon.yml
Related: https://github.com/carbon-design-system/carbon-platform/issues/967
The Carbon Svelte library has a design kits page, to list compatible design kits with the components/patterns in the Carbon Svelte library: https://next.carbondesignsystem.com/libraries/carbon-components-svelte/latest/design-kits
This list of `designKits` would normally be inherited from the `carbon-styles` library (PR https://github.com/carbon-design-system/carbon/pull/12033), but Carbon Svelte has yet to upgrade to v11.
By not inheriting `designKits`, we can specify in this library so the v10 Figma kits are listed, not the new v11 Figma kits.
Once Carbon Svelte updates to v11, we can remove the `designKits` array in the config file.
> docs: index compatible design kits

- src/Dropdown/Dropdown.svelte
- src/ListBox/ListBoxMenuItem.svelte
Fixes #1470
If keyboard navigation is used to navigate the `Dropdown` menu, the highlighted item should scroll into view.
Updating `ListBoxMenuItem` should apply the same behavior to `Dropdown`, `ComboBox`, and `MultiSelect`.
> fix(list-box-menu-item): scroll item into view when using keyboard navigation

- src/ComboBox/ComboBox.svelte
Without preventing the default behavior, pressing the arrow up/down keys will change the cursor position in the input box.
Like `Dropdown`, the default behavior for Enter/ArrowDown/ArrowUp should be prevented.
> fix(combo-box): prevent default when pressing Enter/ArrowUp/ArrowDown

- src/Dropdown/Dropdown.svelte
- src/MultiSelect/MultiSelect.svelte
Pressing "Escape" should close the menu. `ComboBox` already implements this.
> fix: pressing "Escape" should close `Dropdown`, `MultiSelect` menu

- src/ListBox/ListBoxMenuItem.svelte
Fast-follow to #1471
#1471 added missing behavior to scroll the highlighted item into view.
However, the incorrect [`scrollIntoView` strategy](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) was used.
Using `block: "end"` causes the entire browser page to scroll if there is overflowing content. Setting `block: "nearest"` will only scroll the item into view as necessary.
> fix(list-box-menu-item): do not scroll entire page when using keyboard navigation

- src/Button/Button.svelte
Fixes #1476
Icon-only buttons should omit the "bx--btn__icon" class.
> fix(button): avoid left margin style for icon-only buttons

- package.json
- src/Toggle/Toggle.svelte
- src/UIShell/HeaderSearch.svelte
- yarn.lock
Fixes #1479
Svelte [v3.50.0](https://github.com/sveltejs/svelte/blob/ed078e31fe1d3594c105a17f7fb6def769b386f6/CHANGELOG.md#3500) checks for additional a11y violations.
- For the `Toggle` component, the `a11y-role-has-required-aria-props` warning is a false positive since `input role="switch" type="checkbox"` has [built in semantics](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked), and does not require an additional `aria-checked` attribute.
- Aria attributes in `HeaderSearch` have been updated to reflect the upstream implementation of the search bar as seen on https://carbondesignsystem.com.
> fix(a11y): resolve accessibility warnings in Svelte 3.50.0

- src/Button/Button.svelte
#1477 removed the "bx--btn__icon" class for icon-only buttons to fix #1476.
However, it caused a visual regression in the next/previous buttons in `Pagination` and `PaginationNav`, which require the "bx--btn__icon" class.
The solution is to use an inline style attribute to manually unset the left margin instead of removing the class altogether. This is the simplest solution because it does not change the existing component API (like adding a prop/slot or using context).
---
> fix(button): resolve visual regression in `Pagination`, `PaginationNav`

- src/ImageLoader/ImageLoader.svelte
- src/UIShell/HeaderAction.svelte
fixes #1501
Adds `local` to transitions to prevent them from playing between page navigations.
https://svelte.dev/docs#template-syntax-element-directives-transition-fn-transition-events
> Local transitions only play when the block they belong to is created or destroyed, not when parent blocks are created or destroyed.
> fix transitions delaying navigation

- src/UIShell/HeaderSearch.svelte
Fixes #1504
#1480 [updated markup](https://github.com/carbon-design-system/carbon-components-svelte/commit/73385bf598740f616946e974b94c970d8b8e3825#diff-aafe2deee611782c19726e6a62ac9472b9001003bac8342afd555d42bc9b5c34R64) in `HeaderSearch`, which caused some styles to be lost.
> fix(header-search): fix layout regression

- src/ListBox/ListBoxMenuItem.svelte
Fixes #1505
Fixes #1503
`ref?.matches(':hover')` will not throw if `ref` is undefined or null. However, it does not prevent the `ref.scrollIntoView` statement from being evaluated if `ref` is `null`, resulting in a runtime error.
> fix(list-box-menu-item): avoid element reference error

- README.md
- docs/src/pages/index.svelte
- add note on using `optimizeImports` with `svelte-preprocess` (closes #1500)
- point link to v10 SASS guide (#1489)
- remove note on minimum Svelte version required
> docs: update README, links

- carbon.yml
As found in https://github.com/carbon-design-system/carbon-platform/issues/907, added a "Get started" page to the Carbon Svelte library with https://carbondesignsystem.com/developing/frameworks/svelte content.
> docs: index getting started content

- docs/src/pages/components/PaginationNav.svx
- docs/src/pages/framed/PaginationNav/PaginationNavReactive.svelte
This adds the following examples to the `PaginationNav` docs:
- Reactive example
- Total
- Shown
- Custom button text
> docs(pagination-nav): add more examples

- src/NumberInput/NumberInput.svelte
Proposal to fix https://github.com/carbon-design-system/carbon-components-svelte/issues/1510
> fix(number-input): fix interaction between `allowEmpty` and `min`

- package.json
- src/CodeSnippet/CodeSnippet.svelte
- src/ComposedModal/ComposedModal.svelte
- src/ComposedModal/ModalBody.svelte
- src/DataTable/DataTableSkeleton.svelte
- src/FileUploader/FileUploaderButton.svelte
- src/FileUploader/FileUploaderDropContainer.svelte
- src/ListBox/ListBoxField.svelte
- src/Modal/Modal.svelte
- src/NumberInput/NumberInput.svelte
- src/Search/Search.svelte
- src/StructuredList/StructuredListRow.svelte
- src/TextArea/TextArea.svelte
- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.svelte
- src/Tile/SelectableTile.svelte
- src/TimePicker/TimePicker.svelte
- src/Tooltip/Tooltip.svelte
- src/TreeView/TreeViewNodeList.svelte
- src/UIShell/SideNav.svelte
- yarn.lock
Fixes #1517
Ignore a11y warnings emitted from Svelte version 3.51.
> fix(a11y): ignore false positive a11y warnings

- docs/src/COMPONENT_API.json
- src/Search/Search.svelte
- tests/Search.test.svelte
- types/Search/Search.svelte.d.ts
Fixes #1520
`$$restProps` are forwarded to the `input` element. However, this is not reflected in the generated TypeScript definitions.
For example, the following would produce an error in TypeScript:
```svelte
<Search name="q" />
```
> fix(search): prop types should extend `input` attributes

- src/DataTable/DataTable.svelte
remove the `derived` import from "svelte/store"
> no need to import derived from "svelte/store"

- src/ProgressIndicator/ProgressStep.svelte
Wraps label/secondary label in container that places the secondary label under the primary one.
(Looked up element hierarchy in React implementation.)
Fixes #1532.
> Fix vertical layout of ProgressStep.

- docs/src/pages/components/NumberInput.svx
- src/NumberInput/NumberInput.svelte
- tests/NumberInput.test.svelte
Fixes #233, fixes #486, fixes #1554
Use the built-in function of steppers then assign the value.
JS has a bug with floating point which result in a visual bug where input has many decimals. 
There's 2 ways to fix this : 
1. Converting `float` to an `int` (by multiplying by 10 x number of decimals) then make the equation then reconvert to a floating value.
2. Use built-in functions to step up and down.
I prefer the second approach which is simpler.
Also, with this method we don't need to test the `min` and `max` values since `stepUp` and `stepDown` built-in functions do this internally. We do need to assign `value` to the input value because Svelte won't know that the value changed.
I also added a step test and updated the docs to add the step function.
For the margin I understand that …
> Fix `step` floating point issue in `NumberInput`

- src/Dropdown/Dropdown.svelte
Changes:
1. Dispatch `select` event only upon user interaction
* Currently, when using Dropdown with `on:select`, this event always dispatches on initial load, which is undesirable when I depend on that event for side-effects such as navigation.
* With these changes, it will only dispatch upon a user interaction. It's a similar dilemma to the one I had raised in #1497.
2. Allow arrow keys to open menu and highlight items, closes #1475 
* Matches interaction behaviours in the main [Carbon Dropdown Live Demo](https://carbondesignsystem.com/components/dropdown/usage/#live-demo) also described in [Dropdown Interactions](https://carbondesignsystem.com/components/dropdown/usage/#interactions).
* Does not fully address #1475 since the ask was to keep the Dropdown collapsed while selecting items, …
> fix(Dropdown): adjust select event and add arrow key interactions

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Popover.svx
- docs/src/pages/framed/Popover/WithButton.svelte
- src/Popover/Popover.svelte
- types/Popover/Popover.svelte.d.ts
When clicking on a sibling of the popover component, the `click:outside` event was not firing, because the sibling doesn't contain the popover's ref.
Also added a usage example with a button that binds the `open` prop, since it has a small behavior to think into account when clicking on the button.
> Fix popover click outside handler when clicking siblings

- README.md
In the projects' README:
```diff
- https://github.com/carbon-design-system/carbon/tree/master/packages/components
+ https://github.com/carbon-design-system/carbon/tree/main/packages/carbon-components
```
> docs: Fix readme project link

- docs/src/pages/index.svelte
it looks like `components` was renamed to `carbon-components`
> fix `carbon-components` link

- src/ComboBox/ComboBox.svelte
Fix an error related to zero items in combobox.
The error stack trace was:
```
ComboBox.svelte:135 Uncaught TypeError: Cannot read property 'disabled' of undefined
at change (ComboBox.svelte:135)
at HTMLInputElement.keydown_handler_1 (ComboBox.svelte:325)
at HTMLInputElement.<anonymous> (index.mjs:427)
```
> Fix zero items length bug

- src/MultiSelect/MultiSelect.svelte
Related #1545
A runtime error is thrown when focusing the input and using arrow keys of an empty `MultiSelect`.
```svelte
<MultiSelect items={[]} />
```
> fix(multi-select): avoid runtime error if `items` is empty

- src/Dropdown/Dropdown.svelte
Related #1545, #1577
A runtime error is thrown when focusing the input and using arrow keys of an empty `Dropdown`.
```svelte
<Dropdown items={[]} />
```
> fix(dropdown): avoid runtime error if `items` is empty

- docs/src/layouts/ComponentLayout.svelte
- docs/src/pages/components/ButtonSet.svx
- docs/src/pages/components/ClickableTile.svx
- docs/src/pages/components/ExpandableTile.svx
- docs/src/pages/components/InlineNotification.svx
- docs/src/pages/components/PasswordInput.svx
- docs/src/pages/components/RadioTile.svx
- docs/src/pages/components/SelectableTile.svx
- docs/src/pages/components/Tile.svx
- docs/src/pages/components/ToastNotification.svx
Currently, the "Source code" link at the top of a component docs navigates to a single component.
This is confusing since many components actually contain related components. One example is `ContentSwitcher`, which comprises of `ContentSwitcher` and `Switch`.
The expected behavior is that it should navigate to the folder (e.g., `src/ContentSwitcher`).
This PR does the following:
- link to folder if doc contains multiple components (e.g., Breadcrumbs, DataTable etc.)
- remove `source` from frontmatter (the metadata is already available in the Sveld auto-generated docs)
- additionally, the current implementation defaults to the [`page.title` for the source code path](https://github.com/carbon-design-system/carbon-components-svelte/compare/docs-source-code?expand=1#diff-d41ad8b8ac387e8248685f …
> docs: link source code to folder for multiple components

- package.json
- types/Button/Button.svelte.d.ts
- types/Button/ButtonSkeleton.svelte.d.ts
- types/Link/Link.svelte.d.ts
- types/Tile/ClickableTile.svelte.d.ts
- types/UIShell/Header.svelte.d.ts
- types/UIShell/HeaderActionLink.svelte.d.ts
- types/UIShell/HeaderNavItem.svelte.d.ts
- types/UIShell/HeaderNavMenu.svelte.d.ts
- types/UIShell/HeaderPanelLink.svelte.d.ts
- types/UIShell/SideNavLink.svelte.d.ts
- types/UIShell/SideNavMenuItem.svelte.d.ts
- types/UIShell/SkipToContent.svelte.d.ts
- yarn.lock
[`sveltekit:` attributes were removed](https://github.com/sveltejs/kit/blob/20ed756c822615564326e300b4e44d0a4060a214/packages/kit/CHANGELOG.md#100-next454) from SvelteKit almost half a year ago.
This upgrades `sveld` and removes the attributes from the types.
> chore(types)!: remove `sveltekit:` attributes from types

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/components/ComponentApi.svelte
- docs/src/pages/components/Select.svx
- src/Pagination/Pagination.svelte
- src/Select/Select.svelte
- tests/Pagination.test.svelte
- types/Pagination/Pagination.svelte.d.ts
- types/Select/Select.svelte.d.ts
Closes #1491 
Pagination
- Feature: dispatch `change` event from `<Pagination>` whenever user interacts with "previous" button, "next" button, page dropdown, or page size dropdown
Select
- Feature: forward `change` event from `<Select>`; necessary for Pagination to react to changes
- Fix (or breaking change?): dispatch `input` instead of `change`
Side note, it would be nice if the note I added to the `@event` JSDoc appeared on the rendered docs. Perhaps I can open a separate issue for that.
> Dispatch `change` event from `Pagination` and `Select`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/framed/PaginationNav/PaginationNavReactive.svelte
- src/PaginationNav/PaginationItem.svelte
- src/PaginationNav/PaginationNav.svelte
- src/PaginationNav/PaginationOverflow.svelte
- types/PaginationNav/PaginationNav.svelte.d.ts
Closes #1513 
Changes include:
- BREAKING CHANGE (PaginationNav): use 1-indexing
closes #1513 
- fix(PaginationNav): make 'change' event emit after user interaction instead of reactive event (explanation below)
I removed the event dispatcher in `<PaginationNav>` for `change` called in `afterUpdate` since it would dispatch on mount when it should only dispatch upon a user's interaction. When adding a change handler to `<PaginationNav>`, I would have to add a mount flag as a workaround. This treatment is similar to the one I provided in #1497.
With the changes in this PR I can remove my workaround in my change handler, allowing me to trust the `change` event would fire after user input only:
```diff
<script>
import {
PaginationNav
} from 'carbon-components-svelte'
- import { onMount } from …
```
> feat!: use 1-indexing for PaginationNav

- docs/src/components/ComponentApi.svelte
Svelte dispatches `event.detail` and not plural `event.details`.
> docs: change dispatched events label

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/TreeView.svx
- docs/src/pages/framed/TreeView/TreeViewIcons.svelte
- src/TreeView/TreeView.svelte
- src/TreeView/TreeViewNodeList.svelte
- types/TreeView/TreeView.svelte.d.ts
Fixes #1630
**Changes**
- breaking: remove `expanded` from the `TreeNode` interface
- fix: remove unused `expanded` prop from internal `TreeViewNodeList`
- docs: remove `expanded` as a property usage
> fix(tree-view)!: remove `expanded` property from `TreeNode` interface

- src/Dropdown/Dropdown.svelte
- src/ListBox/ListBoxMenuItem.svelte
Fixes #1595
Instead of registering the click on the `window` element, we can simply use the `blur` method on the `bx--list-box__field` button. This fix make it works in every situation even in `iframe`.
> Fix `Dropdown` click outside

- src/Dropdown/Dropdown.svelte
TIL `onDestroy` hook is also run during SSR, but returning a destruction function from `onMount` should do the trick.
> Fix for #1638

- src/Dropdown/Dropdown.svelte
Fixes #1645
The `select` event dispatched in `Dropdown` uses the previous `selectedItem` value. One solution is to use the `tick` method to wait for all state changes to be applied.
> fix(dropdown): dispatch correct `selectedItem` in `select` event

- docs/src/pages/components/Button.svx
Inspired by this [message from Discord](https://discord.com/channels/689212587170201628/756226301475684543/1070663479645720636).
> Hi — is there a disabled state for Icon only buttons?  I can see the disabled state for standard buttons and buttons with icon, but can't find the disabled behaviour for Icon only buttons.
I think it would be helpful to showcase what a disabled, icon-only button looks like.
This PR also changes "Disabled button" to "Disabled state" to be consistent with other docs pages.
---
> docs(button): add example of disabled, icon-only button

- docs/src/COMPONENT_API.json
- src/Checkbox/Checkbox.svelte
- src/FileUploader/Filename.svelte
- src/FluidForm/FluidForm.svelte
- tests/Checkbox.test.svelte
- tests/FluidForm.test.svelte
- types/Checkbox/Checkbox.svelte.d.ts
- types/FileUploader/Filename.svelte.d.ts
- types/FluidForm/FluidForm.svelte.d.ts
A user [reported in Discord](https://discord.com/channels/689212587170201628/1048235099583418448/1073080988957151343) that `$$restProps` types in `Checkbox` are missing from the type definitions.
https://github.com/carbon-design-system/carbon-components-svelte/issues/1621 proposes that we remove `$$restProps` for both clarity and performance reasons. This PR is a hotfix that addresses the existing bugs pre-v1.
The solution is to manually add a `@restProps` tag that sveld uses to generate types from.
> fix(types): add missing `$$restProps` for `Checkbox`, `Filename`, `FluidForm`

- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.svelte
Hello everyone,
This is my first time contributing so be gentle. This commit updates the TextInput and PasswordInput with an aria-describedby attribute for helper text. The components already include this for error and warning states.
This partially addresses #1633.
Best,
Carson
> Aria-describedby Attributes

- src/NumberInput/NumberInput.svelte
- src/TextInput/TextInput.svelte
Fixes #1664
This primarily fixes a bug where setting both `readonly` and `invalid` in `TextInput` would display two icons. The solution is to separate the `readonly` state from the `invalid/warn` states. This PR applies a similar logic to `NumberInput`, although icons will not clash in that component.
Furthermore, the `readonly` state will override the `error` state. That is, if both `readonly` and `error` are set, the `readonly` behavior will prevail.
The diff is best reviewed with [whitespace hidden](https://github.com/carbon-design-system/carbon-components-svelte/pull/1666/files?diff=split&w=1).
See a before/after:
```svelte
<TextInput
labelText="TextInput (readonly + invalid)"
value="Text"
readonly
invalid
invalidText="Invalid text"
/>
<FluidForm>
<TextInput
labelText="Fluid TextInput …
```
> fix: `readonly` should override `error` behavior in `TextInput`, `NumberInput`

- .github/ISSUE_TEMPLATE/config.yml
Add contact links when opening a new issue.
Reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> chore: provide contact links

- docs/src/pages/components/PasswordInput.svx
- src/TextInput/PasswordInput.svelte
- hides the whole helper text container when helper text is not provided (same behaviour as in TextInput) (screenshot 1)
- added an example in docs showing the helper text prop being used (screenshot 2)
fixes #1684
> fix(1684): hide helper text container in password input when not used

- src/TextInput/TextInput.svelte
`--warn` to `--warning`
Fixes #1687
> fix(text-input): correctly set input padding for warning state

- docs/src/global.css
- docs/src/layouts/ComponentLayout.svelte
This patch fixes #1649. The documentation layout is currently broken. The fix adds scroll behavior to:
- Code snippets
- Component props table
Like this the layout is no longer overstretched.
**Before**
**After**
This is a better fix than #1706 which is inspired by https://defensivecss.dev/tip/flexbox-min-content-size.
> docs: fix layout for smaller screens

- docs/package.json
- docs/yarn.lock
- package.json
- src/ContextMenu/ContextMenu.svelte
- src/OverflowMenu/OverflowMenu.svelte
- src/ProgressIndicator/ProgressStep.svelte
- src/Tabs/Tabs.svelte
- src/TreeView/TreeView.svelte
- src/TreeView/TreeViewNode.svelte
- src/TreeView/TreeViewNodeList.svelte
- src/UIShell/HeaderNav.svelte
- src/UIShell/HeaderNavMenu.svelte
- src/UIShell/HeaderSearch.svelte
- src/UIShell/SideNavMenu.svelte
- yarn.lock
Closes #1683, closes #1704
There is a slew of new a11y warnings in Svelte version >=3.57. This causes warnings to be emitted in the console when consuming this library.
Let's silence these warnings as I believe most if not all are false positives. We can resolve any actual warnings in follow-ups; let's not impede the developer experience for users using the latest Svelte version.
This is best reviewed by commit:
- upgrade `svelte` to 3.57
- ~~upgrade `svelte-check` (housekeeping)~~ reverted since it was causing an unrelated CI error
- silence new a11y warnings
To test this locally, you can run either of the following:
```sh
yarn svelte-check --workspace src
yarn build:lib
```
The expected result is that there should be no a11y warnings emitted to the console.
> chore(a11y): silence new a11y warnings from svelte@3.57

- .github/workflows/ci.yml
Currently, docs are [manually deployed](https://github.com/carbon-design-system/carbon-components-svelte/pull/1688#issuecomment-1480882478).
Let's automate the process. I added a repository secret containing the Deploy Hook URL. If hit, the documentation site will automatically redeploy the `master` branch.
This PR updates the GitHub workflow with a job that triggers the deploy hook URL only on `master`.
> ci: add job to automatically deploy docs

- README.md
The above-the-fold `README` is critical for first-time users. We should minimize the number of call-to-actions.
I feel that the Deploy-to-Render button is not relevant to the majority of users who simply want to use the library.
> docs: remove Deploy to Render CTA

- docs/src/pages/components/Slider.svx
The initial `Slider` examples are too minimal. We should encourage the use of `labelText` for accessibility. Also, even though the default `value` is `0`, exposing that attribute in the examples is a nice affordance.
> docs(slider): add label text, value

- docs/package.json
- docs/yarn.lock
- package.json
- src/ContentSwitcher/ContentSwitcher.svelte
- src/ListBox/ListBoxMenuItem.svelte
- src/ListBox/ListBoxSelection.svelte
- src/StructuredList/StructuredListRow.svelte
- src/Tooltip/Tooltip.svelte
- yarn.lock
Now that Svelte version [3.58](https://github.com/sveltejs/svelte/blob/e45a1e05a341e95d30ddb097bc144d8d6f5b3573/CHANGELOG.md#3580) has been released, a new slew of static a11y warnings needs to be addressed.
To repro the warnings, run the following at the root of this repository on `master`:
```sh
yarn add -D svelte; yarn build:lib;
```
This PR is best reviewed by commit because it actually contains a fix.
For each warning, I referenced the upstream Carbon React implementation. There are a couple of cases where the a11y warning can be ignored. There is one fix for `ListBoxMenuItem`. For the `tabIndex` -> `tabindex` capitalization, I don't think there is any user-facing change (Svelte Language Server does not seem to pick up `tabIndex`).
@theetrain If approved, should this PR *not* be …
> Resolve `a11y` warnings from Svelte version 3.58

- docs/src/pages/components/ExpandableTile.svx
- src/Tile/ExpandableTile.svelte
Fixes #1730
Currently, the `ExpandableTile` does not dynamically set the height of the above-the-fold content. In cases where the content is dynamic (a lot of text), this can result in clipped content.
This PR aims to fix this problem by using the Resize Observer to set the height of the tile, and adjust it if the height changes. It implements the [approach of the upstream React library](https://github.com/carbon-design-system/carbon/blob/97b6ca3e90fd9f95869792e4e6b27ea236cc7932/packages/react/src/components/Tile/Tile.js#L500-L509) almost verbatim.
In terms of behavior, this should not be a breaking change since you can still specify a custom tile height on the "above" and "below" slots.
**Changes**
- Fix `ExpandableTile` to use Resize Observer to set the tile max height
- Rework the docs …
> fix(expandable-tile): set tile height using resize observer

- src/DatePicker/DatePickerInput.svelte
Hides the helperText if the field is invalid or warn
> fix(date-picker): hide `helperText` if invalid or warning state

- src/Slider/Slider.svelte
PR contains small changes for slider to improve it's behavior on form submit.
1. Removed redundant input which causes double value submit and submit once when input is disabled.
Form data before: 
```jsonc
{
"FormData": [
{
"name": "basicSlider",
"value": "27"
},
{
"name": "basicSlider", // Data submitted twice here
"value": "27"
},
{
"name": "disableSlider", // It shouldn't submit disabled input with the form
"value": "30"
}
]
}
```
Form data after:
```jsonc
{
"FormData": [
{
"name": "basicSlider",
"value": "27"
}
]
}
```
Tested with both `hideTextInput` `true` and `false`.
2. Removed extra styling since it always sets input type to `hidden` when `hideTextInput` is `true`.
> fix(slider): `disabled` Slider should not submit a form

- package.json
- tests/TreeView.test.svelte
- yarn.lock
I previously attempted to upgrade the major version of `svelte-check` in https://github.com/carbon-design-system/carbon-components-svelte/pull/1703.
One reason for this upgrade is to better diagnose #1740 
In CI, `svelte-check` would [error out](https://github.com/carbon-design-system/carbon-components-svelte/actions/runs/5169738114/jobs/9312181625), as it would attempt to load `svelte.config.js` under `docs`. I was not able to reproduce this locally.
I [RTFM](https://en.wikipedia.org/wiki/RTFM) and updated the [command args](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check#args) to apply `no-tsconfig` and `ignore` to only type check Svelte files in `tests`. This seems to [pass CI](https://github.com/carbon-design-system/carbon-components-svelte/actions/runs/516 …
> chore(deps-dev): upgrade `svelte-check` to version 3

- src/Select/Select.svelte
Related #1757
Did a quick search for `helperText` usage and confirmed [upstream](https://github.com/carbon-design-system/carbon/blob/bb0e5d1f4d84ce71a3131892993b76a5a6805495/packages/react/src/components/Select/Select.tsx#L292) that `Select` should not show helper text if in the invalid or warn states. This is consistent with other inputs.
> fix(select): hide `helperText` if invalid or warning state

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/UIShell/Header.svelte
- types/UIShell/Header.svelte.d.ts
I've noticed that the ui shell has a little glitch during load in our app.
The `Â` disappearing after load but it causes a glitch.
The root cause is an `&nbsp;` character in the company text span.
Maybe somebody else faced with this glitch too, so I created a small improvement for that.
> feat(ui-shell): make `company` in `Header` slottable

- examples/rollup/package.json
- examples/rollup/yarn.lock
- examples/sveltekit/jsconfig.json
- examples/sveltekit/package.json
- examples/sveltekit/yarn.lock
- examples/vite/package.json
- examples/vite/vite.config.js
- examples/vite/yarn.lock
- examples/webpack/package.json
- examples/webpack/webpack.config.js
- examples/webpack/yarn.lock
Bumps dependencies in the example set-ups to the latest, but pre-svelte@4.
> chore(examples): bump deps

- src/FileUploader/FileUploader.svelte
Fixes #1775
In this case, the `labelTitle` and `labelDescription` are not accessible, so they can be conditionally rendered if truthy.
> fix(file-uploader): do not render empty element if `labelTitle`, `labelDescription` not provided

- package.json
- yarn.lock
Follow-up to #1773, which used `sveld@19` to regenerate TypeScript definitions for Svelte 4 support.
I'd used a locally symlinked version of `sveld`. This PR actually upgrades the dependency in the `package.json` so that running `yarn build:docs` produces the same result.
To test this, I ran "yarn build:docs"; as expected, no changes occurred.
> chore(deps-dev): upgrade sveld to v19

- src/CodeSnippet/CodeSnippet.svelte
- src/ContextMenu/ContextMenu.svelte
- src/DataTable/Toolbar.svelte
- src/ImageLoader/ImageLoader.svelte
- src/Notification/ToastNotification.svelte
- src/Popover/Popover.svelte
- src/SkeletonText/SkeletonText.svelte
- src/Slider/Slider.svelte
- src/Tabs/Tab.svelte
- src/Toggle/Toggle.svelte
- src/Tooltip/Tooltip.svelte
- src/TooltipIcon/TooltipIcon.svelte
- src/UIShell/Content.svelte
- src/UIShell/HeaderNavMenu.svelte
- src/UIShell/SideNav.svelte
- src/UIShell/SideNavMenu.svelte
Closes #1604
Refactors the components to use the `style:directive` where possible. Style directives cannot be used on components.
Using the style directive feels more readable, especially for multiple properties. It also removes the need to append `$$restProps.style` if `$$restProps` is spread to the same element.
```diff
- style="left: {x}px; top: {y}px; {$$restProps.style}"
+ style:left="{x}px"
+ style:top="{y}px"
```
> refactor: use style directive where applicable

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/InlineLoading/InlineLoading.svelte
- src/Loading/Loading.svelte
- types/InlineLoading/InlineLoading.svelte.d.ts
- types/Loading/Loading.svelte.d.ts
Fixes #1670
Revisited the `Loading` and `InlineLoading` components, using the upstream React implementation as the primary reference.
The `description` prop is already set on the `svg` title so the label is redundant. For `InlineLoading`, the icon title defaults to the `status` prop for the "error" and "completed" statuses.
- Change default `Loading` description text from "Active loading indicator" to "loading"
- Remove `id` prop from `Loading` since the label is removed
> fix(loading)!: remove redundant `description` label

- .github/workflows/ci.yml
Existing GitHub workflow actions should be upgraded to use v3.
See https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> ci(workflows): upgrade `actions/*` to v3

- docs/src/pages/components/FileUploader.svx
- src/FileUploader/FileUploaderButton.svelte
#1781 fixed the `kind` prop type, but `FileUploaderButton` actually does not use the `Button`. Rather, it's an `input` element, so the classes must be manually applied.
> feat(file-uploader-button): support `danger-tertiary`, `danger-ghost` button variants

- README.md
- docs/src/pages/index.svelte
`carbon-pictograms-svelte` [version 12.7.0](https://github.com/carbon-design-system/carbon-pictograms-svelte/releases/tag/v12.7.0) has 1,024 pictograms.
> docs(pictograms): update number of pictograms

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/UIShell/HeaderActionLink.svelte
- types/UIShell/HeaderActionLink.svelte.d.ts
As mentioned in #1796, this change forwards the `on:click` event from the wrapped anchor element for the `HeaderActionLink` component similar to other UIShell components that wrap anchor elements such as `HeaderPanelLink`, `SideNavLink`, or `SkipToContent`.
closes #1796
> feat(ui-shell): forward onclick event for HeaderActionLink

- src/SkeletonText/SkeletonText.svelte
Fixes #1793
This refactors `SkeletonText` to use a more declarative approach: the `Array.from` method in the markup instead of a for loop inside of a reactive statement.
> fix(skeleton-text): fix rows reactivity in `paragraph` variant

- CONTRIBUTING.md
- README.md
Nothing fancy, just stumbled upon these typos while working on another issue
> Fix old repo org name in README.md and CONTRIBUTING.md

- src/FileUploader/FileUploaderButton.svelte
This fixes the following error I got:
> InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string
which made my tests in vitest fail.
> fix(file-uploader-button): clear value by setting to `""` instead of `null`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ComboBox/ComboBox.svelte
- src/MultiSelect/MultiSelect.svelte
- src/RadioButton/RadioButton.svelte
- src/RadioButtonGroup/RadioButtonGroup.svelte
- src/UIShell/Header.svelte
- types/RadioButton/RadioButton.svelte.d.ts
- types/RadioButtonGroup/RadioButtonGroup.svelte.d.ts
- types/UIShell/Header.svelte.d.ts
`RadioButton` will receive properties from group.
Fixes #1036.
Not the prettiest code, though.
> fix(radio-button-group): add `name` and `required` props

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- types/DataTable/DataTable.svelte.d.ts
This will allow `display` usage to use the whole object for use with computed values, or when needing multiple fields to show more than one element (like "item actions" that might need more than one field, for instance).
> feat(data-table): pass `row` to `display` function

- docs/src/pages/components/RadioButton.svx
- docs/src/pages/framed/RadioButton/RadioButtonReactive.svelte
Uses the `name` prop in the examples.
Also updates the "Default" example to utilize the `legendText`, and move the example that visually hides it to be below it.
> docs(radio-button): use `name` in examples

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/RadioButton.svx
- docs/src/pages/components/RadioTile.svx
- docs/src/pages/framed/RadioTile/RadioTileReactive.svelte
- docs/src/pages/framed/RadioTile/RadioTileReactiveOneWay.svelte
- src/Tile/RadioTile.svelte
- src/Tile/TileGroup.svelte
- tests/RadioTile.test.svelte
- types/Tile/RadioTile.svelte.d.ts
- types/Tile/TileGroup.svelte.d.ts
Similar to #1037, fixes `TileGroup` to forward `name` / `required` props to its group of inputs.
> fix(tile-group): add `name` and `required` props

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/RadioButtonGroup/RadioButtonGroup.svelte
- src/Tile/TileGroup.svelte
- tests/RadioButton.test.svelte
- tests/RadioTile.test.svelte
- types/RadioButtonGroup/RadioButtonGroup.svelte.d.ts
- types/Tile/TileGroup.svelte.d.ts
Strongly type the `event.detail` as `string` for `RadioButtonGroup` and `TileGroup`. Currently, it defaults to `any` since the type is not explicitly annotated.
```svelte
<RadioButtonGroup
legendText="Storage tier (disk)"
selected="standard"
on:change="{(e) => {
console.log(e.detail); // string
}}"
/>
```
> fix(radio-button-group): strongly type dispatched change/select events

- src/MultiSelect/MultiSelect.svelte
Here I have a fix for issue #1831. I am unable to reproduce the issue (reproducible with `master` branch [here](https://svelte.dev/repl/63e6f961f6b1483fab1eac28da08c011?version=4.2.2)) after applying this patch.
If there is a better way to handle initial state set from `onMount()`, I would love to implement a better solution. Please let me know.
> fix(multi-select): reset `selectedIds` when clearing selection

- CHANGELOG.md
- README.md
- carbon.yml
https://svelte.carbondesignsystem.com/ is the new domain for the docs site.
This URL is more concise, professional, and consistent with other Carbon libraries (e.g., [react](https://react.carbondesignsystem.com)).
https://carbon-components-svelte.onrender.com/ will continue to work.
> chore: update docs site link with new URL

- docs/src/pages/components/Form.svx
Closes #1813
`value` is not a valid prop on `Select`. This is a typo as it should be the `selected` prop. In this case, removing it still works because the value of the first `SelectItem` is used as the default selected value.
> docs(form): fix typo in "Form" example

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Select/SelectItem.svelte
- tests/Select.test.svelte
- types/Select/SelectItem.svelte.d.ts
Fixes #1839 
`SelectItem` is missing type definitions for the `class` and `style` props. Even though this defines props on the component, this is not a breaking change as the behavior has always been supported.
> fix(select-item): export `class` and `style` props

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/TreeView.svx
- docs/src/pages/framed/TreeView/TreeViewSlot.svelte
- src/TreeView/TreeView.svelte
- src/TreeView/TreeViewNode.svelte
- src/TreeView/TreeViewNodeList.svelte
- tests/TreeView.test.svelte
- types/TreeView/TreeView.svelte.d.ts
Closes #1660
Currently, the `TreeView` will only render the `node.text` (string). It could be useful to override the display value and/or provide custom styles.
This PR makes the `node` slottable.
The most basic usage is to access the metadata via the `let:node` directive and override the default slot.
```svelte
<TreeView children="{children}" let:node>
{node.id}
{node.text}
{node.expanded}
{node.selected}
{node.disabled}
{node.leaf} // True if the node is a leaf (node does not have children)
</TreeView>
```
The `node` metadata can be used to conditionally apply logic/styles:
```svelte
<TreeView children="{children}" let:node>
<span
style:font-weight="{node.selected ? 600 : "inherit"}"
style:opacity="{node.selected ? 1 : 0.4}"
>
{node.text} ({node.id})
</span>
</TreeView>
```
The code …
> feat(tree-view): make `node` slottable

- CONTRIBUTING.md
- package.json
This library is now published to [NPM with provenance](https://docs.npmjs.com/generating-provenance-statements) via a [GitHub workflow](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/.github/workflows/release.yml). The workflow is triggered when pushing a tag that starts with `v` to the remote.
I've revised the contributing instructions for maintainers to reflect this new practice.
It should make running `yarn release` faster as it's no longer necessary to run `yarn build:lib` locally.
> docs: update CONTRIBUTING.md

- docs/src/layouts/ComponentLayout.svelte
- docs/src/pages/index.svelte
Encourage search engines to prefer https://svelte.carbondesignsystem.com.
> docs: add `link rel="canonical"` to pages

- src/PaginationNav/PaginationItem.svelte
When `PaginationNav` is used inside a `form`, the form will be submitted when clicking a page button.
This is because the `button` lacks an explicit `type` attribute. If contained within a form, the default type is "submit."
```html
<form>
<PaginationNav />
</form>
```
> fix(pagination-nav): set `button type="button"` to prevent form submission

- src/UIShell/HeaderSearch.svelte
The search and clear button icons in the `UIShell` `HeaderSearch` component are currently misaligned. They should be vertically centered.
> fix(header-search): vertically center button icons

- src/UIShell/HeaderSearch.svelte
Pressing "Escape" in `HeaderSearch` should reset the search query without deactivating the search bar.
> fix(header-search): "Escape" should clear search query

- docs/.gitignore
- docs/package.json
- docs/scripts/index-docs.js
- docs/src/pages/_layout.svelte
- docs/yarn.lock
This PR aims to improve the docs UX by adding client-side, full-text search using [minisearch](https://www.npmjs.com/package/minisearch).
The search index is extremely basic; it only searches the component name and example heading. More weight is given to the heading. A maximum of 10 results are shown.
For example: searching "bat" should yield `DataTable – batch selection`.
**Future Work**
- Example description text should also be indexed.
---
> docs: implement rudimentary full-text search

- docs/src/pages/_layout.svelte
Reworks #1852
The keyboard shortcut behavior should trigger on keydown, not keyup. This is most noticeable when holding down CMD+K and nothing happens. Pressing CMD+K should immediately focus the search bar.
> docs: rework keyboard shortcuts to focus search bar

- src/UIShell/HeaderSearch.svelte
Fast-follow to [#1853](https://github.com/carbon-design-system/carbon-components-svelte/issues/1853).
"Escape" should deactivate the search input if no query is present. However, after deactivating, the input retains focus. It should also be blurred.
> fix(header-search): blur input when deactivating

- src/UIShell/HeaderSearch.svelte
Fast-follow to [#1855](https://github.com/carbon-design-system/carbon-components-svelte/issues/1855)
#1855 correctly blurred the input on "Escape." However, if programmatically de-activating the search bar (e.g., setting `active` to `false` or selecting an option), the input remains focused.
For example, the following bug occurs:
1. Activate search bar.
2. Select an option in the menu.
3. The input is "visually" collapsed but the element retains focus.
A more holistic approach would be to use a reactive statement and blur the input when `active` becomes `false`. This is similar to how the input is focused when `active` is `true`.
> fix(header-search): blur input when `active` is false

- package.json
> chore: add `exports` field to package.json

- package.json
Fast-follow to #1864, Fixes #1863
Types must also be specified in the `exports` map.
> fix(package): include types in exports map

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/RadioButton/RadioButton.svelte
- src/RadioButtonGroup/RadioButtonGroup.svelte
- types/RadioButton/RadioButton.svelte.d.ts
- types/RadioButtonGroup/RadioButtonGroup.svelte.d.ts
Fixes #1867 
Currently, the RadioButton `value` is typed to only allow strings. This was inadvertence since the type definitions for the library are auto-generated. If no explicit type is annotated, the type generator will use its default type.
This PR fixes loosens the `value` type to allow strings and numbers. I'd prefer not to make this an `any` type as I believe there is value in strictness.
Without this change, the following code would run fine but produce type errors.
```svelte
<script lang="ts">
import { RadioButtonGroup, RadioButton } from "carbon-components-svelte";
const plans = [1, 2, 3];
let plan = plans[0];
$: console.log("Selected plan", plan, typeof plan);
</script>
<RadioButtonGroup
bind:selected={plan}
on:change={(e) => {
const selected = e.detail; …
```
> fix(radio-button): allow `value` type to be a number

- docs/index.html
- docs/src/layouts/ComponentLayout.svelte
- docs/src/pages/_layout.svelte
- docs/src/pages/framed/_reset.svelte
A couple of minor UX improvements regarding the theme:
1. Synchronously initialize the persisted theme to avoid a flash-of-unstyled-theme (FOUT).
2. Set `:root { color-scheme: 'light' | 'dark' }` based on the selected theme. One nicety is that this can style the browser scrollbar based on the scheme. For example, a dark Carbon theme should suggest to the browser to apply dark-themed scrollbars (see screenshot).
A small refactor includes using `URLSearchParams` to more reliably parse the `theme` key/value from the URL.
---
> style(docs): `color-scheme` reflects theme

- .github/workflows/release.yml
One for stable and one for next tags.
- conditionally run a `publish` job that sets `--tag next` when the Git tag includes the string `-next`; otherwise use `latest` by default
> build: set up separate publish jobs

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ListBox/ListBoxSelection.svelte
- src/Slider/Slider.svelte
- src/StructuredList/StructuredList.svelte
- src/Tabs/Tabs.svelte
- tests/Slider.test.svelte
- tests/StructuredList.test.svelte
- tests/Tabs.test.svelte
- types/ListBox/ListBoxSelection.svelte.d.ts
- types/Slider/Slider.svelte.d.ts
- types/StructuredList/StructuredList.svelte.d.ts
- types/Tabs/Tabs.svelte.d.ts
Some dispatched events do not have an explicit type annotation, and thus default to `CustomEvent<any>`.
This PR enhances the DX by explicitly annotating the type.
```svelte
<Slider
on:change="{(e) => {
console.log(e.detail); // number
}}"
/>
```
> fix(types): improve `e.detail` type for dispatched events

- src/ContextMenu/ContextMenu.svelte
Fixes #1909
Right clicking a non-`target` should allow the default `contextmenu` event.
> fix(context-menu): prevent `on:contextmenu` default behavior only when opening menu

- docs/src/pages/components/CodeSnippet.svx
Adds an example on customizing the show more/less button text.
> docs(code-snippet): add "Custom show more/less text" example

- docs/src/pages/components/ImageLoader.svx
- docs/src/pages/framed/ImageLoader/DynamicImageLoader.svelte
- src/ImageLoader/ImageLoader.svelte
Fixes https://github.com/carbon-design-system/carbon-components-svelte/issues/1677
This one was interesting. The `src` prop was indeed correct, but the DOM was not updated to reflect this. The workaround here is to use a `key` block to recreate the element if `src` changes.
> fix(image-loader): updated `src` should update the image 

- docs/src/pages/components/ToastNotification.svx
- docs/src/pages/framed/ToastNotification/ToastNotificationTimeout.svelte
- src/Notification/ToastNotification.svelte
Does several things:
**Docs**
- Adds an example using the autoclose `timeout` prop.
**Fixes #1914**
- Fixes `ToastNotification` to start the timer in a reactive statement instead of `onMount`. This means if the `timeout` prop is set or changed after component initialization, the timeout should work as expected.
- Fixes `ToastNotifcation` to reset the timer if the close button is clicked.
---
https://github.com/carbon-design-system/carbon-components-svelte/assets/10718366/eacea953-d93d-4018-bd9f-796b547839c0
> fix(toast-notification): clear `autoclose` timeout correctly 

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ContentSwitcher/Switch.svelte
- src/Link/Link.svelte
- src/ProgressIndicator/ProgressIndicator.svelte
- src/Search/Search.svelte
- types/Link/Link.svelte.d.ts
Review by commit – rebase merge.
https://github.com/carbon-design-system/carbon-components-svelte/discussions/1908
There are several low-lift revisions that make this library interoperable with Svelte 5.
- [fix: avoid using reserved $ for Svelte 5 compat](https://github.com/carbon-design-system/carbon-components-svelte/commit/e5ea940da9643aa309cb5b3ea70b089c7dd1936a)
- [fix(link)!: do not render p for disabled link](https://github.com/carbon-design-system/carbon-components-svelte/commit/0b7aca13341d71062699c77a969626cd8e9ec62d) (Closes #1924)
- [fix(search): hoist ignore a11y autofocus comment](https://github.com/carbon-design-system/carbon-components-svelte/commit/6e9cd6e6af0d040554ac275cefa1689df4eacb25)
> Make library interoperable with Svelte 5

- package.json
Fixes #1925
Importing using the explicit `.*js` extension will throw an error as these are not included in the package exports map. Normally, this would be acceptable if it's not part of the API.
However, the `optimizeImports` Carbon preprocessor rewrites certain imports (e.g., `breakpoints`) to the source `*.js` file.
```sh
Internal server error: Failed to resolve import "carbon-components-svelte/src/Breakpoint/breakpoints.js" from "src/App.svelte".
```
> fix(exports): resolve imports with explicit *.js extension

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/framed/UIShell/HeaderUtilities.svelte
- src/Button/Button.svelte
- src/UIShell/HeaderGlobalAction.svelte
- tests/HeaderUtilities.test.svelte
- types/Button/Button.svelte.d.ts
- types/UIShell/HeaderGlobalAction.svelte.d.ts
Breaking change : Use Button component in HeaderGlobalAction
** Issue: [#1893](https://github.com/carbon-design-system/carbon-components-svelte/issues/1893)
** Edit: an example of updated HeaderGlobalAction
> feat(ui-shell): support button tooltip in `HeaderGlobalAction`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/UIShell/HeaderAction.svelte
- src/UIShell/HeaderActionLink.svelte
- src/UIShell/HeaderPanelDivider.svelte
- src/UIShell/HeaderSearch.svelte
I'm currently working on rewriting the Carbon CSS optimize plugin: https://github.com/carbon-design-system/carbon-preprocess-svelte/pull/54
Here's one example of how much unused Carbon CSS can be eliminated (using [#header-with-app-switcher](https://svelte.carbondesignsystem.com/components/UIShell#header-with-app-switcher)).
```sh
Optimized assets/index-DekzpXBw.css
Before: 606.68 kB
After:   84.58 kB (-86.06%)
```
However, the current approach relies on explicit `.bx--` selectors to avoid false positives.
This breaking change requires existing, custom styles to:
- Follow the `.bx--` prefixing pattern
- Be globally scoped (otherwise, the compiler will generate a hashed selector name)
> refactor!: use `:global()` for custom styles

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Accordion.svx
- src/Accordion/Accordion.svelte
- src/Accordion/AccordionItem.svelte
- src/Accordion/AccordionSkeleton.svelte
- tests/Accordion.test.svelte
- types/Accordion/Accordion.svelte.d.ts
- types/Accordion/AccordionItem.svelte.d.ts
- types/Accordion/AccordionSkeleton.svelte.d.ts
Supports #1629
This aligns `Accordion` with the v11 styles and API.
- Remove `xl` size prop. Valid sizes are `sm | md | lg`. Default is `md`.
- Remove `skeleton` prop. `AccordionSkeleton` is used separately.
- Remove `$$restProps` and unnecessary forwarded events.
- `AccordionSkeleton` is no longer `open` by default (flip the boolean). This more closely aligns with the `AccordionItem` behavior.
**New Features**
- Add a `flush` prop to flush align accordion item text.
**Fixes**
- Apply the `layer-size` class to fix sizing.
- Add an `aria-controls` id for the expando button.
**Clean-up**
- Fix JSDoc comment formatting, adjust copy where appropriate.
- Use shorthand for context instead of manually subscribing/unsubscribing.
- Improve the documentation by adding more …
> feat(accordion)!: integrate `Accordion` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/AspectRatio.svx
- src/AspectRatio/AspectRatio.svelte
- types/AspectRatio/AspectRatio.svelte.d.ts
Closes #1948
- Integrates `AspectRatio` with v11. No changes, really. Marking this as breaking, since `aspect-ratio-object` was removed in a previous commit.
- Feature: support a custom tag using `svelte:element`
> feat(aspect-ratio)!: integration with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Breadcrumb.svx
- src/Breadcrumb/Breadcrumb.svelte
- src/Breadcrumb/BreadcrumbItem.svelte
- src/Breadcrumb/BreadcrumbSkeleton.svelte
- tests/Breadcrumb.test.svelte
- types/Breadcrumb/Breadcrumb.svelte.d.ts
- types/Breadcrumb/BreadcrumbItem.svelte.d.ts
- types/Breadcrumb/BreadcrumbSkeleton.svelte.d.ts
- `Breadcrumb` skeleton prop removed. Use `BreadcrumbSkeleton` directly.
- `Breadcrumb` forwarded events removed from `nav` (a11y warning resolved)
- `BreadcrumbSkeleton` forwarded events removed (a11y warning resolved)
**Fixes**
-` BreadcrumbItem`: correctly type `aria-attributes`
- `BreadcrumbItem` forwarded events should be forwarded to `Link`, not `li`
- `BreadcrumbItem` `aria-current` should be unset on `li` since it is passed to `Link`
**Docs**
- Add example for a custom slot
- Document more skeleton states
> feat(breadcrumb)!: integrate `Breadcrumb` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Breakpoint.svx
- src/Breakpoint/Breakpoint.svelte
- src/Breakpoint/breakpointObserver.js
- src/Breakpoint/breakpoints.js
- types/Breakpoint/Breakpoint.svelte.d.ts
No breaking changes (this is a bespoke component implemented for Carbon Svelte that does not rely on any upstream styles).
> feat(breakpoint): integrate `Breakpoint` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Truncate/Truncate.svelte
- src/Truncate/truncate.d.ts
- src/Truncate/truncate.js
- tests/Truncate.test.svelte
- types/Truncate/Truncate.svelte.d.ts
- types/Truncate/truncate.d.ts
- No breaking changes.
- Allows tag customization.
- Uses the official `Action` type from `svelte/action` to type the action.
> feat(truncate): integrate `Truncate` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ListItem/ListItem.svelte
- src/OrderedList/OrderedList.svelte
- src/UnorderedList/UnorderedList.svelte
- tests/OrderedList.test.svelte
- tests/UnorderedList.test.svelte
- types/ListItem/ListItem.svelte.d.ts
- types/OrderedList/OrderedList.svelte.d.ts
- types/UnorderedList/UnorderedList.svelte.d.ts
Does a pass at the list components.
- Removes forwarding events to non-interactive `ol`, `ul`, and `li` elements (resolving a11y warnings)
> feat(list)!: integrate `OrderedList`, `UnorderedList` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/Heading.svx
- src/Heading/Heading.svelte
- src/Heading/Section.svelte
- src/Heading/index.js
- src/index.js
- tests/Heading.test.svelte
- types/Heading/Heading.svelte.d.ts
- types/Heading/Section.svelte.d.ts
- types/index.d.ts
v11 has a new `Heading` and `Section` component.
It automatically sets the heading level based on the nesting of sections.
```svelte
<Section>
<Heading>Heading 1</Heading>
<Section>
<Heading>Heading 2</Heading>
<Section>
<Heading>Heading 3</Heading>
<Section>
<Heading>Heading 4</Heading>
<Section>
<Heading>Heading 5</Heading>
<Section>
<Heading>Heading 6</Heading>
<Section>
<Heading>Capped at Heading 6</Heading>
</Section>
</Section>
</Section>
</Section>
</Section>
</Section>
<Section>
<Heading>Heading 2</Heading>
</Section>
</Section>
```
> feat(heading): add `Heading` and `Section` components

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/RecursiveList/RecursiveList.svelte
- tests/RecursiveList.test.svelte
- types/RecursiveList/RecursiveList.svelte.d.ts
No breaking changes.
**Features**
- TypeScript improvement: allow `children` to be typed as a read-only array.
```svelte
<script lang="ts">
import { RecursiveList } from "carbon-components-svelte";
const children = [
...
] as const;
</script>
<RecursiveList type="ordered" children="{children}" />
```
> feat(recursive-list): integrate `RecursiveList` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/global.css
- docs/src/pages/components/Stack.svx
- src/Stack/Stack.svelte
- src/Stack/index.js
- src/index.js
- tests/Stack.test.svelte
- types/Stack/Stack.svelte.d.ts
- types/index.d.ts
Related #1384
Adds the `Stack` component.
`Stack` is a utility component that can be used to create a stack of elements with a consistent gap between them. It supports both vertical and horizontal orientations.
It uses layout tokens from the Carbon Design System to define the gap between elements. The default gap is `1`, which is equivalent to `0.125rem` (`2px`).
The `gap` scale can be set from `1` to `13`.
```svelte
<Stack gap={2}>
<p>Item 1</p>
<p>Item 2</p>
<p>Item 3</p>
</Stack>
```
> feat(stack): add `Stack` component

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/StructuredList.svx
- docs/src/pages/framed/StructuredList/ProgrammaticStructuredList.svelte
- src/StructuredList/StructuredList.svelte
- src/StructuredList/StructuredListBody.svelte
- src/StructuredList/StructuredListCell.svelte
- src/StructuredList/StructuredListHead.svelte
- src/StructuredList/StructuredListInput.svelte
- src/StructuredList/StructuredListRow.svelte
- src/StructuredList/StructuredListSkeleton.svelte
- tests/StructuredList.test.svelte
- types/StructuredList/StructuredList.svelte.d.ts
- types/StructuredList/StructuredListBody.svelte.d.ts
- types/StructuredList/StructuredListCell.svelte.d.ts
- types/StructuredList/StructuredListHead.svelte.d.ts
- types/StructuredList/StructuredListInput.svelte.d.ts
- types/StructuredList/StructuredListRow.svelte.d.ts
- types/StructuredList/StructuredListSkeleton.svelte.d.ts
Re-works `StructuredList`. Even though v11 looks the same, this takes the opportunity to make `StructuredList` usage a bit more ergonomic.
- Remove unnecessary forwarded events (a11y warnings)
- Remove `head` props as context can be used to determine the header row
- StructuredListRow: allow tag to be customized, support `selected` state
- StructuredListInput: fold icon into input, allow icon to be customizable
- Skeleton: rename `rows` to `count` for consistency
> feat(structured-list)!: integration `StructuredList` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/components/TextArea.svx
- src/TextArea/TextArea.svelte
- src/TextArea/TextAreaSkeleton.svelte
- types/TextArea/TextArea.svelte.d.ts
- types/TextArea/TextAreaSkeleton.svelte.d.ts
Does a pass at integrating `TextArea` with v11. To scope down, will support fluid form in a separate PR.
Closes #1668, closes #1661
Will address #978, #1136.
- Support warn state
- Support readonly state
- Make `invalidText` slottable
- Add `counterMode`
- Disable `resize` if `cols` is a number
> feat(text-area)!: integrate `TextArea` with v11

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- src/DataTable/DataTableTypes.d.ts
- tests/DataTableAppendColumns.test.svelte
- types/DataTable/DataTable.svelte.d.ts
- types/DataTable/DataTableTypes.d.ts
Adjustments for #1954.
- Make key in `cell` slot prop less strict to prevent type errors in markup.
Type errors are hard to deal with in Svelte 3/4, this could be reverted again in Svelte 5.
- No longer exclude `id` from possible keys.
- Resolve property path names up to one level deep for header keys.
Limited to one level for now as combinatorial explosion can make type resolution quite heavy.
For deeper levels a custom helper function could be used or, as with synthetic keys, `as any` can be used to ignore the type error.
I added some line breaks for readability in the source, these seem to be added to the `COMPONENT_API.json` but the docs are not visibly affected.
The types in `DataTableTypes.d.ts` are currently not directly accessible via the docs. (Also, the name and location of that …
> Tweaks to DataTable generics

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Search/Search.svelte
- src/Search/SearchSkeleton.svelte
- tests/Search.test.svelte
- types/Search/Search.svelte.d.ts
- types/Search/SearchSkeleton.svelte.d.ts
**Breaking Changes:**
- `Search`: de-couple skeleton variant from `Search`
- `SearchSkeleton`: remove forwarded events (resolves a11y) and rest props
**Fixes:**
- `Search`: removes an unused reference (`searchRef`)
- `Search`: only pass a function to event listener if `expandable` is true.
> feat(search)!: integrate `Search` with v11

- README.md
- docs/src/pages/index.svelte
[carbon-icons-svelte@12.8.0](https://github.com/carbon-design-system/carbon-icons-svelte/releases/tag/v12.8.0) now has 2,365 icons total.
> docs: update number of icons

- README.md
I don't understand why you would ever load it from a CDN. The setup instructions already had you install `carbon-components-svelte`, so if it's available from local disk, why not just use it? It's the same or less code to use the one from npm. Providing multiple ways to do things just complicates the setup instructions
> docs: simplify setup instructions by removing CDN section

- src/Search/Search.svelte
Fixes #1981
Changed the value checks to also consider `null`/`undefined` since it's typed as `any`.
> fix(search): collapse expandable search if value is falsy

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/TextArea/TextArea.svelte
- types/TextArea/TextArea.svelte.d.ts
Allow null as value attribute on TextArea as on TextInput
> fix(text-area): type `value` prop as nullable

- src/UIShell/HeaderAction.svelte
This PR hot fixes a usability issue – if the `HeaderAction` has vertical overflow, the `overflow: hidden` rule is not overridden. Note that this should ideally be fixed upstream: https://github.com/carbon-design-system/carbon/pull/17160
In the meantime, the fix for Carbon Svelte ensures that the content is vertically scrollable (if necessary).
> fix(header-action): allow vertical scroll when expanded

- package-lock.json
- package.json
Bumps `sveld` from v0.20.0 to v0.20.2, which has 37 fewer transitive dependencies.
See https://github.com/carbon-design-system/sveld/issues/131#issuecomment-2349274386
> chore(deps-dev): upgrade `sveld` to 0.20.2

- telemetry.yml
The PR opened a few days ago updating the endpoint URL had the wrong one -- this PR fixes that.
> chore(telemetry): updated URL

- src/Breakpoint/Breakpoint.svelte
- src/OverflowMenu/OverflowMenu.svelte
- src/TextInput/PasswordInput.svelte
- src/TextInput/TextInput.svelte
Fixes #2016.
When using this library with Svelte 5, I'm seeing development warnings in the console.
```sh
11:18:07 [vite] ✨ new dependencies optimized: svelte/internal/client
11:18:07 [vite] ✨ optimized dependencies changed. reloading
11:18:07 AM [vite-plugin-svelte] node_modules/carbon-components-svelte/src/Breakpoint/Breakpoint.svelte:43:48 Properties of objects and arrays are not reactive unless in runes mode. Changes to this property will not cause the reactive statement to update
11:18:08 AM [vite-plugin-svelte] node_modules/carbon-components-svelte/src/OverflowMenu/OverflowMenu.svelte:195:2 The value of 'aria-haspopup' must be exactly one of "false", "true", "menu", "listbox", "tree", "grid" or "dialog"
11:18:08 AM [vite-plugin-svelte] …
```
> fix: address Svelte 5 warnings

- README.md
- docs/src/pages/index.svelte
https://github.com/carbon-design-system/carbon-icons-svelte/releases/tag/v12.13.0
The latest `@carbon/icons@11.52` brings the total `carbon-icons-svelte` to 2421. Update the docs to reflect this.
> docs: update number of `carbon-icons-svelte` to 2,400+

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/ComboBox/ComboBox.svelte
- tests/ComboBox.test.svelte
- types/ComboBox/ComboBox.svelte.d.ts
In `ComboBox`, on:clear is forwarded to `ListBoxSelection`, and is a dispatched event.
This event must be explicitly typed in `ComboBox`.
> fix(combo-box): fix types for `on:clear`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/ToolbarSearch.svelte
- types/DataTable/ToolbarSearch.svelte.d.ts
Related #2020
`on:clear` is forwarded to `Search`. It needs to be explicitly annotated to pick up the correct type. Otherwise, it defaults to assuming it's a native event.
> fix(toolbar-search): fix types for `on:clear`

- package-lock.json
- package.json
- types/ComboBox/ComboBox.svelte.d.ts
- types/DataTable/ToolbarSearch.svelte.d.ts
- types/DatePicker/DatePickerInput.svelte.d.ts
- types/MultiSelect/MultiSelect.svelte.d.ts
- types/NumberInput/NumberInput.svelte.d.ts
- types/Search/Search.svelte.d.ts
- types/TextArea/TextArea.svelte.d.ts
- types/TextInput/PasswordInput.svelte.d.ts
- types/TextInput/TextInput.svelte.d.ts
- types/TimePicker/TimePicker.svelte.d.ts
- types/UIShell/HeaderSearch.svelte.d.ts
Upgrades Sveld to v0.20.3 to fix the generated types for the `paste` event.
TypeScript lib.dom.d.ts now includes cut/copy/paste on the `WindowEventMap` interface.
> fix(types): fix types for `on:paste` event

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- types/DataTable/DataTable.svelte.d.ts
There are still references to the old `Value` in DataTable JSDocs. TypeScript shows these as errors. This fails open, as the `DataTableValue` is `any` anyway.
> fix(data-table): fix `DataTableValue` types in `DataTable`

- README.md
- docs/src/pages/components/CodeSnippet.svx
- docs/src/pages/framed/CodeSnippet/CodeSnippetOverride.svelte
- docs/src/pages/index.svelte
- tests/CodeSnippet.test.svelte
- tests/CopyableCodeSnippet.test.svelte
For consistency with [carbon-icons-svelte](https://github.com/carbon-design-system/carbon-icons-svelte) and [carbon-pictograms-svelte](https://github.com/carbon-design-system/carbon-icons-svelte):
- Drop the `-D` flag from install commands (this library should be a dependency, not a `devDependency`). It's also cleaner.
- Add Bun an install command
- Re-order command so that `npm --> pnpm --> yarn --> bun`
- Style-wise, update the docs home page to use `<Tabs autoWidth />` since the added tab can look a bit crowded.
> Update install commands in docs

- .github/workflows/checks.yml
- package.json
The generated TypeScript definitions need to be periodically validated.
A flurry of recent PRs have aimed to correct type issues:
- #2019
- #2020
- #2022
- #2023
- #2027
Additionally, TypeScript was upgraded to the latest minor version in #2024.
This PR adds a script to type check generated definitions for the library to ensure basic workability and guard against regressions.
The current check should expectedly fail as there are still TypeScript errors that I'm working through.
> ci: add script to test generated types

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- docs/src/pages/framed/RecursiveList/RecursiveList.svelte
- docs/src/pages/framed/RecursiveList/RecursiveListOrdered.svelte
- docs/src/pages/framed/RecursiveList/RecursiveListOrderedNative.svelte
- src/RecursiveList/RecursiveList.svelte
- tests/RecursiveList.test.svelte
- types/RecursiveList/RecursiveList.svelte.d.ts
Fixes [#2013](https://github.com/carbon-design-system/carbon-components-svelte/issues/2013)
> feat(recursive-list)!: rename `children` prop to `nodes` for Svelte 5 compatibility

- src/MultiSelect/MultiSelect.svelte
Fixes #1986
Here’s an attempt to fix the issues in the `MultiSelect` component that caused incompatibility with Svelte 5 by creating infinite loops (https://github.com/carbon-design-system/carbon-components-svelte/issues/1986). It seems like the core issue was the circular dependency between the `items` and `sortedItems` variables:
`items` assigned to`sortedItems` in an `afterUpdate` block:
https://github.com/carbon-design-system/carbon-components-svelte/blob/ac38e9d3531af85b413ba9919fdc70bca62c2002/src/MultiSelect/MultiSelect.svelte#L261
`sortedItems` depends on `items`:
```svelte
$: sortedItems = items.map((item) => ({
...item,
checked: selectedIds.includes(item.id),
}));
```
The commit removes the `sortedItems` variable, which served an intermediate role, and changes are made to …
> fix(multi-select): avoid cyclic dependency for Svelte 5 compatibility

- src/DataTable/DataTable.svelte
- src/DataTable/ToolbarSearch.svelte
Fixes #2033 
Svelte 5 exposes a bug when using `DataTable` and `ToolbarSearch`. Initial filtering might work, but original rows are not reset.
The root cause is a reset loop caused by `ToolbarSearch`. It currently reads and writes `$tableRows`, which is the source of truth used by `DataTable`.
One of the constraints is for `filteredIds` to be bindable to `ToolbarSearch` (but not two-way reactivity). Beyond that, `ToolbarSearch` should not need to read the source `rows` or manipulate them directly.
The solution is to move the filtering logic to the parent `DataTable`. A copy of the original rows is set (unless `rows` changes). Filtering will then filter on a subset of the copy without modifying the source.
> fix(data-table): move `ToolbarSearch` filtering to `DataTable` for Svelte 5 compatibility

- package-lock.json
- package.json
- scripts/build-docs.js
Replace `glob` used in a build script with a lighter weight alternative (~26 deps down to 2 deps).
Unfortunately, other packages still have `glob` as a transitive, but this can be resolved once they are removed (e.g., #1995).
> build(scripts): replace `glob` with `tinyglobby`

- docs/index.html
- docs/src/pages/_layout.svelte
Moves the script to the base app layout, meaning it should not be loaded or shown in isolated layouts (like `/framed/*` used for `iframe` examples).
Another small performance change is to use `defer` instead of `async` for script loading.
- async: load script asynchronously but execute once it's downloaded (regardless of HTML parsing)
- defer: load script asynchronously AND defer execution until HTML is parsed
> docs: move IBM analytics script to `_layout.svelte`

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/Checkbox/Checkbox.svelte
Fixes #2039
In Svelte 5, `<input indeterminate={indeterminate} />` does not update the value. Binding the variable seems to work.
Tested the following with Svelte 4 and Svelte 5. The difference now is that `indeterminate` is reactive (two-way).
```svelte
<script>
import { Checkbox } from "carbon-components-svelte";
let indeterminate = true;
</script>
<Checkbox labelText="Label text" bind:indeterminate />
<p>Indeterminate: {indeterminate}</p>
<button on:click={() => (indeterminate = !indeterminate)}>Toggle indeterminate</button>
```
---
https://github.com/user-attachments/assets/7814d0e7-2c92-4e7e-ad1d-981043a878b1
> fix(checkbox): bind indeterminate for Svelte 5 compatibility

- src/Checkbox/InlineCheckbox.svelte
Related #2044
`InlineCheckbox` is an internal component used by `DataTable` for batch selectable rows.
Bind `indeterminate` to the underlying input.
> fix(inline-checkbox): bind indeterminate for Svelte 5 compatibility

- src/DataTable/ToolbarMenu.svelte
Fixes #2040
The `$: if (menuRef) menuRef.style.top = "100%";` statement is causing an infinite update loop.
Setting `style` causes `menuRef` to update. Wrapped in a reactive statement, this produces an infinite update error in Svelte 5.
I looked up the Git blame for this line (#369). Historically, it seems this line was used for offsetting the menu position. However, `OverflowMenu` now manually handles this offset based on the button height, so this statement is redundant.
> fix(toolbar-menu): remove redundant menu offset for Svelte 5 compatibility

- package-lock.json
- package.json
- types/ComboBox/ComboBox.svelte.d.ts
- types/DataTable/ToolbarSearch.svelte.d.ts
- types/Dropdown/Dropdown.svelte.d.ts
- types/MultiSelect/MultiSelect.svelte.d.ts
Upgrades `sveld` to v0.22, which upgrades Prettier to v3. By default, trailing commas are enabled.
> chore(deps-dev): upgrade `sveld` to v0.22

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/DataTable/DataTable.svelte
- src/DataTable/DataTableTypes.d.ts
- tests/DataTable.test.svelte
- tests/DataTableAppendColumns.test.svelte
- tests/DataTableBatchSelection.test.svelte
- tests/DataTableBatchSelectionToolbar.test.svelte
- tests/DataTableNestedHeaders.test.svelte
- tests/RadioSelectableDataTable.test.svelte
- tests/SelectableDataTable.test.svelte
- types/DataTable/DataTable.svelte.d.ts
- types/DataTable/DataTableTypes.d.ts
This PR is based on #816. Closes #816
- Ugprades `sveld` to v0.20 to use generics
- Uses generics to type `DataTable` so that types for `rows` and `headers` can be inferred
@brunnerh Would love your thoughts on this. Seems like a straightforward win. I love the inferred types based on keys in `rows`. FWIW, this doesn't break existing usage (see the `DataTable.test.svelte` file) of exported props, since the generic parameter is optional (`<Row = DataTableRow>`).
> feat(data-table): support generics

- docs/src/pages/components/RecursiveList.svx
- docs/src/pages/components/TreeView.svx
Similar to #2054, also update docs on `RecursiveList` where the `children` prop was renamed or Svelte 5 compatibility.
> docs(recursive-list): update mentions of renamed `children` prop

- src/TreeView/TreeView.svelte
`$: nodes = traverse(nodes);` is unexpectedly mutating the original `nodes` reference used to render `TreeView`.
As a result, a tail leaf node is appended to the top-level list.
Flattening is necessary to obtain a reference to all node IDs (to programmatically show/hide nodes). This fix creates a new reference `flattenedNodes` instead of overriding the original `nodes`.
> fix(tree-view): do not traverse original `nodes`

- docs/src/components/ComponentApi.svelte
Reactive props are sorted first in the Component API documentation.
However, required props should also be factored in, and take precedence.
> docs(component-api): required props are sorted first

- docs/src/components/ComponentApi.svelte
- docs/src/components/PreviewTypeScript.svelte
Fix a race condition where non-reactive modules are not loaded before usage.
Instead, lazy load the component.
> docs(component-api): async load component

- docs/src/components/ComponentApi.svelte
- docs/src/components/PreviewTypeScript.svelte
- docs/src/global.css
- Removes stray `console.log`
- Adds bottom margin to "Default value" text
- Override syntax highlighting for light themes for readability (until a light theme palette is designed)
> docs: fix highlighting for lighter themes

- docs/src/components/Preview.svelte
Many docs examples are loaded via iframe. This is particularly so for DataTable.
Set [`loading="lazy"`](https://web.dev/articles/iframe-lazy-loading) on the iframe so that supported browsers defer loading (i.e., until the iframe is in the viewport).
> docs: set `loading="lazy"` on iframes

- docs/package-lock.json
- docs/src/COMPONENT_API.json
- docs/src/components/ComponentApi.svelte
- docs/src/components/Preview.svelte
- docs/src/components/PreviewTypeScript.svelte
- package.json
- scripts/format-component-api.js
Pre-process the COMPONENT_API.json to avoid using Prettier on the client-side. Reduces the bundle size. This also adds the slot detail to the component metadata section. Previously, only the slot name was included.
> docs: avoid code formatting on client-side

- src/MultiSelect/MultiSelect.svelte
- tests/MultiSelect/MultiSelect.test.ts
- tests/setup-tests.ts
Fixes #2066
I wrote some tests for the MultiSelect component while looking for possible fixes for https://github.com/carbon-design-system/carbon-components-svelte/issues/2066. If this is a useful addition, I’d be happy to include more cases or make revisions.
> fix(multi-select): fix sorting behavior for `top-after-reopen`

- .github/workflows/checks.yml
- docs/src/COMPONENT_API.json
- docs/src/components/ComponentApi.svelte
- scripts/format-component-api.js
Formats files and include the `lint` check as part of CI.
> ci: run `lint` check

- .prettierignore
- docs/src/COMPONENT_API.json
`COMPONENT_API.json` is auto-generated by Sveld and has its own format style.
Instruct Prettier to ignore this file. This should also make the lint step slightly faster.
> chore: exclude auto-generated `COMPONENT_API` from formatting

- src/TooltipIcon/TooltipIcon.svelte
The button element should have an explicit `type="button"` to avoid inadvertent form submission. If inside a `form`, the implicit role is "submit."
> fix(tooltip-icon): `button` should have explicit `type`

- tests/App.test.svelte
- tests/TreeView/TreeView.test.svelte
- tests/TreeView/TreeView.test.ts
Expand test coverage for the `TreeView` component, testing expand behavior using `expandAll` and `expandNodes` accessors.
Also scaffolds the testing GUI a bit more (ability to "route" components for easier preview). The test GUI is purely for the benefit of writing unit tests. The GUI is not used in the test run.
> test(tree-view): `expandAll` and `expandNodes`

- src/DataTable/DataTable.svelte
- tests/App.test.svelte
- tests/DataTable/DuplicateDataTables.test.svelte
Fixes #2081
Create an internal ID prefix for the radio buttons and checkboxes used within `DataTable`.
This addresses the case where multiple `DataTable` instances may be instantiated, and the data contains overlapping IDs in `rows`.
> fix(data-table): prefix internal ID for radio button, checkbox

- src/DataTable/DataTable.svelte
Improves the accessibility of an expandable `DataTable`.
Adds in missing:
- `aria-controls` < > `id` attributes
- Sets `aria-hidden="true"` on expandable icons since the button already has a label
> fix(data-table): improve `expandable` accessibility

- src/Dropdown/Dropdown.svelte
- src/MultiSelect/MultiSelect.svelte
Fixes #2083
There's a bug in Firefox where the focus is trapped inside the Dropdown button and MultiSelect field. I was able to repro with the latest FF version 134.0.1 (64-bit).
From my research, the symptoms seem similar to this [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=53579) (although the report itself is over a decade old, and has reportedly been fixed).
This removes the unnecessary manual `blur` in the "Tab" events. I've also tested Chrome, Safari, and the behavior is consistent.
> fix: avoid manual `blur` in `Dropdown`, `MultiSelect` to allow keyboard navigation in Firefox

- src/DataTable/DataTable.svelte
- tests/DataTable/DuplicateDataTables.test.svelte
Follow-up to #2082 (not yet released)
Each `input` for either a checkbox or radio variant should have an `id`. This should be used to avoid clashes between table instances. The `name` – on the other hand – should be the same across all rows (except the batch selection one).
#2087 allows customization for the input `name` value.
> fix(data-table): input `name` is stable while `id` is unique

- src/TextArea/TextArea.svelte
The [TextArea](https://svelte.carbondesignsystem.com/components/TextArea) component allows `null` [value](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/src/TextArea/TextArea.svelte#L2-L6), however the component breaks when a null value is provided/bound to the value property since "_Cannot read properties of null (reading 'length')_" at [line 88](https://github.com/carbon-design-system/carbon-components-svelte/blob/master/src/TextArea/TextArea.svelte#L88).
> fix(text-area): counter supports null `value`

- src/Tag/Tag.svelte
Fixes #2096
Interestingly, `<Tag filter on:close />` does not fire because the forwarded `on:click` uses the `stopPropagation` modifier.
Removing it allows the dispatched "close" event to fire. `on:close` is effectively an alias for `on:click`, which is only forwarded to the button for a filterable tag.
Both "click" and "close" should be logged.
```svelte
<Tag
filter
on:click={() => {
console.log("click");
}}
on:close={() => {
console.log("close");
}}
>
Tag
</Tag>
```
If the consumer manually stops propagation, "click" is logged but "close" will not. This works in Svelte 5, but not Svelte 4.
```svelte
<Tag
filter
on:click={(e) => {
e.stopPropagation();
console.log("click");
}}
on:close={() => {
console.log("close");
}}
>
Tag
</Tag>
```
> fix(tag): allow `on:close` to work with Svelte 5

- README.md
- docs/src/pages/index.svelte
The latest [`carbon-pictograms-svelte` release](https://github.com/carbon-design-system/carbon-pictograms-svelte/releases/tag/v13.2.0) brings up the total number of pictograms to 1212.
> docs: update number of `carbon-pictograms-svelte` to 1,200+

- src/OverflowMenu/OverflowMenu.svelte
Adds a missing `aria-controls` to the trigger element. The associated ID is the overflow menu.
> fix(overflow-menu): add `aria-controls` to trigger button

- docs/src/pages/components/UIShell.svx
- docs/src/pages/framed/UIShell/HeaderMultipleSwitcher.svelte
Adds an example with multiple switchers:
- Demo custom icon
- Demo tooltip usage
- Demo `text` usage
> docs(ui-shell): add "Header with multiple switchers" example

- src/Select/SelectItem.svelte
- tests/Select/Select.falsy.test.svelte
- tests/Select/Select.test.ts
Fixes #2117
The logical OR operator in `SelectItem` currently defaults to `value` if the provided `text` is falsy (e.g., empty string).
Intead, it should coalesce to `value` if `text` is `null` or `undefined`.
> fix(select): falsy item `text` should not override value

- src/UIShell/HeaderAction.svelte
Currently, the UI Shell only supports the dark theme. The `HeaderAction` panel should instruct browsers to apply a dark color scheme to the scrollbar.
> fix(ui-shell): `HeaderAction` uses dark color scheme

- src/ListBox/ListBoxMenuItem.svelte
- tests/ComboBox/ComboBox.test.ts
`ListBoxMenuItem` is used by `ComboBox`, `Dropdown`, and `MultiSelect`.
When the item has `disabled: true`, the disabled state for the item is applied. However, the `disabled` attribute on `<div role="option"` is invalid markup. This fixes it to use `aria-disabled` instead.
> fix(list-box): use `aria-disabled` instead of invalid `disabled` attribute

- src/Notification/InlineNotification.svelte
- src/Notification/ToastNotification.svelte
The `kind` prop influences the style used for `InlineNotification` and `ToastNotification`.
However, the raw value is currently set on the underlying `div` element (e.g., `<div kind="info"`). `kind` is not a valid attribute, and exposing it in the markup feels unpolished. It was initially added [six years ago.](https://github.com/carbon-design-system/carbon-components-svelte/commit/94dceae1fba3c9ae37fb2e1d58b84a64f4ecfad7#diff-b2b441bceba9a2a52c4a99d48160c7a45775a0dfd044b60f9d82d862b8a162f0R37) This will no doubt [cause breakage](https://www.hyrumslaw.com/) if consumers rely on `[kind=*]` for styling or selection.
> fix(notification): remove invalid `kind` prop from markup

- src/Theme/Theme.svelte
- tests/Theme/Theme.test.ts
Similar to #2126, using `Theme` as either a toggle or select will pass the internal `themes` prop down to the DOM element.
Nothing breaking with this, but it feels unpolished.
This fixes it to avoid passing `themes` down to the rendered element.
> fix(theme): remove invalid `themes` prop from markup

- src/MultiSelect/MultiSelect.svelte
Fixes #2128
If `MultiSelect` is provided `disabled` items, keyboard navigation (up/down arrows) should "skip" over disabled items. Currently, there's a bug where it's out-of-sync. The reason is that the keyboard logic references `items` when `MultiSelect` computes it as either `filteredItems` or `sortedItems`. Repro with the ["Disabled items"](https://svelte.carbondesignsystem.com/components/MultiSelect#disabled-items) example in the docs.
```svelte
<MultiSelect
items={[
{ id: "1", text: "Email", disabled: true },
]}
/>
```
After internal sorting, "Email" is surfaced on top.
The solution is to use either the `filteredItems` or `sortedItems` in the skip logic. An additional optimization is to store the `length` of `itemsToUse` instead …
> fix(multi-select): fix keyboard navigation for disabled items

- src/ListBox/ListBoxMenuItem.svelte
- tests/ComboBox/ComboBox.test.ts
Reverts carbon-design-system/carbon-components-svelte#2125
It turns out that changing `disabled` --> `aria-disabled` did cause a style regression here. Carbon v10 styles targets the `[disabled]` attribute.
Reverting this change.
> Revert "fix(list-box): use `aria-disabled` instead of invalid `disabled` attribute"

- src/ListBox/ListBoxSelection.svelte
- tests/ComboBox/ComboBox.test.ts
- tests/MultiSelect/MultiSelect.test.ts
Identified in #2131
`ListBoxSelection` is used by `MultiSelect` and `ComboBox`.
Currently, it uses the incorrect aria-label for the clear selection button. It's using the `translateId` (e.g., `"clearAll"`) instead of the user-friendly copy.
A follow-up would be to adjust the copy based on `selectionCount`. For example, for `MultiSelect`, there may be multiple values selected. For `ComboBox`, it wouldn't make much sense to have "Clear all selected items" if there is only one selected item.
> fix(list-box-selection): fix `aria-label` for clear button

- COMPONENT_INDEX.md
- docs/src/COMPONENT_API.json
- src/RadioButton/RadioButton.svelte
- tests/RadioButton/RadioButton.test.svelte
- tests/RadioButton/RadioButton.test.ts
- types/RadioButton/RadioButton.svelte.d.ts
Identified in https://github.com/carbon-design-system/carbon-components-svelte/pull/2131
`focus` and `blur` events should be forwarded to the underlying `input` element used in `RadioButton`.
```svelte
<RadioButton on:focus on:blur />
```
> fix(radio-button): forward `focus`, `blur` events

- src/Tile/RadioTile.svelte
- tests/RadioTile/RadioTile.test.ts
Identified in https://github.com/carbon-design-system/carbon-components-svelte/pull/2131
Although `RadioTile` is intended to be used inside a `TileGroup`, it feels unpolished for standalone usage to crash. This is because no parent context is found.
This fixes `RadioTile` to fail open by supplying an `add: () => {}` no-op in the case where `TileGroup` context does not exist.
> fix(radio-tile): allow standalone `RadioTile` usage

- src/TextArea/TextArea.svelte
- tests/TextArea/TextArea.test.ts
Identified in https://github.com/carbon-design-system/carbon-components-svelte/pull/2131
This fixes an accessibility issue with `TextArea`.
Currently, if `hideLabel` is `true`, the label for the `textarea` is not rendered at all. The expected behavior is that it should be visually hidden to still be available to screen readers.
> fix(text-area): allow visually hidden label

- src/ListBox/ListBoxMenuItem.svelte
- tests/ComboBox/ComboBox.test.ts
This re-applies https://github.com/carbon-design-system/carbon-components-svelte/pull/2125, which was reverted in #2130
Carbon styles depend on the `[disabled]` attribute. The `disabled` attribute is not valid mark-up when applied to `div role="option"`, so this PR preserved the existing `disabled` attribute while also setting `aria-disabled`.
> fix(list-box): set `aria-disabled` if `disabled` (#2125)

- src/ListBox/ListBoxSelection.svelte
- tests/ComboBox/ComboBox.test.svelte
- tests/ComboBox/ComboBox.test.ts
- tests/MultiSelect/MultiSelect.test.ts
The `ListBoxSelection` component now properly handles translations for the clear button based on the selected items:
- Fix `buttonLabel` and `description` to use the same translation logic
- Add tests for custom translations in both `ComboBox` and `MultiSelect`
Stylistically, use an explicit `selectionCount === undefined` to use the default `clearSelection` id.
> fix(list-box): correct button/description translations based on selection count

- src/utils/toHierarchy.js
- tests/TreeView/toHierarchy.test.ts
Use a single-pass approach (one Map, one for loop) for `toHierarchy` used to flatten nodes.
> perf(to-hierarchy): optimize to use single-pass approach

- src/DataTable/ToolbarSearch.svelte
- tests/DataTable/DataTableSearch.test.ts
Fixes #2143
Currently, `ToolbarSearch` filtering is not reactive. The component reads `DataTable` rows passed via Svelte context. The expected behavior is that the filtered rows are updated if `rows` passed to `DataTable` (the source of truth) updates.
The solution is to subscribe to the rows passed down from `DataTable`. The key is to only run `filterRows` in the `afterUpdate` callback to avoid an infinite update loop.
> fix(toolbar-search): re-filter rows if `DataTable` rows change

- src/ComposedModal/ComposedModal.svelte
Silence another a11y warning if using Svelte 5.
> fix(composed-modal): ignore a11y warning in Svelte 5

- src/ListBox/ListBoxSelection.svelte
- tests/ComboBox/ComboBox.test.svelte
- tests/ComboBox/ComboBox.test.ts
Fixes #2166 
The clear button in the ComboBox currently only supports the "Enter" key for keyboard navigation. It should support "Space."
This makes it consistent with the behavior of the Search button and the upstream React implementation.
> fix(combo-box): clear button supports "Space" key

- src/ComboBox/ComboBox.svelte
- tests/ComboBox/ComboBox.test.ts
Fixes [#2167](https://github.com/carbon-design-system/carbon-components-svelte/issues/2167)
Currently, "Escape" only closes the combobox menu. Pressing "Escape" should also clear the value. This is consistent with the Search component and the upstream React implementation. The input focus should be retained.
> fix(combo-box): "Escape" key clears input value

- README.md
- docs/src/pages/index.svelte
There are now 2,521 Carbon icons in the latest release: https://github.com/carbon-design-system/carbon-icons-svelte/releases/tag/v13.5.0
> docs: update number of `carbon-icons-svelte` to 2,500+

- .github/workflows/checks.yml
Parallelize the existing job into three:
- lint
- test
- types
Also skips checks if the PR contains changes to non-relevant source code files (Markdown, docs/examples folders)
With `deploy-docs` relying on all three passing.
> [CI] Optimize `checks.yaml`

- src/OverflowMenu/OverflowMenu.svelte
- tests/OverflowMenu/OverflowMenu.test.ts
Fixes #2197
The dynamically computed width is used to control the width of the shadow on `:after`. Without this, the shadow of the menu will overshadow the button when it is opened.
There is a performance issue: an overflow menu may be rendered hundreds of times. This is not uncommon with tables.
The fix, suggested by @brunnerh in #2197, is elegant: instead of injecting styles into the DOM for each overflow menu, re-use a CSS global rule referencing a single custom property.
**Performance Improvements**
- Linear performance: there will only be one global class for *n* component instantiations.
- Less specificity. Previously, the `id` was used to scope styles.
- Avoids DOM pollution and reduces browser memory usage.
This PR also adds unit tests to guard against regressions.
> fix(overflow-menu): avoid dynamic style injection for performance

- src/Pagination/Pagination.svelte
- tests/Pagination/Pagination.test.ts
Currently, `on:change` in Pagination dispatches with the previous value. Pagination should use `on:update` instead.
> fix(pagination): `on:change` dispatches with correct value

- docs/src/pages/framed/DataTable/DataTableAppendColumns.svelte
The overflow column has an auto-width by default. Fix the example to demonstrate usage of the a fixed width column as applied to the example.
```
40px button width + 32px padding = 72px
```
More generally:
- Are width/minWidth props documented? Do they only apply on table header cells?
- What are the "reserved" header keys? Are these enforced/documented via TypeScript?
---
> docs(data-table): set width on empty column with overflow menu

- src/DataTable/DataTable.svelte
- tests/DataTable/DataTable.test.ts
Fixes #2193
In #2193, a `DataTable` with dynamic, mismatched headers and rows can crash with:
```sh
TypeError: Cannot read properties of undefined (reading 'empty')
```
If keys are mismatched between headers, `#if headers[j].empty` may cause a runtime error (i.e., the error message above).
The root cause was in the reactive statement creating `tableCellsByRowId` which used `headerKeys.map()` but then accessed headers[index].
The solution is to consolidate `headers` directly, and stub out potentially missing properties to eliminate the potential for the out-of-bounds array access.
> fix(data-table): handle dynamic `headers`
